### ISSUE TITLE
Stream.tails leaks memory

### ISSUE THREAD

**Issue by scabug** [scala/bug#10131]
this code causes OOME

```scala
  def stream = Stream.continually(new Array[Byte](1024 * 1024))
  stream.tails.take(100000).foreach{_ => }
```

generated Iterator has reference to underlying stream via calling `newBuilder`
https://github.com/scala/scala/blob/v2.12.1/src/library/scala/collection/TraversableLike.scala#L806

**Comment by szeiger** [comment]
Moving to backlog because `Stream` is deprecated.

**Comment by NthPortal** [comment]
`LazyList` does not OOM here.

`Stream` still does this in 2.13 M5.

**Comment by counter2015** [comment]
`LaszList` in 2.13.2 causes OOME in my test environment
```scala
Welcome to Scala 2.13.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> def stream = LazyList.continually(new Array[Byte](1024 * 1024))
def stream: scala.collection.immutable.LazyList[Array[Byte]]

scala> stream.tails.take(100000).foreach{_ => }
java.lang.OutOfMemoryError: Java heap space
  at $anonfun$stream$1(<console>:1)
  at $Lambda$992/447477005.apply(Unknown Source)
  at scala.collection.immutable.LazyList$.$anonfun$continually$1(LazyList.scala:1198)
  at scala.collection.immutable.LazyList$$$Lambda$998/1867108691.apply(Unknown Source)
  at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state$lzycompute(LazyList.scala:230)
  at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state(LazyList.scala:223)
  at scala.collection.immutable.LazyList.isEmpty(LazyList.scala:240)

```

**Comment by NthPortal** [comment]
you are correct; my apologies. assigning to myself to fix the `LazyList` portion

**Comment by NthPortal** [comment]
arguably this is a problem with `Iterator.iterate`, in that it closes over the `start` parameter

**Comment by NthPortal** [comment]
update: in actuality, it is the implementation of `tails` (in `LinearSeqOps`) that is broken. the implementation is as follows:

```scala
  override def tails: Iterator[C] =
    Iterator.iterate(coll)(_.tail).takeWhile(_.nonEmpty) ++ Iterator.single(newSpecificBuilder.result())
```

the last element in the iterator is lazy, but invokes `newSecificBuilder` on the initial collection. thus, it retains a reference to the head of the collection, and leaks memory.

the fix for this problem is to eagerly create the `Iterator.single`, and it fixes both `LazyList` and `Stream`. alternatively, you could make the implementation track whether the previous element was empty, and then you don't need to concat the iterators at all, but that seems less efficient
