### ISSUE TITLE
Re-initialization of transient lazy val not working after de-serialization

### ISSUE THREAD

**Issue by scabug** [scala/bug#10244]
Accessing a transient lazy val from a trait after an object was de-serialized causes a `NullPointerException` *if* the lazy val was accessed *before* the object was serialized.

One can reproduce this problem with the following classes:

```
class NotSerializable {
  def foo = "bar"
}

trait Base extends Serializable {
  @transient
  protected lazy val notSerializable = new NotSerializable
}

class BaseImpl extends Base {
  def check: Boolean = Try(notSerializable.foo).isSuccess
}
```

If you create an instance of `BaseImpl`, serialize and de-serialize this instance calling `check` works without problems.
If you create an instance, call `check`, serialize and de-serialize this instance calling check causes a `NullPointerException`.

**Comment by sarahgerweck** [comment]
The issue here is that the fix in #10075 marked the actual member as transient, but any transient fields need to have their associated bitmap marked as transient as well.

**Comment by sarahgerweck** [comment]
@adriaanm any thoughts? It looks to me like the code is trying to do the right thing, but it is not realizing that these values need to use the transient bitmap. This has just become a supermassive headache for me, so I'd love it if there were a fix (or at least a diagnosis that could lead somebody to fix it themselves).

**Comment by adriaanm** [comment]
Thanks for the analysis! I'll see if I can fix this in 2.12.3

**Comment by sarahgerweck** [comment]
@adriaanm in case it's helpful, this is the line that seems to be _trying_ to correctly decide between the two bitmaps: https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/transform/AccessorSynthesis.scala#L134

**Comment by adriaanm** [comment]
> wondered if maybe the transient information isn't present when this is called

Yep, the logic operates on the getters (which don't have the `transient` annotation) and then tries to link these to the field (which do have the expected annotation). The problem is that we cannot use `accessed` to get to the field from the getter in a class where these fields are inherited from a trait, because we are in the process of transforming the info of the class to add the members and their additional symbols as inherited from any supertraits, and are about to enter them into the class's decls (in its info, a ClassInfoType), but have not yet done so.  Because the decls have not yet been entered,  `accessedOrSelf` in `def hasTransientAnnot(field: Symbol) = field.accessedOrSelf hasAnnotation TransientAttr` returns NoSymbol.

**Comment by adriaanm** [comment]
wip: https://github.com/scala/scala/compare/2.12.x...adriaanm:i10244-bitmaps-for-fields?expand=1
