### ISSUE TITLE
Can't exclude `unused` warnings from -Xlint

### ISSUE THREAD

**Issue by ghik** [scala/bug#10294]
Scala 2.12.2
```scala
object Unused {
  private val stuff = 5
}
```
Then:
```
$ scalac -Xlint Unused.scala
Unused.scala:2: warning: private val stuff in object Unused is never used
  private val stuff = 5
              ^
one warning found
```
which is ok, but the warning should go away when using one of these:
```
$scalac -Xlint:_,-unused Unused.scala
$scalac -Xlint -Ywarn-unused:_,-privates Unused.scala
$scalac -Ywarn-unused:_,-privates Unused.scala
```
and it doesn't.

Currently the only way to have `-Xlint` enabled without unused warnings is to use `-Xlint` with all the types of warnings explicitly listed and `unused` intentionally omitted.

And by the way: the only reason I want to disable `unused` is because it's often wrong (more issues incoming).

**Comment by xuwei-k** [comment]
duplicate? https://github.com/scala/bug/issues/10270

**Comment by ghik** [comment]
Yes, possibly. Sorry, I don't know how I missed it.

**Comment by ghik** [comment]
It seems that this version works:
```
$scalac -Xlint:-unused,_ Unused.scala
```
I didn't realize this syntax is possible.

**Comment by som-snytt** [comment]
The compiler settings couldn't quite model the interactions we intend between `-Xlint` and `-Ywarn-unused`.

In summary, `-Xlint:unused` is a boolean, but it turns on/off an expanding option on `-Ywarn-unused`. That has the desired semantics because an expanding option is lowest priority. 

https://github.com/scala/scala/pull/5879
