### ISSUE TITLE
Implicit conversions precedence

### ISSUE THREAD

**Issue by kamilkloch** [scala/bug#10329]
Define
```scala
class A

object A {
  implicit class AOps(val a: A) {
    def *(b: Double): A = new A
  }
}
```
As expected,
```scala
scala> new A * 3.0
res0: A = A@735b478
```
Add
```
class B

implicit class AOps2(val a: A) {
  def *(b: Double)(implicit ev: B): A = new A
}
```
Now, 
```scala
scala> new A * 3.0
<console>:12: error: could not find implicit value for parameter ev: B
              new A * 3.0
                    ^
```
Compiler, despite the lack an implicit `B`, decides for a locally defined `AOps2` implicit conversion (over the conversion from the `A`'s companion object) and then fails. I suppose it has to to with the implicit `B` being curried, but still, it does not feel right.

**Comment by som-snytt** [comment]
As described [in the spec](http://www.scala-lang.org/files/archive/spec/2.12/07-implicits.html#implicit-parameters), first it considers `AOps2` because `AOps2` is available by normal scoping. So that's the error you get. Otherwise, it would consider "implicit scope", which includes members of the companion.

Your intuition is that, lacking an implicit B, it should ignore `AOps2`. Should it also ignore the following error?

```
scala> implicit class AOps2(val a: A) {
     |   def *(b: Double)(implicit ev: B): Double = 3.14 }
defined class AOps2

scala> new A * 3.0
<console>:15: error: could not find implicit value for parameter ev: B
       new A * 3.0
             ^

scala> implicit val b: B = null
b: B = null

scala> new A * 3.0
res1: Double = 3.14

scala> new A * 3.0 : A
<console>:16: error: type mismatch;
 found   : Double
 required: A
       new A * 3.0 : A
             ^

```
