### ISSUE TITLE
Inconsistent exhaustive compiler warning (single vs tuple match)

### ISSUE THREAD

**Issue by didii** [scala/bug#10373]
When using tuples, the compiler correctly generates the `match may not be exhaustive` warning for non-sealed classes. When using a direct pattern match, this is not the case.

    abstract class Foo {
        def bar(): Unit = this match {
            case Foo_1() => //do something
            case Foo_2() => //do something
            // Works fine
        }
        
        def baz(that: Foo): Unit = (this, that) match {
            case (Foo_1(), _) => //do something
            case (Foo_2(), _) => //do something
            // match may not be exhaustive
        }
    }
    case class Foo_1() extends Foo
    case class Foo_2() extends Foo

This generates only the following warning:

    Warning:(12, 23) match may not be exhaustive.
    It would fail on the following input: (_, _)
        def baz(): Unit = (this, Foo_1()) match {

Meaning that for the *non-sealed* class `Foo`, the match in `bar()` is fine while `baz()` is not even though they are effectively the same.

-----

* Scala welcome message:
    > Welcome to Scala 2.12.1 (Java HotSpot(TM) Client VM, Java 1.8.0_131).
* Using `sealed abstract class Foo` removes the warning as expected inferring that `bar()` should also generate this message
* Might be related to issue https://github.com/scala/bug/issues/9630 even though this was fixed in 2.12.0-M4
* Might be related to issue https://github.com/scala/bug/issues/10019 which is the reverse of this

**Comment by dwijnand** [comment]
Just leaving some investigation notes:

The difference in behaviour comes down to the fact that in the single case `Foo` not being sealed means that exhaustivity stops short (from `-Ypatmat-debug` after some data massaging):

```
reachability, vars:
  V1: Foo ::= Foo_1 | Foo_2 | null | ... // = x1

equality axioms:
  And()
```

from `def exhaustive`: `if (uncheckableType(prevBinder.info)) Nil`

In the tuple case it initially considers the tuple to be `null` and then it discards that information which is why it ends with `(_, _)`:

```
reachability, vars:
  V1: (Foo, Foo) ::= (Foo, Foo) | null// Set((Foo, Foo), null) // = x1
  V2: Foo ::= Foo_1 | Foo_2 | null | ... // = x1._1

equality axioms:
  And(
    Or(V1=(Foo, Foo)#5, V1=null#1),
    AtMostOne(V1=(Foo, Foo)#5, V1=null#1)
  )

var assignment for model Map(V1=Foo_1#6 -> false, V1=Foo_2#7 -> false):
  V1(=x1._1: Foo) == () != (Foo_1, Foo_2)

describing (V1,List(),List(Foo_1, Foo_2),Map(),class Foo,true)
described as: Some((x: Foo forSome x not in (Foo_1, Foo_2)))

describing (V2,List(),List(),Map(value _1 -> Some((x: Foo forSome x not in (Foo_1, Foo_2)))),class Tuple2,true)
  describing (V1,List(),List(Foo_1, Foo_2),Map(),class Foo,true)
  described as: Some(_)
described as: Some((_, _))
```

I'm not sure why the `x: Foo forSome x not in (Foo_1, Foo_2)` is lost in the nested time... 😕

I'm also not sure why it considers the tuple a `checkableType`, even the fact that (as it says) "tuple types with at least one component of a checkable type as a checkable type" makes no sense with the components still being both `Foo`. ¯\\_(ツ)_/¯
