### ISSUE TITLE
compiler doesn't allow to define matching .apply manually

### ISSUE THREAD

**Issue by HuStmpHrrr** [scala/bug#10383]
following code generates error, which is not expected:

```scala
Welcome to Scala 2.12.1 (OpenJDK 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

case class Foo(s: String)
object Foo { def apply(s: String) = new Foo(s) }

// Exiting paste mode, now interpreting.

<pastie>:13: error: method apply is defined twice;
  the conflicting method apply was defined at line 14:25
       case class Foo(s: String)
```

from the [specification](https://www.scala-lang.org/files/archive/spec/2.12/05-classes-and-objects.html#case-classes):

> If the object c already has a matching apply (or unapply) member, no new definition is added.

obviously, I am defining a matching `.apply`, hence the compiler shouldn't complain and simply accept my definition, instead of adding another definition of `.apply`. this behavior doesn't comply to the specification.

**Comment by SethTisue** [comment]
You're on 2.12.1, but this wasn't allowed until 2.12.2.

**Comment by HuStmpHrrr** [comment]
@SethTisue can you elaborate? this part has existed at least in 2.11:

https://www.scala-lang.org/files/archive/spec/2.11/05-classes-and-objects.html#case-classes

**Comment by SethTisue** [comment]
it was added in 2.11.11; see https://github.com/scala/scala/releases/tag/v2.11.11. 2.12.2 includes all the 2.11.9/2.11.10/2.11.11 changes; see https://github.com/scala/scala/releases/tag/v2.12.2

in 2.12.2, you can do it by default, but in 2.11.11, a late decision was made to put it behind `-Xsource:2.12` instead of having it enabled by default. at that time that decision was made, the 2.11 spec change should also have been reverted. a PR fixing that in the 2.11 spec would be welcome

**Comment by SethTisue** [comment]
note that in general, it isn't valid to reason that everything you see in _any_ 2.11.x release is also present in _every_ 2.12.x release. some 2.11.x releases are newer than some 2.12.x releases
