### ISSUE TITLE
Name clash when case class and user-defined case apply both have defaults

### ISSUE THREAD

**Issue by lrytz** [scala/bug#10389]
In 2.12.2 and 2.11.11 under `-Xsource:2.12`:

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

case class C(x: Int = 1)
object C { def apply(x: Int = 1) = new C(x) }

// Exiting paste mode, now interpreting.

<console>:11: error: double definition:
def apply$default$1: Int at line 12 and
def apply$default$1: Int at line 11
have same type
       case class C(x: Int = 1)
                    ^
```

**Comment by adriaanm** [comment]
Lukas, could you look into a fix?

**Comment by lrytz** [comment]
When unlinking the synthetic `apply`, I find both `apply$default$1` symbols in the owner's scope, and I don't know how to tell which one belongs to the synthetic `apply` method. We don't store any references between method symbols and their default getters, the approach is purely based on naming.

Maybe I need to introduce a symbol attachment for default getters of `apply` methods that points  back to the `apply` symbol. This could easily be done at the point where the default getter is created.

Other ideas?

**Comment by adriaanm** [comment]
The second, more direct approach sounds nicer. I can't think of anything better. Are we going to get into trouble with substitution/cloning and lose track of the default getters somehow? The only gotcha that comes to mind.

**Comment by estsauver** [comment]
Xx A

On Jun 23, 2017 11:26 PM, "Adriaan Moors" <notifications@github.com> wrote:

The second, more direct approach sounds nicer. I can't think of anything
better. Are we going to get into trouble with substitution/cloning and lose
track of the default getters somehow? The only gotcha that comes to mind.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scala/bug/issues/10389#issuecomment-310776820>, or mute
the thread

**Comment by estsauver** [comment]
Xx A
