### ISSUE TITLE
scala.Boolean.box problem casting from java.lang.Boolean 

### ISSUE THREAD

**Issue by carloscaldas** [scala/bug#10396]
Check out the following instructions at REPL

```scala
scala> scala.util.Properties.versionString
res0: String = version 2.12.1

scala> val jb : java.lang.Boolean = null
jb: Boolean = null

scala> val sb : Option[scala.Boolean] = Option(jb)
sb: Option[Boolean] = Some(false)

scala> val sb : Option[scala.Boolean] = Option(jb).map(x => x)
sb: Option[Boolean] = None

**scala> scala.Boolean.box(jb)**
res3: Boolean = false
```

**Comment by hrhino** [comment]
I'm inclined to believe that this is, strange as it may seem, correct behavior.

<a name="part1" />

```scala
val sb: Option[scala.Boolean] = Option(jb)
```

This is equivalent to 
```scala
val sb = Option(jb) : Option[scala.Boolean]
```
that is, `Option(jb)` [is expected to conform to](https://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#typed-expressions)  `Option[scala.Boolean]`. Because of this, the type parameter of `Option.apply(jb)` is inferred to be `scala.Boolean`, and you wind up with
```scala
val sb = Option.apply[scala.Boolean](jb)
```

Now, in this case `Option.apply` wants a `scala.Boolean` argument, but you are giving it a `java.lang.Boolean` argument. There is an implicit conversion `scala.Predef.Boolean2boolean` which does this conversion, defined as 
```scala
  implicit def Boolean2boolean(x: java.lang.Boolean): Boolean = x.asInstanceOf[Boolean]
```

Because of [the semantics of `null.asInstanceOf`](https://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#the-null-value), this returns `false` (the [default value](https://www.scala-lang.org/files/archive/spec/2.12/04-basic-declarations-and-definitions.html#value-declarations-and-definitions) of `scala.Boolean`).

Therefore, you have
```scala
val sb: Option[scala.Boolean] = Option.apply[scala.Boolean](Boolean2boolean(null))
```

which evaluates to `Option.apply(false)`.

<hr />

As for your second defininition of `sb`:
```scala
val sb: Option[scala.Boolean] = Option(jb).map(x => x)
```

The difference between this and <a href="#part1">the previous similar definition</a> is that the type ascription falls on the result of the `map` call:

```scala
val sb = Option(jb).map(x => x) : Option[scala.Boolean]
```

and therefore the expression `Option(jb)` is typed without an [expected type](https://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#expression-typing). Because its argument `jb` has type `java.lang.Boolean`, the type parameter of `Option.apply` is inferred to be that type, and we get

```scala
val sb = Option.apply[java.lang.Boolean](jb).map(x => x) : Option[scala.Boolean]
```

However, `Option.apply(jb)` will evaluate `Option.apply(null)`, which is `None`. The `.map` call is never executed, as can be seen by adding a side effect:

```scala
scala> val sb = Option(jb).map(x => { println("I was called!"); x }) : Option[scala.Boolean]
sb: Option[Boolean] = None
```

<hr />

Finally, the call to `scala.Boolean.box` works similarly to the first case: it expects an argument of type `scala.Boolean`, but you're giving it a `java.lang.Boolean`; the implicit conversion `Boolean2boolean` kicks in; `null` is converted to the default value `false`, and `scala.Boolean.box` boxes it to `java.lang.Boolean.FALSE`.

<hr />

I agree with you that this is, at a minimum, highly surprising behavior (and possibly deserves a place on [Scala Puzzlers](http://scalapuzzlers.com/)!). However, I'm inclined to close this as being spec conformant behavior. I'll leave it open for a bit for someone smarter than I to explain where I slipped up.

Have a nice day!

**Comment by DarkDimius** [comment]
This is intentional behavior: null is unboxed to default value of 
respectful type.

This is needed to correctly handle default initialization under generics:

```

class F[T]{
 var s : F = _
}

new F[Int].s // should be 0
```

**Comment by SethTisue** [comment]
this is something of an FAQ. does anyone know what the canonical ticket on this is? I did some searching just now but didn't find it.
