### ISSUE TITLE
Immutable maps have inconsistent behaviour on update

### ISSUE THREAD

**Issue by mkeskells** [scala/bug#10415]
I was writing some additional unit test and uncovered a bug or two in my code and some odd behaviour in HashMap and friends, in that when updating a Map the semantics are inconsistent

I think that we need some rules and guidelines for what the semantics of an update are
something like
"if the newly inserted key == the existing key and the values are the same the map is unchanged, otherwise a new map it returned containing the new key and value"
I am not sure who owns these libraries, the semantic definition, and whether this is a change for 2.12 or 2.13, or even if you agree. I would be happy to work on this change after confirmation of the semantics required  

I had a look at the implementations of += updated etc in the various immutable maps, and they seem inconsistent, and overly memory thirsty 

for Map1-4 keys and values are compared with ==, keys a retained if values differ
when adding keys are compared with == values is ignored even if identical
Strangely the original key is maintained - **this looks to be a bug IMO**

```scala
    override def updated [V1 >: V] (key: K, value: V1): Map[K, V1] =
      if (key == key1) new Map1(key1, value)
      else new Map2(key1, value1, key, value)
```

For a HashMap.HashMap1 the comparison is done via identity of the AnyRef view of the value
this can introduce boxing overheads, and false memory churn where the keys and values are primitives due to the vaguaries of boxing

```scala
    private[collection] override def updated0[B1 >: B](key: A, hash: Int, level: Int, value: B1, kv: (A, B1), merger: Merger[A, B1]): HashMap[A, B1] =
      if (hash == this.hash && key == this.key ) {
        if (merger eq null) {
          if (this.value.asInstanceOf[AnyRe f] eq value.asInstanceOf[AnyRef]) this
          else new HashMap1(key, hash, value, kv)
```
ListMap doesnt bother checking the values, it always removes and adds a new (key,value) at the head
This is used in HashMap.HashMapCollision1, as well as directly as a collection class

ListMap implementation is out of step with its scaladoc which states 
  * This class implements immutable maps using a list-based data structure. List map iterators and
  * traversal methods visit key-value pairs in the order whey were first inserted.
IMO I dont thisnk that the order is part of this spec, and limits optimisations anyway, and since it is not correct
I personally think that the scaladoc should not include the ordering

```scala
    override def +[B2 >: B1](kv: (A, B2)): ListMap[A, B2] = {
      val m = this - kv._1
      new m.Node[B2](kv._1, kv._2)
    }
``` 

HashTrieMap just delegated to children (HashMap1, HashMapCollision1,HashTrieMap)
so this will follow the semantics of the children, but currently be a victim to the over copying of the data from
HashMap1 and HashMapCollision1

---

Having a quick look at other Maps
TreeMap always creates
```
override def updated [B1 >: B](key: A, value: B1): TreeMap[A, B1] = new TreeMap(RB.update(tree, key, value, overwrite = true))
```
as does IntMap, LongMap etc

----

Looking a the mutable Maps
ListMap always replaces unconditionally
LinkedHashMap, AnyRefMap, and HashMap updates the value and retains the key

some code that I was using to investigate

```scala
package scala.collection.immutable
class Test(val v1:Any, memo:String = "") {
  override def equals(o:Any) = o match {
    case other:Test => v1 == other.v1
    case ignore => false
  }
  override def hashCode = 0
  override def toString=s"Test[$v1, $memo]"
}

object MapBehaviour extends App {
  val smallMap = new Map.Map1[Any,Any](0,0) + (0.0 -> 0.0)
  println (s"smallMap - $smallMap ${smallMap.getClass}")

  val listMap1 = ListMap[Any,Any](0 -> 0) + (1 -> 1)
  val listMap2 = listMap1 + (0 -> 0)
  println (s"listMap1,2 - $listMap1  $listMap2")

  val hashMap1 = HashMap[Any,Any]() + (0 -> 0) + (0.0 -> 0.0)
  println (s"hashMap1 - $hashMap1 ${hashMap1.getClass}")

  val hashMap10 = HashMap[Any,Any]() + (0 -> 0)
  val hashMap11 = hashMap10 + (0 -> 0)

  println(s" hashmap10, 11 ${hashMap10 == hashMap11}  ${hashMap10 eq hashMap11} ")

  val hashMap20 = HashMap[Any,Any]() + (0.0 -> 0.0)
  val hashMap21 = hashMap20 + (0.0 -> 0.0)

  println(s" hashmap20, 21 ${hashMap20 == hashMap21}  ${hashMap20 eq hashMap21} ")
}

```

and the output ...

```scala
smallMap - Map(0 -> 0.0) class scala.collection.immutable.Map $Map1
listMap1,2 - ListMap(0 -> 0, 1 -> 1)  ListMap(1 -> 1, 0 -> 0)
hashMap1 - Map(0.0 -> 0.0) class scala.collection.immutable.Has hMap$HashMap1
 hashmap10, 11 true  true 
 hashmap20, 21 true  false 
```

**Comment by szeiger** [comment]
Hi Mike,

> I am not sure who owns these libraries, the semantic definition, and whether this is a change for 2.12 or 2.13, or even if you agree.

I think we can easily agree that something is wrong here but it's harder to define what behavior is actually correct and what is not. I expect in some cases it will come down to making the spec clearer and then implementing whatever was specified. Therefore I don't expect this will lead to any changes in 2.12. It should be split up into multiple tickets in https://github.com/scala/collection-strawman. @Ichoran is probably the person with the most experience in this area and can provide additional input.

> I had a look at the implementations of += updated etc in the various immutable maps, and they seem inconsistent, and overly memory thirsty

You only mentioned maps in your explanation. `+=` is really `+` and present in all collections, so we should also consider consistency with sets. In particular, for immutable sets, the documentation says: "Elements that already exist in the immutable hash set will not be added." Should `updated` be consistent with `+` or treat keys and values differently?

> Strangely the original key is maintained - this looks to be a bug IMO

For `updated` this could be considered a feature. But nobody knows because the semantics are not specified.

> For a HashMap.HashMap1 the comparison is done via identity of the AnyRef view of the value
this can introduce boxing overheads, and false memory churn where the keys and values are primitives due to the vaguaries of boxing

Without specialization an `Any` value is already boxed, so there is no extra overhead here. The cast to `AnyRef` is a no-op. The current collections are generally not a good fit when you want the best performance for primitive values. I assume the comparison with `eq` is done to keep the overhead low. When in doubt it's faster to create a new small MapN than doing a proper equality check.

> traversal methods visit key-value pairs in the order whey were first inserted.
IMO I dont thisnk that the order is part of this spec, and limits optimisations anyway, and since it is not correct
> I personally think that the scaladoc should not include the ordering

Isn't ordered traversal the main point of using ListMap?

> Having a quick look at other Maps

Looks quite inconsistent.  In the case of mutable maps there is also `update` in addition to `updated`. The former has a more precise specification. We should consider using the same semantics for `updated` for better consistency.

**Comment by som-snytt** [comment]
Not an expert, I have to remind myself as needed.

```
scala> case class C(c: Int)(val d: Int)
defined class C

scala> val vs = new java.util.HashMap[C, Int]()
vs: java.util.HashMap[C,Int] = {}

scala> vs.put(new C(1)(42), 42)
res0: Int = 0

scala> vs.put(new C(1)(17), 17)
res1: Int = 42

scala> vs.forEach((k,v) => println(s"$k,${k.d},${v}"))
C(1),42,17
```
For keys and set members, only hashcode and equals matter.

**Comment by mkeskells** [comment]
@szeiger 
I think the main purpose of ListMap in that it stores in a List-like structure, and doesn't depend on hashCode. I would think that the ordering is a separate concern, like java LinkedHashMap
TBH I dont really care if the ordering is specified. IMO you should specify to minimum that doesn't limit implementation, but provides facility. I dont think that you want to box yourself into a corner without due cause. In this case ListMap is only a concern because it is used by HashMap, and that implementation in not part of the specification and could be changed

My concern with ListMap is that the scaladoc and the implementation are not in alignment

Re +

>  In particular, for immutable sets, the documentation says: "Elements that already exist in the immutable hash set will not be added." Should updated be consistent with + or treat keys and values differently?

I think that we will have to do this. This is not a statement for collections, just for sets, and refers to the == equallity of the parameter. If we were to do this then that would imply that that we would use == for the (K,V) and thus == for the value to be inserted in the. This would be different to all of the semantics of the maps that I have looked at (it was actually the bug that I was chasing in other code that led me into all of this inconsistency) 

My General concern with + is that 

1. for Map1-4, HashMap (HashMap1, HashTrieMap, HashMapCollision1) it should be consistent, as I get these from the same builder depending on data size and values
1. implementation should not be overly memory hungry

**Comment by szeiger** [comment]
I had another look at the 2.12 collections and the new design. Here are some notable scaladoc comments from 2.12 which either mention update semantics or should mention them but don't:

- `Setlike.+`
  > Creates a new set with an additional element, unless the element is already present.

- `SetLike.union`
  > a new set consisting of all elements that are in this set or in the given set

- `SetLike.diff`
  > a set containing those elements of this set that are not also contained in the given set

- `MapLike.updated` & `immutableMap.updated`
  > A new map with the new binding added to this map

- `MapLike.+`
  > Adds a key/value pair to this map, returning a new map.

- `mutable.Map.+=`
  > Adds a new key/value pair to this map. If the map already contains a mapping for the key, it will be overridden by the new value.

- `mutable.SetLike.+=`
  > Adds a single element to the set.

We have the following basic methods in the API for the new design:

- `IterableOps.concat` (aka `++`) applies to all collections
- `SetOps.+` and `MapOps.+` are deprecated on generic sets and maps
- `immutable.SetOps.incl` (aka `+`) adds an element
- `mutable.SetOps.addOne` (aka `+=` aka `add`) via `mutable.Growable`
- `mutable.MapOps.addOne` (aka `+=`) via `mutable.Growable` with tupled key and value
- `mutable.MapOps.update` and `mutable.MapOps.put` with separate key and value parameters

I suggest these rules:

- Unless explicitly noted otherwise, containment and equality for key elements (i.e. set elements and map keys) refers to the `equals` / `hashCode` contract.
- Immutable updates of mutable collections *must* always return a unique copy without structural sharing, even when the collection is unchanged or the result is empty.
- Immutable updates of immutable collections *should* use structural sharing and avoid copying.
- Key element identities already in the source collection (i.e. the receiver of a method call) *must* always be preferred over new key elements which are equal but have different identities
- Map values *must* always be updated (i.e. the new value wins over an existing value)
- In immutable maps structural sharing *must not* be done for non-identical values; equality of map values is irrelevant.

**Comment by mkeskells** [comment]
I would propose this clarifications
Map values must always be updated **if they have a different identity** (i.e. the new value wins over an existing value)
An update to a map with a key and value that are identical should not cause an update (this reduces memory churn)

**Comment by Ichoran** [comment]
@mkeskells - I think Stefan's proposed a very reasonable set of rules.

Unfortunately we can't guarantee that the value is the "same" in all important ways unless we use reference identity (which probably won't help memory churn), but sure, a reference identity check wouldn't cost much (probably).  The principle of least surprise is that if you put something new in a map, it is there.  Since our API doesn't return keys on either sets or maps by default, it's only the value for which this should be true.

One could envision methods that did only change the key if it was different according to equality, e.g. with a default implementation of

```
def updatedIf[K, V1 >: V](key: K, value: V1)(p: (V, V1) => Boolean) =
  get(key) match {
    case None => updated(key, value)
    case Some(v) =>
      if (p(v, v1)) updated(key, value)
      else this
  }
```

And one could also envision a method that always replaces the key, e.g. equivalent to

```
def rekey[K, V1 >: V](key: K, value: V1) = (this - key).updated(key, value)
```

but implemented more efficiently in the particular map types.

**Comment by mkeskells** [comment]
@Ichoran You have read identity and assumed I meant equality. 

I was referring to identity aka reference equallity (i.e eq) only, and it **would** reduce memory churn and improve structural sharing.
That was **precisely** why I request this.

```
val a = "a"
val b = "b"
val x = Map(a-> b)
```
why should not 
```x eq x + (a -> b)```

There is no observable difference (other that the above) to the application if identical values are retained in the map without alteration

IMHO There is a debate to be had on insertion ordered maps, what count as insertion (whether it is the first/last insertion, whether a change of value is an insertion etc, but these issues are secondary to the fundamental rules), and I am less concerned with the outcome, only that it is defined

BTW the API does (and always has) returned keys, and the behavior of the keys must be defined in an unambiguous manner. Note this is not currently the case as you can see in my original post

**Comment by Ichoran** [comment]
@mkeskells - Yeah, no point rebuilding if they're referentially identical.  That's a good addition to the rules Stefan listed.

But the API does not return the key.  `m.get(k)` returns only the value; `m(k)` only returns the value; etc..  You can _traverse_ the keys along with the values, but that's not the same as looking them up.  Thus, _which_ key happens to be stored is, by API design, mostly irrelevant.  We should have a standard policy and follow it--I absolutely agree--but what it is would be different if the normal usage was `val (k, v) = m.entry(k2)`.

**Comment by mkeskells** [comment]
@Ichoran  I agree the most important point is to have a consistent set of rules, recommendations etc. I also think that the I would say that traversal is part of the (very broad) Map API though. `myMap.head._1` seems like part of the API to me, but I don't want to get hung up on the semantic boundaries.
 
Traversal of maps occurs very frequently IMHO

The rule chosen WRT to the original key then this has impact on `+`, `++` and others
As I see it, `+`, `++`, and `updated` retain the same semantics WRT key and value handling

**Functionality**
Following evaluating `myMap + (a->b)` - I would expect a mapping from "a to b", not a mapping of "either a or something that == a to b depending on the content of myMap". To quote your earlier comment "_The principle of least surprise is that if you put something new in a map, it is there_". I would extend that to "_The principle of least surprise is that if you put some mapping a map, it is there_"

IMO it is surprising if the rule were to be that original key would be retained as traversal could provide a mapping that was never present (old key and new value)

Retaining the old key retains memory. Imagine that I have a map where a key instance is the only reference blocking GC of some memory. It would be surprising if replacing the mapping could not easily free the memory, and I had to remove all of the keys and reassemble

**Non functionals**
Part of the stated aims of HAMP and CHAMP maps is structural sharing. Currently there is very little sharing (I was working on some for the 2.12 Maps, but have killed this before PR as the collections is reworked) and it would be sensible to promote rules that encourage, or at least allow more structural sharing

If we choose a rule that retains the existing key then a ++ operation will have less possibility for structural sharing when the key is `==` but not `eq` and the value is updated. 

So - which key is retained affects non-functional issues, but Sets and Map are really widely used

- Smaller data may run faster (normal caching & memory issues)
- A production system may have many Gb of Maps, Sets etc
- Production systems may run a grid of hundreds or thousands of machines
- They communicate with generalised structures (including maps and sets), and (some) communications API understand and optimise graphs (e.g. Java Serialisation) .

The non-functional decisions have real bearing on applications in the real world. API designers have to consider the full stack consequences of a decision that they are making, both functionally and non-functionally

**Comment by szeiger** [comment]
I have slightly updated the rules and written a comprehensive test for them (except # 3 which cannot be tested directly):

> 1. Unless explicitly noted otherwise, containment and equality for key elements (i.e. set elements and map keys) refers to the `equals` / `hashCode` contract.
> 2. Immutable updates of mutable collections *must* always return a unique copy without observable structural sharing, even when the collection is unchanged or the result is empty.
> 3. Immutable updates of immutable collections *should* use structural sharing and avoid copying.
> 4. When updating a collection (immutably or in place), key element identities already in the source collection (i.e. the receiver of a method call) *must* always be preferred over new key elements which are equal but have different identities.
> 5. When transforming a collection (immutably or in place) into a new collection (e.g. `map`, `flatMap`, `collect`), only the transformation results are used. Existing key elements *must not* be preserved.
> 6. Map values *must* always be updated (i.e. a new value wins over an existing value with a different identity)
> 7. In immutable maps structural sharing *must not* be done for non-identical values; equality of map values is irrelevant.

Compared to the original version I have clarified that map values only need to be updated when they have a different identity in # 6 (which doesn't really change anything as an update to an identical object is meaningless and cannot be observed), split up the rule on key identities into # 4 and # 5 (because it only applies to updates whereas the behavior of transformation should be the opposite) and added the restriction to *observable* sharing in # 2 (so we don't rule out copy-on-write).

All standard operations on all standard `Map` and `Set` implementations pass all of the tests except the ones for # 4 (preserving key identities). The results for that one nicely reflect the discussion in this ticket. You can argue that adding an existing item to a set shouldn't change anything (and treat maps the same way by extension) or that always updating is necessary to push old keys out where needed. Or you can simply not care and leave it as an implementation detail.

These collections currently preserve key identities in updates:
- mutable.SeqMap
- mutable.LinkedHashMap
- mutable.LinkedHashSet
- mutable.TreeMap
- mutable.TreeSet
- mutable.OpenHashMap
- mutable.HashMap
- mutable.HashSet
- mutable.Map (small sizes and HashMap)
- mutable.Set (small sizes and HashSet)
- immutable.VectorMap
- immutable.TreeSet
- immutable.ListSet
- immutable.Map for sizes <= 4
- immutable.Set for sizes <= 4
- java.util.HashMap (via wrapper)
- java.util.HashSet (via wrapper)

And these don't:
- mutable.ListMap
- mutable.AnyRefMap
- concurrent.TrieMap
- immutable.TreeMap
- immutable.ListMap
- immutable.HashMap

If we want to be consistent internally and also with the Java collections (which could not be easily fixed in a wrapper without sacrificing performance) we should preserve key identities.

**Comment by szeiger** [comment]
I should mention that for all of the maps that don't preserve key identities this is the case even when the values are identical (such that a set implemented by a map with null or Unit values would also fail the test) but at least the set implementations agree that an existing set element should always win over a new one.
