### ISSUE TITLE
annotation argument needs to be a constant; found: Bar.constant

### ISSUE THREAD

**Issue by spockz** [scala/bug#10426]
When generating scaladoc for the trait below scaladoc will choke on the constant. `sbt compile` works just fine. [Stackoverflow](https://stackoverflow.com/a/20038139/682376) suggests setting `canAdaptConstantTypeToLiteral` to `true`. 

Regardless, the scaladoc compiler should probably use the same settings as the normal compiler.

```scala
import javax.annotation.Priority
import javax.ws.rs.Priorities

@Priority(Bar.constant)
trait A {
  def x(): String
}

object Bar {
  final val constant = Priorities.USER + 42
}
```

**Comment by jvican** [comment]
Hey @spockz, thanks for filing this issue.
  
So the thing here is, it's unclear whether this option has to be `false` for Scaladoc. Does anyone in the Scala team know why this is the case?
  
If no one thinks this is a bad idea, I think the best way to move this forward is trying to flip the boolean at hand for scaladocs and see what it breaks. If nothing breaks, the option can be configured via a compiler scaladoc setting or whichever method is used to configure scaladoc. When this is done, we can make this option configurable from sbt so that this error doesn't happen again.

**Comment by lrytz** [comment]
Maybe Scaladoc wants to retain the original trees for printing default arguments.

```scala
trait T {
  def x(i: Int = Bar.constant): Unit
}
object Bar {
  final val constant = Integer.MAX_VALUE + 42
}
```

gives

![image](https://user-images.githubusercontent.com/119636/28563715-15e3e5c2-7127-11e7-890a-b548fed58f22.png)

**Comment by lrytz** [comment]
If it's just about that, we could achieve the same effect by adding an `OriginalTree` attachment added to the `Literal` https://github.com/scala/scala/blob/v2.12.2/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L998

**Comment by spockz** [comment]
How can we proceed on this? If this would be fixed would it require a release of 2.11 in order to be able to generate docs in 2.11 or can we use the same scaladoc when cross compiling?

**Comment by jvican** [comment]
2.11.x is EOL'ed, so that can't happen @spockz. This could happen in the next 2.12.x release if I'm not mistaken.
  
> If it's just about that, we could achieve the same effect by adding an OriginalTree attachment added to the Literal https://github.com/scala/scala/blob/v2.12.2/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L998
  
BTW, this fix would help me get Zinc working for final constants (which would be enormous). If you confirm me this attachment is ok @lrytz, I'm more than happy to submit a PR with that fix. I proposed a more ambitious approach to this problem, but that didn't seem to work out: https://github.com/scala/scala-dev/issues/340.

**Comment by hrhino** [comment]
There's now an `OriginalTreeAttachment` which should allow threading of the needle here.

**Comment by som-snytt** [comment]
I thought typelevel constant folding was going to be the solution.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/9532

**Comment by qingwei91** [comment]
Hi, may I know if this is fixed? 

I am bumping into this issue on scala 2.12.10

**Comment by som-snytt** [comment]
Looks like the linked ticket was 2.13.
