### ISSUE TITLE
Eta expansion binds var fields by value

### ISSUE THREAD

**Issue by gzm0** [scala/bug#10452]
Consider the following example:

```scala
object Test {
  class A {
    def f(x: String) = println("hello " + x)
  }

  var x: A = null
  val f0: String => Unit = m => x.f(m)
  val f1: String => Unit = x.f _

  def main(args: Array[String]) = {
    x = new A
    f0("world")  // prints "hello world"
    f1("world")  // throws NPE
  }
}
```

This is in violation of the [first example of eta expansion in the specification][1] that says that `x.f _` is equivalent to `m => x.f(m)`.

It happens across the board in 2.10.6, 2.11.11, 2.12.2, 2.13.0-M2.

[1]: https://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#method-values

**Comment by som-snytt** [comment]
This is covered in 6.26.5. `math.random.toString _` is not `() => math.random.toString()`.

It could clarify that stable but side-effecting expressions preserve the lazy side-effect:

```
scala> object X { println("X") ; def f(i: Int) = i + 1 }
defined object X

scala> val g = X.f _
g: Int => Int = $$Lambda$1017/995482901@f3560d4

scala> g(42)
X
res0: Int = 43

scala> lazy val v = new Runnable { println("v") ; def run() = println("ran") }
v: Runnable = <lazy>

scala> val g = v.run _
g: () => Unit = $$Lambda$1067/1844381234@49038f97

scala> g()
v
ran
```
I was surprised by the lazy val.

**Comment by gzm0** [comment]
I do not fully understand 6.26.5. Notably it is unclear to me what a "maximal sub-expression" is.

The way I understand it, it would translate `x.f _` in the first example to:

```scala
{
val x1 = x
(y1: String) => x1.f(y1)
}
```

or, alternatively, if `x` is not considered a "maximal sub-expression" to

```scala
{
(y1: String) => x.f(y1)
}
```

Both of which will not throw an NPE.

I do not understand how 6.25.5 relates to the `toString` example. Also, I think your two lazy examples are fully within spec (although it seems to more relate to the spec of closures in general than eta expansion specifically).

**Comment by gzm0** [comment]
Actually, the first expansion (with `x1`) will NPE. So his might actually be correct.

Leaving this open for others to comment. Maybe we can clarify this in the spec?

**Comment by som-snytt** [comment]
I'll just clarify that I half-expected the lazy val example to work as you showed:
```
{ val v1 = v ; () => v1.run() }
```
for the reason that
```
def f(x: => Int)(y: Int) = y
f { println("x") ; 42 } _
```
prints in 2.9 but not 2.10. That is, "evaluate maximal subexpressions" used to mean evaluate by-name parameters, even when the parameter is not "named" (there is no request to evaluate x).

Because of the overhead of lazy vals, it's actually useful to fetch the value only once for many invocations of the result function. If I write `v.run _`, I might reasonably expect `v` is evaluated eagerly.

Similarly, `math.random` is evaluated eagerly in `math.random.toString _`. The result function prints the same value for every invocation. I'd expect the same behavior if `random` were a var.

**Comment by som-snytt** [comment]
The examples in 6.7 show, e.g., `Some(1)` is evaluated first. But it's confusing that https://github.com/scala/bug/issues/11465
