### ISSUE TITLE
The compiler fails to find implicit parameter if there's a definition with same name in scope

### ISSUE THREAD

**Issue by loskutov** [scala/bug#10465]
If I try to compile the following piece of code:
```
object A {
  val seqDerivedOrdering = 42

  import Ordering.Implicits._

  Seq(Seq(1)).sorted
}
```
the compiler complains:
```
A.scala:6: error: No implicit Ordering defined for Seq[Int].
  Seq(Seq(1)).sorted
              ^
one error found
```
I've tried several `scalac` versions from 2.10.6 to 2.13.0-M1 and all of them behave this way. However, if I rename the `val` or remove it, the code does compile, as expected.

**Comment by jvican** [comment]
Oh wow, this is a good one. Thanks for reporting.

**Comment by som-snytt** [comment]
This is just how it works. Your implicit value has to "available by simple name". Make it "accessible without a prefix." http://www.scala-lang.org/files/archive/spec/2.12/07-implicits.html

Note that your local value trumps an import. http://www.scala-lang.org/files/archive/spec/2.12/02-identifiers-names-and-scopes.html

```
scala> Seq(Seq(3,2,1)).sorted
<console>:12: error: No implicit Ordering defined for Seq[Int].
       Seq(Seq(3,2,1)).sorted
                       ^

scala> locally { import Ordering.Implicits._ ; Seq(Seq(3,2,1)).sorted }
res1: Seq[Seq[Int]] = List(List(3, 2, 1))

scala> locally { val seqDerivedOrdering = 42 ; import Ordering.Implicits._ ; Seq(Seq(3,2,1)).sorted }
<console>:12: error: No implicit Ordering defined for Seq[Int].
       locally { val seqDerivedOrdering = 42 ; import Ordering.Implicits._ ; Seq(Seq(3,2,1)).sorted }
                                                                                             ^

scala> locally { val seqDerivedOrdering = 42 ; import Ordering.Implicits._ ; seqDerivedOrdering }
res3: Int = 42

scala> object X { implicit val x: String = "hi" }
defined object X

scala> locally { implicitly[String] }
<console>:12: error: could not find implicit value for parameter e: String
       locally { implicitly[String] }
                           ^

scala> locally { import X._ ; implicitly[String] }
res5: String = hi

scala> locally { val x = 0 ; import X._ ; implicitly[String] }
<console>:13: error: could not find implicit value for parameter e: String
       locally { val x = 0 ; import X._ ; implicitly[String] }
                                                    ^

scala> locally { val x = 0 ; import X._ ; x }
res7: Int = 0
```

**Comment by ritschwumm** [comment]
i guess after getting bitten by this a few times you get used to the pain :/

**Comment by som-snytt** [comment]
They call it the "import tax."

**Comment by loskutov** [comment]
Doesn't it make sense to warn about shadowing then?

**Comment by som-snytt** [comment]
For some reason, no one has asked for a warning about this flavor of shadowing, but https://github.com/scala/bug/issues/4762. I assume a linter would have to do it.

This one is more fun, https://github.com/scala/bug/issues/9208.

**Comment by jvican** [comment]
I'm sorry, I don't get it... Citing the spec:

> The actual arguments that are eligible to be passed to an implicit parameter of type T fall into two categories. First, eligible are all identifiers x that can be accessed at the point of the method call without a prefix and that denote an implicit definition or an implicit parameter.
  
Here, the first condition is met `val seqDerivedOrdering` is indeed accessible from the call-site of the implicit search. But the second condition, namely "and that denote an *implicit* definition or an *implicit* parameter", is not met because `val seqDerivedOrdering` is *not* an implicit, right? Otherwise it would need to be defined with `implicit val seqDerivedOrdering`.
  
Am I missing something?

**Comment by sjrd** [comment]
Yup, you're interpreting the requirement of being implicit on the wrong thing.

The one that will be *selected* must be both:
* accessible without prefix
* implicit

Note that it can be inaccessible due to another definition. Whether that other definition itself is implicit or not is irrelevant.

**Comment by jvican** [comment]
Aha, I see! Thanks for the explanation. This leads me to the question -- why does it need to be accessible without a prefix? Wouldn't it be better to reword this rule as "it has to be accessible via a stable path" so that this case in handled?

**Comment by som-snytt** [comment]
The rule is useful for disabling specific implicits in lexical scope.

I remember [the example in specs2](https://github.com/etorreborre/specs2/blob/SPECS2-3.9.4/common/src/main/scala/org/specs2/control/LanguageFeatures.scala).

No one has proposed rewriting the spec in Yoda's dialect:

> Eligible are all x that can be accessed without a prefix. Implicit must they be.

An appealing feature of anonymous implicits (`implicit val _: X = new X`) is that they would be immune to shadowing.

**Comment by jvican** [comment]
> The rule is useful for disabling specific implicits in lexical scope.
  
I fail to see how the example you link would fail with the amendment I'm proposing to implicits... Is there a place where this rule was discussed in the past so that I can have a read? I'm really surprised by this behaviour... unless there is a very good reason why this is the case, I think that the linked code at the beginning of the issue should compile.

**Comment by Blaisorblade** [comment]
Searching "implicit shadowing" brings to light one bug where the compiler was fixed to have this behavior.
https://github.com/scala/bug/issues/4270

> From what I understand from reading the SLS, implicits are only applicable if they can be accessed on the current scope without any prefix. Shadowing should prevent them from being used in the current scope, however it appears that only implicits can shadow implicits.

**Comment by Blaisorblade** [comment]
OTOH, @odersky once wrote a `conforms` method got confused (#7788). I quote:

> The problem is that Predef.conforms is shadowed by the local conforms. It took me a while to figure out what happened.

> IMO this is a trap waiting to happen for everyone. We should avoid it by finding a less conspicuous name for the conversion. Ideally with a dollar in it.

I agree up to "trap waiting to happen for everyone". As @jvican points out, the language feature (though the correct reading of the SLS) is itself a trap, since you almost never need to think about implicit names. The other exception is when you need to import an implicit explicitly.

> Wouldn't it be better to reword this rule as "it has to be accessible via a stable path" so that this case in handled?

We discussed this, and @jvican clarified he'd like to allow doing *one* field-lookup from accessible values. So if `Foo` is in scope, implicit members `Foo.v` for all `v` should be in the implicit scope. Of course, this risks being a massively breaking change. But Scala already has some similar (but more complex) rules—right now, when `Foo` is in scope then all implicit members `Foo.v` of type `Foo[...]` are in the implicit scope for `Foo`.

**Comment by som-snytt** [comment]
Sounds like a topic for the forum.

Another trick is to name implicits more confoundingly with back-quoted identifiers.
```
val `some implicit you cannot shadow easily`: A = ???
```
I think the intuition for the first rule is that since implicit `x` is in scope, normally I'd write `f(x)`. If the parameter list is implicit, I can omit writing it. Normal scoping applies.

Implicit scope is the second rule. I didn't understand that last sentence, "when `Foo` is in scope...". Implicit scope depends on the type of the required implicit.

The other proposal for anonymous implicits is a syntax `import implicit Foo._` which could mean basically import with rename such that implicits can't be shadowed.

**Comment by odersky** [comment]
> Sounds like a topic for the forum.

I think so, too.

**Comment by Blaisorblade** [comment]
Agreed on the forum.

> Implicit scope is the second rule. I didn't understand that last sentence, "when Foo is in scope...". Implicit scope depends on the type of the required implicit.

For the record: IIUC @jvican proposed to use `Foo` members even when searching for `Bar[Int]` not just for `Foo[Int]`—and I find this very different but interesting (though I'm not sure how compatible it is). A proper case will wait for the forum thread.
