### ISSUE TITLE
Scaladoc incorrectly treats dots not followed by whitespace as end-of-sentence

### ISSUE THREAD

**Issue by sjrd** [scala/bug#10491]
For example:
```scala
/** The Scala.js linker. */
```
renders as
> The Scala.

instead of
> The Scala.js linker.

Similarly,
```scala
/** The set of .scala files. */
```
renders as
> The set of .

instead of
> The set of .scala files.

As you can imagine, this issue pollutes a lot of the documentation of Scala.js.

This can be fixed with an easy rule: only dots directly followed by whitespace (including newline) should be considered as end-of-sentence.

Related: #8839

**Comment by Philippus** [comment]
Where do you see this rendering?

**Comment by sjrd** [comment]
Here, for example: https://www.scala-js.org/api/sbt-scalajs/0.6.20/#org.scalajs.sbtplugin.ScalaJSPlugin$$AutoImport$ (see the members `scalaJSLinker` and `scalajsp` for characteristic issues)

**Comment by sjrd** [comment]
Funny thing, this was apparently already [fixed a long time ago](https://github.com/scala/scala/pull/3824), but the problem has obviously reappeared.

Maybe a good-first-issue, assuming we can take inspiration from that old PR to find the correct code spot to fix?

**Comment by adri242** [comment]
Seems this is already fixed having a look at the previous example commented above: https://www.scala-js.org/api/sbt-scalajs/0.6.20/#org.scalajs.sbtplugin.ScalaJSPlugin$$AutoImport$ (see the members scalaJSLinker and scalajsp for characteristic issues)

**Comment by SethTisue** [comment]
Those docs were generated by an old Scala version, Scaladoc has been overhauled since then.

Let's see how 2.13.0-M5 does. At e.g. https://www.scala-lang.org/files/archive/api/2.13.0-M5/scala/Predef$.html we see:

![screen shot 2018-10-09 at 10 17 10 am](https://user-images.githubusercontent.com/161079/46686274-a356fa80-cbac-11e8-981e-13cd24b9957b.png)

this was generated from a doc comment beginning `  /** We prefer the java.lang.* boxed types to these wrappers in`

whereas at https://www.scala-lang.org/files/archive/api/2.11.0/#scala.Predef$ we see

![screen shot 2018-10-09 at 10 20 01 am](https://user-images.githubusercontent.com/161079/46686359-e6b16900-cbac-11e8-99ec-608ce9689228.png)

which shows the bug which existed in 2.11.0.
