### ISSUE TITLE
Case class generated equals throws ClassCastException

### ISSUE THREAD

**Issue by Jasper-M** [scala/bug#10539]
Continued from #10536.
This code throws a `ClassCastException: java.lang.String cannot be cast to java.lang.Boolean`:
```
class A { def ==(a: A) = "lol" }
case class B(a: A)
B(new A) == B(new A)
```

This code however doesn't compile, with the error `value && is not a member of String`:
```
case class B(a: A) { 
  override def equals(any: Any) = this.eq(any.asInstanceOf[Object]) || ((any match { 
    case _: B => true
    case _ => false
  }) && {val that = any.asInstanceOf[B]; (this.a == that.a) && that.canEqual(this)})
}
```

Somehow the synthetic code passes typechecking but then wrongly receives an `unboxToBoolean` call.

**Comment by som-snytt** [comment]
The spec just says equals "with respect to equals". But since the case equals is specified as `(Any)Boolean`, we are probably to assume the same for structural equality.

Or maybe not. But if structural equality is name-based, it would have to specify `equals` or `==`.

The implementation used to be based on `match`, before a round of optimization, where universal equality is intended:

```
scala> class C { def equals(c: C) = false }
defined class C

scala> val c = new C
c: C = C@5584d9c6

scala> c.equals(c)
res0: Boolean = false

scala> case class D(c: C)
defined class D

scala> D(c) match { case D(`c`) => }
        ^
       warning: match may not be exhaustive.
       It would fail on the following input: D((x: C forSome x not in c))
```
