### ISSUE TITLE
Java method with boxed/unboxed overloads causes ambiguity error if more than one boxed argument

### ISSUE THREAD

**Issue by aandr** [scala/bug#10532]
Tested on 2.12.2 and 2.12.3.

Constructing the following Java class:
```java
public class A {
  public A(long x, Long y) {}
  public A(Long x, Long y) {}
}
```
causes an ambiguous reference to overloaded definition error:

```scala
scala> new A(1,1)
<console>:12: error: ambiguous reference to overloaded definition,
both constructor A in class A of type (x$1: Long, x$2: Long)A
and  constructor A in class A of type (x$1: Long, x$2: Long)A
match argument types (Int,Int)
       new A(1,1)
       ^

scala> new A(1L,1L)
<console>:12: error: ambiguous reference to overloaded definition,
both constructor A in class A of type (x$1: Long, x$2: Long)A
and  constructor A in class A of type (x$1: Long, x$2: Long)A
match argument types (Long,Long)
       new A(1L,1L)
       ^
```

This is suspicious, because it works fine in the following situations: 

```java
public class B { // only one unboxed type
  public B(long x, String y) {}
  public B(Long x, String y) {}
}

public class C { // only one argument
  public C(long x) {}
  public C(Long x) {}
}
```

A temporary workaround is:

```scala
new A(java.lang.Long.valueOf(1), java.lang.Long.valueOf(2))
```

**Comment by SethTisue** [comment]
Seems fixed as of 2.13.0. 

However, it's _not_ fixed in Scala 3 🙀

If anyone cares, please open a ticket (or look for an existing one) over at https://github.com/scala/scala3

```
% scala-cli repl -S 3.nightly .
Downloading Scala 3.5.0-RC1-bin-20240429-e2c456f-NIGHTLY compiler
...
scala> new A(1L,1L)
-- [E051] Reference Error: -----------------------------------------------------
1 |new A(1L,1L)
  |    ^
  |Ambiguous overload. The overloaded alternatives of constructor A in class A with types
  | (x$0: Long, x$1: Long): A
  | (x$0: Long, x$1: Long): A
  |both match arguments ((1L : Long), (1L : Long))
  |
  | longer explanation available when compiling with `-explain`
1 error found
```

**Comment by lrytz** [comment]
Hope GitHub Copilot Workspace will be able to handle "Submit a regression test for scala/bug#10532" soon!

**Comment by lrytz** [comment]
Just now in my inbox 😄

<img width="1076" alt="image" src="https://github.com/scala/bug/assets/119636/6a2e0024-8928-41cc-a607-2a589fa976de">

**Comment by som-snytt** [comment]
Fixed by https://github.com/scala/scala/pull/7680

**Comment by som-snytt** [comment]
Fixed by `OverloadedArgProto` in https://github.com/scala/scala/commit/54714cd3392c0256e685503aa3684d85b49df728 where using an expected type for the argument improves applicability during overload resolution.

(Implicits are not enabled during overload resolution, which hurts applicability; they seem to be enabled for `typedArg` where the improved pt is the boxed type and the type of the arg is the boxed type. Previously, the arg type was a primitive (int or long), so the method taking boxed Long was not applicable.)

The "suspicious" examples in OP are just examples where the alternative with no boxed parameter types is chosen.
