### ISSUE TITLE
fsc : Invalid argument or cannot assign requested address

### ISSUE THREAD

**Issue by joel-f** [scala/bug#10602]
Hello,

I get the following issue on Linux when I type fsc -verbose :

java.net.SocketException: Invalid argument or cannot assign requested address

It does it when my hostname is a numeric hostname.

But if I change to regular characters fsc works fine.

I have had a numeric hostname for years and never experienced anything like that with any program. It seems that it is valid according to RFC 1123.

Is it something related to scala or Java ?

Thanks for the good work, so far I enjoy Scala.

**Comment by oowekyala** [comment]
I think the problem is in Java libraries. It seems `java.net.InetAddress.getLocalHost()` interprets the host name as the address itself when it's all numeric, e.g. with a hostname of `123`, the returned address will be `0.0.0.123`. You can easily check that with jshell.

I checked on the Oracle bug database and that bug isn't yet reported, so you could try [creating a bug report](http://bugreport.java.com/).

**Comment by joel-f** [comment]
Thanks for the answer.

I could reproduce this issue with java and jshell by changing the hostname and using :
new java.net.Socket(java.net.InetAddress.getLocalHost(), 8080);

I reported it to Oracle as you suggested.

**Comment by som-snytt** [comment]
It's as documented, and is arguably a feature?

**Comment by joel-f** [comment]
I think it's not really common to set such a hostname and this thread is now findable on the most popular search engines if it happens to someone else.

For me it appears to be a Java issue. I'll publish here the answer from Oracle when I get one, so that you can react accordingly.

**Comment by joel-f** [comment]
The report has been evaluated by Oracle and assigned a Bug ID : http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8191991
