### ISSUE TITLE
Shouldn't return a failed Future when the Executor throws a RejectedExecutionException?

### ISSUE THREAD

**Issue by gabrielgiussi** [scala/bug#10616]
It was surprising to me that the apply method of `Future` could throw an exception if the underlying `Executor` doesn't accept a task for execution, this means throwing a RejectedExecutionException if, for example, the queue is bounded and is filled.
Due to the fact that the apply is simply a call to map over a Successful KeptPromise, both `map` and `flatMap` could also throw an exception.
```scala
object Scenario1 extends App {
  val ex = new ThreadPoolExecutor(1, 1, 0L, TimeUnit.MILLISECONDS, new ArrayBlockingQueue(1))
  implicit val ec = ExecutionContext.fromExecutor(ex)

  val f = Future { Thread.sleep(1000); 1 }
  val f2 = Future { 1 }
  val f3 = Future { 1 } // throws RejectedExecutionException

  sys.addShutdownHook {
    ex.shutdown()
  }
}
```

This is the stacktrace
```scala
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@4667ae56 rejected from java.util.concurrent.ThreadPoolExecutor@77cd7a0[Running, pool size = 1, active threads = 1, queued tasks = 1, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:20)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
	at scala.concurrent.impl.Promise.transform(Promise.scala:29)
	at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
	at scala.concurrent.Future.map(Future.scala:287)
	at scala.concurrent.Future.map$(Future.scala:287)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
	at scala.concurrent.Future$.apply(Future.scala:653)
	at futures.Scenario1$.delayedEndpoint$futures$Scenario1$1(PlayingWithFutures.scala:101)
	at futures.Scenario1$delayedInit$body.apply(PlayingWithFutures.scala:95)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at futures.Scenario1$.main(PlayingWithFutures.scala:95)
	at futures.Scenario1.main(PlayingWithFutures.scala)
```

If the Future isn't completed, a `map` doesn't try to send the task to the executor until it's completed. When the `onComplete` callback is executed, then it sends the task to the executor in `CallbackRunnable#executeWithValue`.
```scala
object Scenario2 extends App {

  val ex = new ThreadPoolExecutor(1, 1, 0L, TimeUnit.MILLISECONDS, new ArrayBlockingQueue(1))
  implicit val ec = ExecutionContext.fromExecutor(ex)

  val f = Future { Thread.sleep(10000); 1 }.map(_ + 1)
  val f2 = Future { 100 }

  sys.addShutdownHook {
    ex.shutdown()
  }

}
```
The stacktrace is slightly different
```scala
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@1df38c1f rejected from java.util.concurrent.ThreadPoolExecutor@58f101c5[Running, pool size = 1, active threads = 1, queued tasks = 1, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:20)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.complete(Promise.scala:49)
	at scala.concurrent.Promise.complete$(Promise.scala:48)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I think it should return a failed Future instead of throwing an exception, mainly because of scenario 2 because the exception is happening in the thread of the thread pool and we can't catch it.
However, I expected that a simple try-catch "fix" the Scenario1 because the exception is being trowed in the main thread, but it didn't. Could someone explain this?
```scala
Neither of these options catched the exception
val f3 = try { Future { 1 } } catch { case e:RejectedExecutionException => Future.failed(e)}
val f3 = Try { Future { 1 } }.recover { case e:RejectedExecutionException => Future.failed(e)}
```
Also, I just realized that the `CallbackRunnable#executeWithValue` already does a try-catch

I'm adding this issue with the consent of @axel22 
I hope I was clear.
 
**Update:**
I just figured out why the exception wasn't being catched, it's because is already catched by the `CallbackRunnable` in `CallbackRunnable#executeWithValue` who handles the exception calling the `ExecutionContext#reportFailure` and the `ExecutionContextImpl` implementation pass it in turn to its reporter wich by default just print the stacktrace.

So, the default implementation is silently swallowing the exception and the Future **never completes**.

This worked 
```scala
object Scenario1Fix extends App {
  val ex = new ThreadPoolExecutor(1, 1, 0L, TimeUnit.MILLISECONDS, new ArrayBlockingQueue(1))
  implicit val ec = ExecutionContext.fromExecutor(ex, t => throw t) // re-throw the exception

  val f = Future { Thread.sleep(1000); 1 }
  val f2 = Future { 1 }
  val f3 = try { Future { 1 } } catch { case e:RejectedExecutionException => Future.failed(e)}

  sys.addShutdownHook {
    ex.shutdown()
  }
}
```
Because the CallbackRunnable is already catching the exception throwed by the executor, I think the solution could be 
```scala
  def executeWithValue(v: Try[T]): Unit = {
    require(value eq null) // can't complete it twice
    value = v
    // Note that we cannot prepare the ExecutionContext at this point, since we might
    // already be running on a different thread!
    try executor.execute(this) catch { case NonFatal(t) =>
      value = Failure(t) // updating the value with the exception
      onComplete(value) // calling the callbacks with the Failure, e.g. Failure(RejectedExecutionException)
      executor reportFailure t }
  }
```

**Comment by gabrielgiussi** [comment]
Calling `onComplete` outside the executor could be dangerous because the callbacks will being executed where not intended to be. 
I guess this requires more analysis.
Maybe rethrowing the exception in the CallbackRunnable and do a try catch in `Promise#transform` but this will only solve the Scenario1.

**Comment by gabrielgiussi** [comment]
What about using an inner ExecutionContext with an unbounded queue to execute callbacks where the value is `Failure[RejectedExecutionException]`.
You could say "Why don't use an unbounded queue in the beginning?", the difference is that the ExecutionContext should be configurable by the user, while these inner ExecutionContext shouldn't.

**Comment by viktorklang** [comment]
@gabrielgiussi There's no clean solution to this issue in the current encoding of Future in the standard library as all we know at that point is that there's an onComplete effect that we wanted to execute but we couldn't.

With the new encoding, which I will propose for the next Scala version we can most probably solve this issue: https://github.com/viktorklang/scala-futures/blob/wip-optimizations-%E2%88%9A/src/main/scala/scala/future/impl/Promise.scala#L383

Since we now can know that a callback is an XformPromise, we can `tryFailure` it with the `RejectedExecutionException` and let the failure propagate along that path instead.

**Comment by viktorklang** [comment]
In the new encoding, the fix is just a few lines of code.

After patch:
~~~scala
scala> import scala.future._
import scala.future._

scala> val f = Future.successful(1)
f: scala.future.Future[Int] = Future(Success(1))

scala> val throwingEC = scala.concurrent.ExecutionContext.fromExecutor((r: Runnable) => throw new java.util.concurrent.RejectedExecutionException())
throwingEC: scala.concurrent.ExecutionContextExecutor = scala.concurrent.impl.ExecutionContextImpl@2168c4f3

scala> f.map(_.toString)(scala.concurrent.ExecutionContext.global)
res0: scala.future.Future[String] = Future(Success(1))

scala> f.map(_.toString)(throwingEC)
res1: scala.future.Future[String] = Future(Failure(java.util.concurrent.RejectedExecutionException))
~~~

~~~diff
@@ -314,11 +314,15 @@ private[future] final object Promise {
       if (a.isInstanceOf[ExecutionContext]) {
         val executor = a.asInstanceOf[ExecutionContext]
         _arg = requireNonNull(v)
-        try executor.execute(this) catch { case NonFatal(t) => executor.reportFailure(t) }
+        try executor.execute(this) catch { case NonFatal(t) => onSubmitFailed(executor, t) }
       }
       this
     }

+    private[this] final def onSubmitFailed(ec: ExecutionContext, failure: Throwable): Unit =
+      if (!this.tryFailure(failure)) // If we can't propagate, then report
+        ec.reportFailure(failure)
+
~~~

**Comment by sahilahmadlone** [comment]
I think The fix should not be done for this. Any composition calls on Promise/Future is supposed to be a Promise/Future in itself. Just because the language allows the syntax should not change the semantics. Moreover when the user is configuring the system in such a way and the system is behaving rightly. Whether the task can be submitted should be the first course of action which in this case is rightly happening.
The fix will change the semantics which differentiates the error in case of failure to execute user passed function and the basic ground to determine if we have resources to execute the task.

**Comment by viktorklang** [comment]
@sahilahmadlone The current behaviour os non-deterministic and surprising—depending on whether the Future is already completed or not, the RejectedExecutionException will be thrown on different threads.

**Comment by sahilahmadlone** [comment]
You are right as it depends on Future completion but at the same time, you should put emphasis on the configuration of the executor, which translates into this behavior.
One concern I have is programming interface as mostly the applications use the future failure as the business logic failure and in this case its the system failure which should be propagated in term of throw rather than a future status.

**Comment by gabrielgiussi** [comment]
But if you propagate the exception in terms of throw instead of the value of the Future it could blow up in any place. Who would you handle this?
You should complete the Future with the Exception or never complete it, I can't see another option.

**Comment by sahilahmadlone** [comment]
The fact being the system won't go in fail state as because as soon as we have the thread again available for execution it could have passed. Looks to me pure programmers fault in this case.

**Comment by sahilahmadlone** [comment]
@gabrielgiussi You also have to pay attention the type of Queue you are passing. Blocking with wait line as 1 which itself says what the programmer wants.

**Comment by gabrielgiussi** [comment]
Bounded Queues are actually the way of fixing `OutOfMemory` errors.
I think we aren't trying to limit the resources, the resources ARE limited.

**Comment by viktorklang** [comment]
I think the argument is that the user of the EC shouldn't have to know how it is implemented, and as such those exceptions shouldn't affect the code which adds the operation.

**Comment by eugeniyk** [comment]
Currently using bounded, rethrowable executor is not possible without mentioned hack.

Why it's a hack? Constructing `Future` / map / flatMap / onComplete / transform / etc supposed to be safe for `NonFatal` exceptions. `RejectedExecutionException` is expected behavior as backpressure signal, and it's not error neither fatal.

I agree with @gabrielgiussi, making Future never complete has to be avoidable by all means

@viktorklang this can also have implications of providing cancellation ability for std Futures? If we'll increase the states space for Futures we'll have NotReady|Ready|Failed|JVM Error + new Rejected (failed)|Cancelled(failed)|Timeouted(failed) etc

**Comment by viktorklang** [comment]
@eugeniyk Cancellation is not part of the Future state space—Cancellation is related to a task, and Future represents a value. See: https://viktorklang.com/blog/Futures-in-Scala-protips-6.html

**Comment by eugeniyk** [comment]
that's interesting

we keep modelling Future as `value` eventually available in future (if it's forever - it's probably a leak or algo completeness issue), at the same time we are aware of exceptions and JVM errors, but we are limiting internal relation to java `Executors` that potentially has richer states 

I don't mean here that I can cancel the future (as Future is read-only part from consumer side), I just mean we want to be able to observe other states from underlying abstraction as Executor etc

What if we start looking at `Future` just like `Runnable` (derivation of Task as resulted value, where, from producer side, other manipulations are possible through `tryComplete`)? Reject, cancel and timeout states would be natural and could fit under `Failure`

**Comment by eugeniyk** [comment]
Btw in guava they are using one-shot rejection-aware context (https://github.com/google/guava/blob/9537f78cc652a4f5e77f4f418d5bbf4f49674515/android/guava/src/com/google/common/util/concurrent/MoreExecutors.java#L967) that allows them to fail it

Is there any significant design differences with std scala one? I'm trying to figure out but lost with states, callbacks, executors and listeners =)

**Comment by som-snytt** [comment]
The future is failed in 2.13 as described.
