### ISSUE TITLE
Official docker images

### ISSUE THREAD

**Issue by vaibhavsood** [scala/bug#10627]
Hi, want to check if ppc64le official docker images are supported for scala? I could not find it listed as an architecture https://hub.docker.com/_/influxdb/

Thanks!

**Comment by SethTisue** [comment]
Docker stuff is community/third-party, there's no Docker stuff under https://github.com/scala

I'm not sure where the best place to ask about this, as I'm not personally familiar with what exists in this area. http://scala-lang.org/community/ is a starting point on where to seek out folks with more knowledge on it

**Comment by jvican** [comment]
Hello @vaibhavsood , you may be interested in checking out these two images:
1. https://hub.docker.com/r/scalacenter/scala/
1. https://hub.docker.com/r/scalaplatform/scala/
  
We should probably add them to the docs, so that more folks know of their existence. There's certainly some weird stuff adopted for Drone, so I recommend you to check out the repo https://github.com/scalacenter/docker-scala
