### ISSUE TITLE
lineStream is too eager

### ISSUE THREAD

**Issue by elibarzilay** [scala/bug#10696]
The documentation says that `.lineStream` "blocks when lines are not available", but it would be much more useful if it wouldn't block *until* trying to read from the resulting stream.

For example, [this page](https://alvinalexander.com/scala/how-to-execute-external-system-commands-in-scala) claims that `lines` runs the process in the background, but this is not entirely true.

**Comment by SethTisue** [comment]
`scala.collection.immutable.Stream` has a strict head, only the tail is lazy, so `lineStream` _must_ read the first line before we can return the `Stream`.

It will become possible to improve this in Scala 2.13, when `Stream` will be replaced with `LazyList` which is full lazy.

**Comment by elibarzilay** [comment]
@SethTisue Yeah, that was my guess --- but it would be nice if there was
a way around it nice since exactly in this case having it be properly
lazy would be much more useful...

(Also, that page from the scala cookbook thing should be updated.)

**Comment by SethTisue** [comment]
the Scala cookbook is third-party, you'd have to notify Alvin about that separately.

I'm only just now realizing that you're talking about the `lineStream` in `scala.sys.process` and not the one on `io.Source`, but my remarks above apply to both.

`io.Source` has `getLines` which returns an `Iterator`, which is of course fully lazy.

although I haven't studied it carefully, I don't see anything comparable in the `scala.sys.process` stuff, which is probably a design mistake. but it's too late to do anything about it for 2.12.x, we can't add new API, because of binary compatibility.

as for the 2.13.x context, the plan there is to split `scala.sys.process` out of the standard library altogether, and put it in a separate repo as a standard module. at that point this will become actionable in that repo. for now, we can leave the ticket open here.

**Comment by joshlemer** [comment]
Should this now be closed since there is now the method `ProcessBuilder#lazyLines: LazyList[String]`?

**Comment by SethTisue** [comment]
indeed

**Comment by SethTisue** [comment]
> as for the 2.13.x context, the plan there is to split scala.sys.process out of the standard library altogether, and put it in a separate repo

(well, we didn't get to this for 2.13. hopefully 2.14)

**Comment by NthPortal** [comment]
I'd have to look, but I suspect it that `lazyLines` may need to be tweaked to use `LazyList.unfold` or something. I will have a look after M5 when the new `LazyList` is merged.
