### ISSUE TITLE
REPL confused by existential types

### ISSUE THREAD

**Issue by joroKr21** [scala/bug#10769]
Those are bugs in the printer:
```scala
scala> val x: Int forSome { type A } = 42
x: Int[] = 42
```
this one by @alexknvl
```scala
scala> val x: x.type forSome { val x: x.type forSome { val x: String } } = "a"
x: x.type forSome { val x: x.type forSome { type x.type <: String } } = a
```
on Scala 2.12.4

**Comment by evanhaldane** [comment]
@SethTisue Hi! I'm looking into this as a first issue.

As I understand it, the REPL is not correctly inferring the lack of dependence on the existentially quantified variable(s). Of course, once the value is assigned, it disappears, since we have:

```scala
scala> val x: Int forSome {type A} = 42
x: Int[] = 42
```

```scala
scala> x
res0: Int = 42
```

If the type is for a function argument, we get:

```scala
scala> val f = (x: Int forSome {type A}) => 42
f: Int[] => Int = $$Lambda$3521/2106745158@6c60f905
```

```scala
scala> f
res4: Int[] => Int = $$Lambda$3521/2106745158@6c60f905
```

The bug in the former does not exist in Ammonite, as we get:
```scala
@ val x: Int forSome {type A} = 42
x: Int = 42
```

whereas for the latter, it does not evaluate the type expression, but it prints correctly:

```scala
@ val f = (x: Int forSome {type A}) => 42
f: Int forSome { type A } => Int = ammonite.$sess.cmd0$$$Lambda$1922/1547398254@5b43fbf6

```
Some questions: 
1) Is the desired behavior that of Ammonite?
2) Do you have a sense of whether the solution would involve allowing the compiler to interpret the type expression, making the quantified variable disappear, or will the REPL code itself have to do that same work, inferring the lack of dependence?

I'm just getting up-to-speed here so I hope the second question makes sense.

Thanks!

**Comment by SethTisue** [comment]
@joroKr21 can you clarify the report...?

**Comment by joroKr21** [comment]
I'm not sure what the desired behavior is. But the printed types are not even valid Scala syntax, so in that regard what Ammonite does is already an improvement.

**Comment by SethTisue** [comment]
@evanhaldane I'm sorry, I apparently forgot to reply to this, and now a great deal of time has passed.

if you're still around and still interested, let me know, and I'll try to answer
