### ISSUE TITLE
Varargs method overloading with another type leads to double definition error 

### ISSUE THREAD

**Issue by dos65** [scala/bug#10787]
Example:
```scala
object A {
  def apply(ints: Int*): Unit = {}
  def apply(strings: String*): Unit = {} // error: double definition:
}
```
Compiler error:
```
error: double definition:
def apply(ints: Int*): Unit at line 2 and
def apply(strings: String*): Unit at line 3
have same type after erasure: (ints: Seq)Unit
  def apply(strings: String*): Unit = {}
      ^
one error found

```

**Comment by SethTisue** [comment]
This is working as designed. As the error message says, both types erase to `Seq[_]`. "It is also an error if a template contains two members (directly defined or inherited) with the same name and the same erased type" (SLS 5.3)

**Comment by dos65** [comment]
I was worried about if it's by design. But after compiling the similar case on Java, I decided to report that - in java varargs aren't erased.

**Comment by NthPortal** [comment]
In Java, varargs are arrays, which are of type `int[]` or `String[]` in
your case - there's nothing to erase. In Scala, those same varargs are of
type `Seq[Int]` or `Seq[String]`, which both erase to `Seq[_]` (or
technically `Seq`).

**Comment by SethTisue** [comment]
> in java varargs aren't erased

yeah, Java represents varargs using `Array` instead of `Seq`, and `Array` is special on the JVM level in that its type parameter isn't erased, so e.g. this compiles: `object O { def x(xs: Array[String]) = (); def x(xs: Array[Int]) = () }` but if you change `Array` to `Seq` it doesn't.

I don't for sure know the history of Scala varargs being `Seq`, but my guess is that Martin & co wanted to avoid baking a JVM dependency into the spec. Back then the concern would have been .NET, nowadays it would be Scala.js and Scala Native.

**Comment by SethTisue** [comment]
jinx!

**Comment by SethTisue** [comment]
Oh, it's also convenient for performance that in Scala you can pass any `Seq` as varargs directly without having to copy the contents into an array.
