### ISSUE TITLE
Scala 2.13.0-M4-pre-20d3c21 : SortedMap#transform should return a SortedMap

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#10834]
```
Welcome to Scala 2.13.0-M4-pre-20d3c21 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> scala.collection.immutable.SortedMap(1 -> 2).transform(_ + _)
res0: scala.collection.immutable.Map[Int,Int] = ChampHashMap(1 -> 3)
```

```
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> scala.collection.immutable.SortedMap(1 -> 2).transform(_ + _)
res0: scala.collection.immutable.SortedMap[Int,Int] = Map(1 -> 3)
```

**Comment by Jasper-M** [comment]
The issue here seems to be that trait `SortedMapOps[K, +V, +CC[X, +Y], +C]` extends `MapOps[K, V, Map, C]` instead of `MapOps[K, V, CC, C]`. I'm sure there's some reason for this, and you could probably circumvent it by duplicating some methods in `SortedMap`. It looks like a design flaw though.

**Comment by NthPortal** [comment]
It probably needs to be manually overridden.

Because most methods on `SortedMap[K, _]` yielding a `Map` do not yield a `Map[K, _]` (that is, they yield a map with a different key type), they cannot all yield a `SortedMap` in general (that would require an `Ordering` for the new key type). I don't imagine it would be too difficult to override though.

**Comment by NthPortal** [comment]
I'll see if I can tackle this this weekend
