### ISSUE TITLE
Specialized hash maps lose their type with +

### ISSUE THREAD

**Issue by Ichoran** [scala/bug#10876]
It is deprecated, but this is still breaking behavior:

```scala
scala> collection.mutable.AnyRefMap("fish" -> 3)
res0: scala.collection.mutable.AnyRefMap[String,Int] = AnyRefMap(fish -> 3)

scala> res0 + ("birds", 2)
            ^
       warning: method + in trait MapOps is deprecated (since 2.13.0): Consider requiring an immutable Map or fall back to Map.concat
res1: scala.collection.mutable.Map[String,Int] = HashMap(fish -> 3, birds -> 2)
```

**Comment by szeiger** [comment]
The methods return a `CC` so they keep the correct type in general. The exceptions are the mutable `SortedMap`, `LongMap` and `AnyRefMap` which require special-casing because they cannot refine `CC`.

**Comment by szeiger** [comment]
There's also a related consistency in `SortedMap.concat` which currently allows widening of the key type. This requires an overload instead of an override. The latter is sufficient in `AnyRefMap` and `LongMap` because `Map.concat` does not allow widening. `SortedMap` didn't allow it in 2.12, either (https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/SortedMapLike.scala#L96). I think we should remove the widening.
