### ISSUE TITLE
ArrayBuilder has a memory leak

### ISSUE THREAD

**Issue by mkeskells** [scala/bug#10923]
https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/mutable/ArrayBuilder.scala#L33

```
  final def clear(): Unit = size = 0
```
this means that existing elements in the array are not dereferenced

**Comment by szeiger** [comment]
There are two mutually incompatible optimizations one can perform. Either avoid allocating new arrays by keeping owned arrays after `result()` is called or ensure that no references are retained. `ArrayBuilder` does the former and IMHO this is the right decision. If you want to ensure that no references are retained, you can drop the `ArrayBuilder` instead of reusing it.

One situation that we can optimize is when an `ArrayBuilder` gives up ownership of its backing `Array` instead of copying it in `result()` because the size already matches:

```scala
      if (capacity != 0 && capacity == size) {
        capacity = 0
        elems
      }
```
It should also set `elems = null` to drop the reference at this point because it can never be reused and the next addition to the `ArrayBuilder` would drop it anyway.
