### ISSUE TITLE
Builder size/isEmpty

### ISSUE THREAD

**Issue by mkeskells** [scala/bug#10924]
It would be useful for builders to provide some indication as to size, isEmpty/sizeCompare 

In hot-path situations where we generate a result and process that result, it would be useful to optimise the isEmpty case (and maybe others)

**Comment by joshlemer** [comment]
@mkeskells maybe something kinda like (but with a different name obviously)
```scala  
/** Returns number of elements if possible, otherwise -1 */
def sizeIfAtAllPossible: Int
```

would do the trick? The problem I see with this is that `Builder[A, Iterator[A]]` cannot support a `size: Int` method because it would need to consume the `Iterator[A]` to compute its size. I was thinking about adding `def knownSize: Int` to `Builder`, but this has a slightly different meaning -- it will only compute the size if it is trivially easy to do so. I assume that even in cases like `Builder[A, immutable.Set[A]]` you would want `size` to compute the real size, not `-1`, however `Set[A]#knownSize` will return `-1`. 

Any idea on a good name for this method defined on `Builder`?

**Comment by shawjef3** [comment]
Make everything explicit and optional when it might be unknown for a given builder. Example,

case class Size(size: Option[Int], knownSize: Option[Int], isDefiniteSize: Boolean)

`def size: Size`

**Comment by mkeskells** [comment]
@shawjef3 please lets not create garbage on a call to size

**Comment by adriaanm** [comment]
👋 who would like to implement this?
