### ISSUE TITLE
collection.Map -- not available in 2.13.0-M4

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10957]
It's not possible to remove elements on `collection.Map` but it's possible to add [`collection.Map.++`](https://static.javadoc.io/org.scala-lang/scala-library/2.13.0-M4/scala/collection/Map.html#++[V2%3E:V](xs:Iterable[(K,V2)]):CC[K,V2])

**Comment by julienrf** [comment]
Reminder: we removed `--` in `collection.Map` because then `collection.mutable.Map` would inherit from it in addition to its own `--=`. If we add it back I think it should be deprecated, with the same kind of messages we already have for `collection.Map#+` (https://static.javadoc.io/org.scala-lang/scala-library/2.13.0-M4/scala/collection/Map.html#+[V1%3E:V](kv:(K,V1)):CC[K,V1]).
