### ISSUE TITLE
[2.13.0-M4] missing methods in IterableOps, IterableOnceOps

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10974]
* `IterableOps`
  * missing methods from `TraversableLike`
    * [ ] `def ++:[B](that: TraversableOnce[B]): Traversable[B]`
    * [x] `def view(from: Int, until: Int): TraversableView[A, Repr]`

  * missing methods from GenTraversableLike
    * [ ] `def repr: Repr`
    * [x] `def stringPrefix: String`
    * [x] `def sameElements(that: GenIterable[A]): Boolean`

* `  IterableOnceOps`
  * missing methods from `IterableOnce`
    * [x] `def copyToBuffer(dest: Buffer[B]): Unit`

  * missing methods from `GenTraversableOnce`
    * [x] `def copyToArray(xs: Array[A]): Unit`
    * [x] `def hasDefiniteSize: Boolean`
    * [x] `def isTraversableAgain: Boolean`
    * [x] `def toBuffer[A1 >: A]: Buffer[A1]`
    * [x] `def toIterator: Iterator[A]`

**Comment by julienrf** [comment]
We do have `stringPrefix`, `sameElements` (deprecated and provided by an implicit conversion), `copyToBuffer` (deprecated), `copyToArray`, `hasDefiniteSize` and `toIterator`.

I think `++:` does not really make sense on `Iterable` because there is no notion of element order so you can use `ys ++ xs` instead of `xs ++: ys`. If element order is important then you should use a `Seq`. Thus, we should add `++:` for compatibility only and it should be deprecated.

I’m not sure what we should do with `view(from, until)`. Should we add it and deprecate it in favor of `view.slice(from, until)`?

We can add `def repr: C = coll`. Note that `coll` is `protected`, whereas `repr` was public. Should we make `coll` public (and deprecate `repr`)? Maybe it can be useful for people writing extension methods.

We can add `isTraversableAgain: Boolean = this.instanceOf[Iterable[_]]`.

**Comment by szeiger** [comment]
I was wondering about the use case for `repr`. We can easily add it but there's no good replacement to recommend. In a collection implementation you would use `coll`. Is there any reason to call it from the outside? In extension methods you can tie the knot with suitable type constraints so that the collection value itself is its own `repr`. This should work for all collections in 2.13. The previous corner cases `StringOps` and `ArrayOps` are no longer collection types.

**Comment by julienrf** [comment]
That makes sense. So, we would just reintroduce it for backward compatibility and deprecate it?
