### ISSUE TITLE
[2.13.0-M4] missing classes on ArrayOps

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10986]
* [ ] `ofBoolean`
* [ ] `ofByte`
* [ ] `ofChar`
* [ ] `ofDouble`
* [ ] `ofFloat`
* [ ] `ofInt`
* [ ] `ofLong`
* [ ] `ofRef[T <: AnyRef]`
* [ ] `ofShort`
* [ ] `ofUnit`

**Comment by julienrf** [comment]
These public classes have been moved to the `ArrayBuilder` object. We should move them back to `ArrayOps`, unless there is a reason for that? (maybe @szeiger knows?)

**Comment by Jasper-M** [comment]
To quote [myself](https://github.com/scala/bug/issues/10966#issuecomment-402182484):

> I just realized, ArrayOps is a value class. In 2.12 those specialized subclasses were also value classes, but that was completely useless since value classes still box when you call an inherited method on them. You would have to redefine all inherited members in every specialized subclass if you want to avoid the extra boxing.

To which @Ichoran says:

> @Jasper-M - Yes, that's absolutely right! It's still probably worth doing, if someone is willing to keep it all straight.

**Comment by szeiger** [comment]
Unrelated to `ArrayBuilder`. I removed these classes because they appear to be useless. The only specialized methods were `length`, `apply` and `update`, none of which is ever called because they are available directly on `Array`. Other methods did not benefit from the specialization because `ArrayOps` itself is not specialized. In fact, the subclasses are actually harmful for performance because they prevent all the inherited methods (i.e. the ones that really get called) from becoming extension methods.

**Comment by szeiger** [comment]
A small addition: The specialized methods are called from `ArrayOps` methods to prevent typecasing on array types for every access in bulk operations. We can do this in a different way inside the `ArrayOps` bulk methods as already implemented in `fold`, `foldLeft` and `foldRight`. It may be useful to do the same for other methods that can benefit from this optimization.

**Comment by szeiger** [comment]
Closing because we don't intent to add these classes back.
