### ISSUE TITLE
Consider adding an `updateWith` operation on mutable Maps

### ISSUE THREAD

**Issue by julienrf** [scala/bug#11004]
From https://github.com/scala/bug/issues/10949#issuecomment-403114097:

> We should still have a proper efficient `updateWith(k, f: V => V): Boolean` at least for mutable maps where slotting the new item in the same hole is vastly faster than doing two lookups.

**Comment by nasadorian** [comment]
Hi @julienrf I quickly wrote up these implementations. I saw in the previous discussion that the function was supposed to be in terms of PartialFunction on Option[V]. I'm assuming this is because you'd want the user to have control over the situation where there is no value?

`  implicit class updateWithImmutable[K,V](m: Map[K, V]) {
    def updatedWith(k: K, f: V => V): Map[K, V] =
      m.get(k).fold(m)(v => m.updated(k, f(v)))
  }

  implicit class updateWithMutable[K,V](m: mutable.Map[K, V]) {
    def updateWith(k: K, f: V => V): Unit =
      m.get(k).fold(())(v => m.put(k, f(v)))
  }
`

**Comment by julienrf** [comment]
Operating on an `Option[V] => Option[V]` instead of a `V => V` gives the users the ability to:
- say what to do in case there was no binding (when the incoming option is `None`),
- remove the binding (by returning `None`)

**Comment by julienrf** [comment]
Superseded by #11185
