### ISSUE TITLE
`knownSize` not always constant time on views

### ISSUE THREAD

**Issue by allanrenucci** [scala/bug#11005]
> The number of elements in this $coll, if it can be cheaply computed, -1 otherwise. Cheaply usually means: Not requiring a collection traversal.

Most of the `knownSize` implementations on views are defined in term of the underlying data-structure. If the underlying data structure is itself a view then the contract for `knownSize` can be broken. E.g.
```scala
xss.foldLeft(View.empty[A])(new View.Concat(_, _)).knownSize
```
In the example above, the complexity of `knownSize` is linear in the size of `xss`

**Comment by NthPortal** [comment]
what's the desired fix for this? possibilities include:

- That's how views work, and that's what happens if you nest a ton of `View.Concat`s. You're using `View.Concat` essentially as a cons cell, which is not intended. Don't do that
- `View.Concat#knownSize` always returns `-1`
- `View.Concat#knownSize` does something fancy to attempt to detect if it is comprised of other `View`s (or maybe specifically other `View.Concat`s? idk). If so, it bails and returns `-1`; if not, it does what it currently does

**Comment by julienrf** [comment]
We can try to implement the third proposition (basically, “fusion” for `knownSize`). Otherwise I’m happy to live with the first proposition. I think the second proposition (always returning `-1` in views) may cause more harm than good.

**Comment by allanrenucci** [comment]
This issue is not specific to `View.Concat`. All views that implements `knownSize` in term of the underlying collection share the same issue (e.g. `Drop`, `Take`, `ScanLeft`, `Map`...)

> You're using View.Concat essentially as a cons cell, for which it's not intended. Don't do that

https://github.com/scala/scala/blob/40d0f04830c504925327250503c1c457d455e452/src/library/scala/collection/Factory.scala#L243-L245

Not sure what the best solution is but we should at least change all the `knownSize` implementations to avoid repeated calls to `knownSize`. E.g.
```diff
diff --git a/src/library/scala/collection/View.scala b/src/library/scala/collection/View.scala
index d7d18b71ef..64a208abae 100644
--- a/src/library/scala/collection/View.scala
+++ b/src/library/scala/collection/View.scala
@@ -259,7 +259,10 @@ object View extends IterableFactory[View] {
   @SerialVersionUID(3L)
   class Appended[A](underlying: SomeIterableOps[A], elem: A) extends AbstractView[A] {
     def iterator: Iterator[A] = new Concat(underlying, new View.Single(elem)).iterator
-    override def knownSize: Int = if (underlying.knownSize >= 0) underlying.knownSize + 1 else -1
+    override def knownSize: Int = {
+      val size = underlying.knownSize
+      if (size >= 0) size + 1 else -1
+    }
   }
```

**Comment by julienrf** [comment]
I agree: a simple improvement would be to not re-evaluate `knownSize`.

**Comment by julienrf** [comment]
Maybe the title of the issue is not clear. Indeed, `knownSize` on views independent of the number of elements of the views, but if you combine a *collection of views* together, then `knownSize` is linear with the number of combined views.

**Comment by NthPortal** [comment]
yes, `View.Prepended` is going to have the same problem as `View.Concat` - I would stick them in the same category.

Funnily enough, since `xs` is a list, `view1.knownSize` is actually linear in the size of `xs` to discover that the size is not known xD

In your first example, `view1.last` is also O(n<sup>2</sup>), so... bad performance everywhere! ¯\\\_(ツ)_/¯

Honestly, this makes me lean more towards option 1: don't deeply nest views, or you'll get bad performance. This isn't just true of `knownSize`; it's true of pretty much all operations.

**Comment by SethTisue** [comment]
> this makes me lean more towards option 1

agree

**Comment by NthPortal** [comment]
Are we closing this as "works as intended"?

**Comment by julienrf** [comment]
Yes.

**Comment by dwijnand** [comment]
Shouldn't the scaladocs of `knownSize` at least be tweaked?

Having to memoize underlying known sizes like scala/scala#6988 proposes is surprising.

**Comment by NthPortal** [comment]
@dwijnand the current scaladocs say:

> The number of elements in this $coll, if it can be cheaply computed, -1 otherwise. Cheaply usually means: Not requiring a collection traversal.

At least to me, this doesn't indicate that the operation has a negligible cost; just that it's not O(n). I would never expect it to be expensive, but there's no need to compute it twice (PEP 572 anyone? 😉).

**Comment by NthPortal** [comment]
Oh, huh. We should probably bring the docs in line with each other then.

**Comment by julienrf** [comment]
Indeed, the docs should not be overridden in `IterableOnceOps`. We should move what is currently in `IterableOnceOps` to `IterableOnce`.
