### ISSUE TITLE
[2.13.0-M4] Missing type Coll

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11010]
https://static.javadoc.io/org.scala-lang/scala-library/2.12.6/index.html?search=Coll

**Comment by julienrf** [comment]
I think that, in `IterableOps`, `Coll` should be an alias to `CC[_]`. In `MapOps` it should be an alias to `CC[_, _]`.

**Comment by Prithvirajbilla** [comment]
Is this is the issue?
https://static.javadoc.io/org.scala-lang/scala-library/2.13.0-M4/index.html?search=Coll doesn't list lot of collections in `Member results`. whereas, https://static.javadoc.io/org.scala-lang/scala-library/2.12.6/index.html?search=Coll lists collections in `Member results` correctly. 

It was not very clear to me from the description. Thanks.

**Comment by julienrf** [comment]
Hey @Prithvirajbilla. Sorry the description is not very detailed. It’s about a type member named `Coll` and defined in `GenMapFactory`, `SortedMapFactory`, `SortedSetFactory` and `GenericCompanion`.

We might want to provide an equivalent type member in our factory template traits (e.g. `IterableFactory`, `MapFactory`, etc.) for the sake of compatibility. That being said, I think this type member was mostly used as a parameter of `CanBuildFrom` instances. Since we don’t use that anymore I’m not sure if having `Coll` would be useful at all.

@MasseGuillaume Did you see scenarios where `Coll` would be useful?

**Comment by MasseGuillaume** [comment]
Only for `CanBuildFrom` so far.

**Comment by julienrf** [comment]
Ok, then I suggest that we focus on more urgent things!

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/7380 was abandoned (thank you, @grizio, for taking a stab at it!

@NthPortal @julienrf should we even leave this ticket open...? I haven't tried to study this to understand what happened

**Comment by NthPortal** [comment]
scala/scala#7380 attempts the obvious fix, which is just to add the type aliases pretty much as defined in 2.12; however, that produces errors:

```scala
[error] /mnt/d/April/code/personal/scala/src/library/scala/collection/Factory.scala:88:8: covariant type CC occurs in invariant position in type CC[_] of type Coll
[error]   type Coll = CC[_]
[error]        ^
[error] /mnt/d/April/code/personal/scala/src/library/scala/collection/Factory.scala:391:8: covariant type CC occurs in invariant position in type CC[_, _] of type Coll
[error]   type Coll = CC[_, _]
[error]        ^
[error] /mnt/d/April/code/personal/scala/src/library/scala/collection/Factory.scala:451:8: covariant type CC occurs in invariant position in type CC[_] of type Coll
[error]   type Coll = CC[_]
[error]        ^
[error] /mnt/d/April/code/personal/scala/src/library/scala/collection/Factory.scala:734:8: covariant type CC occurs in invariant position in type CC[_, _] of type Coll
[error]   type Coll = CC[_, _]
[error]        ^
```

I don't know if there's an easy fix to this. Does `@uncheckedVariance` work? Is that valid/safe/correct?
If there is an easy fix, it seems simple to revive and push through, but otherwise I would tend to agree with @julienrf that it's not a very high priority.

**Comment by grizio** [comment]
For your information, `@uncheckedVariance` did not work, as some other annotations to ignore the issue.

**Comment by julienrf** [comment]
I think we can close this issue. We might re-open it if we find problematic cases in the wild, but I doubt lots of codebases rely on this `Coll` type member.
