### ISSUE TITLE
Type inference issue in presence of overloads using varargs

### ISSUE THREAD

**Issue by julienrf** [scala/bug#11015]
As reported in https://github.com/etorreborre/specs2/issues/687#issuecomment-404384272, overloading resolution does not play well with type inference in the following case:

~~~ scala
class X[A] {
  def append(a: A): Unit = ()
  def append(a: A*): Unit = ()
}

case class Foo[A](value: Int)

val x = new X[Foo[String]]

x.append(Foo(2))
// overloaded method value append with alternatives:
//   (a: Playground.this.Foo[String]*)Unit 
//   (a: Playground.this.Foo[String])Unit
//  cannot be applied to (Playground.this.Foo[Nothing])

x.append(Foo[String](2)) // OK if the type parameter of `Foo` is explicitly instantiated
~~~

This could be a problem for us because scala/scala#6879 did introduce such problematic overloads.

**Comment by SethTisue** [comment]
> This could be a problem for us because scala/scala#6879 did introduce such problematic overloads.

indeed, https://github.com/scala/bug/issues/11112

**Comment by szeiger** [comment]
I just took a quick look at this. In this particular case we end up with "second try" typing. In simpler situations it can be typed in the first try where the disambiguation works. This includes cases such as:

```scala
x.append(new Foo(2): Foo[String])
```

Compare this to the failing case:

```scala
x.append(new Foo(3))
```

The second try could be a red herring though. We end up there because the type of the argument is inferred as `Foo[Nothing]` which cannot be adapted to the expected `Foo[String]`. But I don't think it should ever get this far. Without overloading the type is correctly inferred as `Foo[String]` because we use that as the expected type. In the overloaded case there is no expected type, so I think the problem lies the type approximation that we do in overload resolution. Maybe we simply forgot to take varargs into account.

**Comment by szeiger** [comment]
I couldn't resist to look further. A possible problem is at https://github.com/scala/scala/blob/f1422a42ece9dc94af485ce0073642a457626cde/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L3392. We already know the overloaded method type `(a: this.Foo[String]*)Unit <and> (a: this.Foo[String])Unit` but we do not compute a pt from it (which would be possible in this case). I'm not sure though if this is the right place to fix this because we *do* set the function type, so maybe the argument type should be computed somewhere further down.

**Comment by adriaanm** [comment]
When I worked on improving type inference for overloaded higher-order methods, I experimented with improving our treatment of overloaded methods in general, but it proved hard to find a good balance that doesn't break existing code, while enabling newer patterns such as this one to be type checked.

The core of the problem is not really due to varargs, but because they preclude reducing the overloaded call to a non-overloaded call simply based on arity. Here's a simplified example of the same problem:

```
class Foo[A]

class Test {
  def append(a: Foo[String]): Unit = ()
  def append(a: Foo[String], as: Int*): Unit = ()

  append(new Foo) // overload can't be resolved by arity (the one with varargs fits with N=0 for the repetition), so we proceed without expected type for `new Foo`
}
```
