### ISSUE TITLE
[2.13.0-M4] Missing type collection.IndexedSeqOptimized

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11013]

**Comment by julienrf** [comment]
We should add a deprecated alias to `IndexedSeqOps`, but the type signature is not exactly the same as before (same problem as with `IndexedSeqLike` vs `IndexedSeqOps`).

**Comment by julienrf** [comment]
I’m not sure what we should do about that one. It might be fine to just document the change and not try to provide a deprecated type alias because we don’t really have an equivalent type in the new design. Also, the situation is the same for other template traits such as `immutable.LinearSeqLike`, `immutable.IndexedSeqLike`, `immutable.SeqLike`, etc.

**Comment by sjrd** [comment]
The only purpose of `IndexedSeqOptimized` is to extend from it, and it's been established that providing compatibility for custom collections was outside the scope of the new collections. Just drop it. You won't ever be able to salvage custom collections.

Btw, it's another reason for which all the `final` -> `@deprecatedOverride` are pointless.

**Comment by szeiger** [comment]
Agreed. This is an implementation class, so I'm closing this issue.
