### ISSUE TITLE
Inconsistency between `.toSeq` and `.to[Seq]` in Scala 2.12.x

### ISSUE THREAD

**Issue by plokhotnyuk** [scala/bug#11027]
Initially investigated in https://github.com/AVSystem/scala-commons/issues/76
```
andriy@notebook:~$ scala
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_171).
Type in expressions for evaluation. Or try :help.

scala> Seq(1, 2, 3)
res0: Seq[Int] = List(1, 2, 3)

scala> Seq(1, 2, 3).toSeq
res1: Seq[Int] = List(1, 2, 3)

scala> Seq(1, 2, 3).to[Seq]
res2: Seq[Int] = Vector(1, 2, 3)
```

**Comment by SethTisue** [comment]
2.10 and 2.11 are the same.

you mentioned on Gitter that this is "already fixed in 2.13.0-M4", so I'm closing the ticket.

my guess is that a pull request changing the 2.12 behavior wouldn't be accepted, on the grounds that it's better to leave long-established and not-technically-outright-incorrect behavior well enough alone this late in a release cycle
