### ISSUE TITLE
Map.flatMap regression in 2.13

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11033]
```scala
Map(1 -> 1).flatMap(_ => Some(2))
```

```scala
// obtained in 2.12
res0: scala.collection.immutable.Iterable[Int] = List(2)

// obtained in 2.13.0-M4: 
overloaded method value flatMap with alternatives:
[error]   [K2, V2](f: ((Int, Int)) => scala.collection.IterableOnce[(K2, V2)])scala.collection.mutable.Map[K2,V2] <and>
[error]   [B](f: ((Int, Int)) => scala.collection.IterableOnce[B])scala.collection.mutable.Iterable[B]
[error]  cannot be applied to (((Int, Int)) => Some[Int])
[error]   Map(1 -> 1).flatMap(_ => Some(1))
[error]               ^

```

**Comment by julienrf** [comment]
Possible workarounds:

~~~ scala
Map(1 -> 1).flatMap(_ => Some(2): Iterable[Int])
Map(1 -> 1).map(_ => Some(2)).flatten
~~~

**Comment by szeiger** [comment]
This will be fixed by https://github.com/scala/scala/pull/6871

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6871 actually didn't fix this, so it's still open.

**Comment by adriaanm** [comment]
As far as I understand, this is as specified. The expected type for the function only specifies its argument types, not its result type: https://github.com/scala/scala/pull/6871/files#diff-5d74b019862ed901d7800b4ace79fb5bR1447

**Comment by szeiger** [comment]
I've traced this into `inferMethodAlternative`. From my limited understanding of how the typechecker works, everything looks correct up to this point:

```
infer method alt value flatMap with alternatives List(
  [K2, V2](f: ((Int, Int)) => scala.collection.IterableOnce[(K2, V2)])scala.collection.immutable.Map[K2,V2],
  [B](f: ((Int, Int)) => scala.collection.IterableOnce[B])scala.collection.immutable.Iterable[B]
) argtpes=List(((Int, Int)) => Some[Int]) pt=?
```

But now `isAltApplicable` discards all alternatives because the return type of the lambda is incompatible. Commenting out this check makes it fail later because no further adaptation is attempted for the lambda's return type.

Adaptation of the whole lambda is attempted later but this is not what we need here. I'm not sure what the right way forward is in this case. Should `isAltApplicable` disregard return types of function-like types (because they may be wrong when typechecked without the correct expected type and therefore without possible adaptation to that type)? We still need to retype the function-like arguments for every alternative somewhere so that the proper adaption can be performed.

**Comment by adriaanm** [comment]
It's possible there's a better way, but I don't think we can hold up 2.13 over this. Unless someone disagrees by Monday EOD, this will have to go to 2.14.

**Comment by dwijnand** [comment]
Just throwing this out there: add an overload (not sure at what level of the hierarchy) for Option?

**Comment by eed3si9n** [comment]
To supplement the context here `Some[+A]` extends `Option[A]`, and `Option[+A]` extends `Product with Serializable`, so along the parent type there are no `Iterable` or `IterableOnce`. However in the `Option` companion object there is:

```scala
  implicit def option2Iterable[A](xo: Option[A]): Iterable[A] =
    if (xo.isEmpty) Iterable.empty else Iterable.single(xo.get)
```

So if someone were to pass in `Some(1)` to an argument expecting `Iterable[A]` it would work, but `Some(1)` is not an `IterableOnce` that the following candidates expect:

```scala
scala> Map(1 -> 1).flatMap(_ => Some(2))
                   ^
       error: overloaded method value flatMap with alternatives:
         [K2, V2](f: ((Int, Int)) => scala.collection.IterableOnce[(K2, V2)])scala.collection.immutable.Map[K2,V2] <and>
         [B](f: ((Int, Int)) => scala.collection.IterableOnce[B])scala.collection.immutable.Iterable[B]
        cannot be applied to (((Int, Int)) => Some[Int])
```

So in terms of the language spec and given overloads it does make sense, while it might be surprising to Scala 2.12.x users.

> Just throwing this out there: add an overload (not sure at what level of the hierarchy) for Option?

If it's up to me, I'd put an overload with `@deprecatedError("Option is not an Iterable. use List instead", since="1.3.0")`.

**Comment by lrytz** [comment]
We'd need two overloads

```
  def flatMap[B](f: ((K, V)) => Option[B])(implicit dummy: DummyImplicit): Iterable[B] = flatMap(x => f(x): Iterable[B])

  def flatMap[K2, V2](f: ((K, V)) => Option[(K2, V2)])(implicit dummy: DummyImplicit): CC[K2, V2] = flatMap(x => f(x): Iterable[(K2, V2)])
```

The other option would be to make `Option` extend `IterableOnce`, which is not difficult, but adds  some not-very-useful methods to `Option`'s API (like `take`).

**Comment by SethTisue** [comment]
discussed at team meeting just now. there were two threads of discussion:

* is it a good idea to make the change this late in the 2.13 cycle
* is it a good change at all

I'm a strong "no" on the first

(and a weaker "no" on the second, but if we agree it's too late for 2.13, we have time to think on that. as Lukas points out, `IterableOnce` is a thinner dependency than the pre-2.13 alternatives, so I need to think on whether I'm clinging to my ≤2.12 position on this out of habit)

**Comment by NthPortal** [comment]
@lrytz don't those both erase to `flatMap(Function1)(DummyImplicit)`?

**Comment by lrytz** [comment]
@Nth They have different return types, which is allowed in bytecode.

**Comment by adriaanm** [comment]
Unscheduling for the RC cycle as it has an easy workaround. For 2.14, we could consider either improving type inference to have an expected type for the higher-order function's result, or have Option extend IterableOnce (my preference).

**Comment by ashawley** [comment]
More workarounds:

```scala
Map(1->1).toList.flatMap(_ => Some(2))
Map(1->1).flatMap[Int](_ => Some(2)) // Only works in 2.13.0-RC1
```

**Comment by ashawley** [comment]
> As far as I understand, this is as specified. The expected type for the function only specifies its argument types, not its result type.

So the two `flatMap` definitions are ambiguous?  Why does `Map`  in the new collections have two `flatMap` definitions, then?  It only had one in 2.12.

**Comment by dwijnand** [comment]
https://github.com/scala/scala/blob/v2.13.0-RC1/src/library/scala/collection/Map.scala#L267

**Comment by adriaanm** [comment]
We decided to have Option extend IterableOnce to avoid regressing here (the workaround was a bit clunky): https://github.com/scala/scala/pull/8038

**Comment by dwijnand** [comment]
Fixed by https://github.com/scala/scala/pull/8038, then.
