### ISSUE TITLE
Deprecate tupleNZipped operations

### ISSUE THREAD

**Issue by julienrf** [scala/bug#11041]
These operations have been replaced by `lazyZip`:

~~~ scala
// old style
(xs, ys).zipped.map((x, y) => x + y)

// new style
xs.lazyZip(ys).map((x, y) => x + y)
~~~

We should deprecate the implicit conversion that makes the `zipped` operation available.

**Comment by joshlemer** [comment]
@julienrf does this mean that all of these are deprecated?

* Tuple2Zipped
* ZippedIterable2
* Tuple3Zipped
* ZippedIterable3

**Comment by joshlemer** [comment]
And of course, the conversion that enables `(xs, ys, zs).zipped`

**Comment by SethTisue** [comment]
ALL THE THINGS

**Comment by joshlemer** [comment]
For now I have not deprecated the above 4 classes, just the implicit conversions, but will if that's what's wanted.

**Comment by SethTisue** [comment]
direct usages of these classes are almost certainly exceedingly rare or nonexistent, but regardless, I don't see a downside to deprecating them

**Comment by SethTisue** [comment]
anyway deprecating them will help us remember to delete them later

**Comment by manojo** [comment]
Butting in a bit late, for sure, but what is the reasoning behind deprecating `zipped`?  It feels so much more intuitive to write `(x, y, z, a).zipped` over `x.lazyZip(y).lazyZip(y).lazyZip(a)`. Is there a performance issue whereby it is discouraged to zip many collections together?

**Comment by SethTisue** [comment]
I don't remember all the details, but we've all had a pretty dim opinion of`zipped` for a long time. as best I can recall off the top of my head,

1) uniformness and discoverability (e.g. via autocompletion) are both good reasons to have methods on collections directly whenever possible, rather than adding extension methods to tuples. (also, conversely, extension methods on common types such as tuples have an annoying way of turning up in annoyingly unrelated situations Scaladoc, autocompletion, error messages, and so forth, though I don't recall if this was a concern for `zipped` in particular)
1a) it isn't clear to me — in fact, I think I disagree — that `(x, y, z, a).zipped` is "intuitive". it became familiar, perhaps. familiar things have a way of coming to seem "intuitive", but designwise, especially when doing a sweeping redesign, we're more concerned with newcomers than with people are who accustomed to familiar things
2) yes, performance, we avoid making the tuple, which is especially a win in the common `Tuple2` case
3) we wanted to add `lazyZip` anyway for largely unrelated reasons, some discussion is at https://github.com/scala/collection-strawman/pull/223
3b) and then once you have `lazyZip`, the case for keeping `zipped` around diminishes a lot
4) the reason `zipped` ever existed in the first place was to make the operations lazy, but there wasn't a good way to do that in the old collections, so we added `zipped` and some custom types to make it work. in the new design, laziness is well-supported and so that permitted a cleaner design

maybe @julienrf has something to add; the original ticket (https://github.com/scala/collection-strawman/issues/221) gives the impression of being the product of in-person discussion

**Comment by tpolecat** [comment]
FWIW, if you're using Cats the parallel applicative instances for list-like types have zipping behavior, which is a lot like the old `.zipped`.

```scala
@ (List(1,2,3), List("a", "b"), List(true, false)).parTupled 
res6: List[(Int, String, Boolean)] = List((1, "a", true), (2, "b", false))

@ (List(1,2,3), List("a", "b"), List(true, false)).parMapN((n, s, b) => s"$n $s $b") 
res7: List[String] = List("1 a true", "2 b false")
```

**Comment by manojo** [comment]
Thank you for the explanations, and the alternatives available at cats.

The reasoning behind having a cleaner design makes sense indeed. Regarding the familiarity question, from a user point of view I still think that having something like `parTupled` in cats, or maybe even an explicit `TupleOps.zipN` is easier on the eyes.

Then again, maybe the deprecation and lack of such methods is deliberate in discouraging such constructions.
