### ISSUE TITLE
Iterable ++ Iterator

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11053]
This snippet compile in 2.12 but not in 2.13

```scala
def t(names: Iterator[String]): Unit = {
  (Vector() ++ names): Vector[String]
}
```

```
[error] /home/gui/scala-collection-compat/compat/src/test/scala/test/scala/collection/Playground.scala:15: type mismatch;
[error]  found   : Iterator[String]
[error]  required: Iterable[String]
[error]     (Vector() ++ names): Vector[String]
[error]                  ^
```

**Comment by julienrf** [comment]
One way to make `++` take an `IterableOnce` would be to wrap it in `LazyList` so that it becomes iterable more than once.

**Comment by Jasper-M** [comment]
Does `++` require something that is iterable more than once, besides performance optimizations?

**Comment by julienrf** [comment]
The reason it requires an Iterable is that the view based design first builds a view of the result of the operation, and then this view might or might not be forced according to the resulting collection type. View.Concat has to be iterable more than once because it inherits from Iterable. Therefore, the only way to make it work with IterableOnce parameters is to memoize their content during the first Iteration (eg using a LazyList).

**Comment by Ichoran** [comment]
It seems counterintuitive that a view-based design, which is supposed to minimize intermediate work, is actually doing the opposite here in the default case.

Is there any reasonable workaround that will allow `xs ++ ys` to work efficiently by default?  (For instance, overloading the method to also take an `Iterator`?)

**Comment by julienrf** [comment]
The view-based design is not supposed to minimize intermediate work, it provides a correct implementation of transformation operations for both strict and non strict collections.

> Is there any reasonable workaround that will allow xs ++ ys to work efficiently by default? (For instance, overloading the method to also take an Iterator?)

We could do that maybe, but I’m not sure what benefit you would get.

The solution I propose is to rewrite the `View.Concat` type as follows:

~~~ scala
class Concat[A](prefix: IterableOnce[A], suffix: IterableOnce[A]) extends AbstractView[A] {
    private val iterablePrefix = prefix match {
      case it: Iterable[A] => it
      case _ => LazyList.from(prefix)
    }
    private val iterableSuffix = suffix match {
      case it: Iterable[A] => it
      case _ => LazyList.from(suffix)
    }
    def iterator = iterablePrefix.iterator ++ iterableSuffix.iterator
}
~~~

**Comment by szeiger** [comment]
`IterableFactory.from` can already deal with `IterableOnce`. This was not the case in the beginning. Is there any reason why `fromIterable` doesn't do the same?

```scala
  @`inline` final protected def fromIterable[E](it: Iterable[E]): CC[E] = iterableFactory.from(it)
```

If we change it to accept an `IterableOnce` it is easy for `concat` to do the same. If the RHS is `Iterable`, create a `View`, otherwise create an `Iterator`.

**Comment by julienrf** [comment]
@szeiger Good idea! We might want to do the same for `zip`, btw…
