### ISSUE TITLE
Performance degradation for concat on immutable sets and maps in 2.13.0-M5

### ISSUE THREAD

**Issue by odd** [scala/bug#11128]
The implementation of `concat` in `collection.StrictOptimizedSetOps` and `collection.StrictOptimizedMapOps` (both new in 2.13.0-M5) uses a builder to create the resulting collection. The elements of the original collection are added to the builder followed by the elements of the suffix collection. This requires `N + M` builder `addOne`-calls (where `N` is the number of elements in the original collection, and `M` is the number of elements in the suffix collection). While this is well suited for mutable sets and maps where copying is needed anyway, it is less than optimal for persistent immutable collections. By instead adding the suffix collection element-wise to the original collection, this copying can be avoided (requiring only `M` `incl`/`updated`-calls). This is indeed how `concat` is implemented in `immutable.SetOps` and `immutable.MapOps`, but this implementation is not the one inherited after the `collection.StrictOptimizedSetOps` and `collection.StrictOptimizedMapOps` was added to the immutable sets and maps in commit deb94ea.

**Comment by odd** [comment]
Looking some more at this it seems some implementations of `immutable.Iterable`, `immutable.Set` and `immutable.Map` are affected while others are not.

The affected ones (i.e. inheriting the slow version of `concat` from `collection.StrictOptimized[Iterable|Set|Map]Ops`) are:
* `immutable.ArraySet` (although `ArraySeq` needs to copy anyway since nothing is shared between instances even though it is immutable)
* `immutable.BitSet`
* `immutable.HashMap`
* `immutable.List`
* `immutable.ListMap`
* `immutable.Queue`
* `immutable.TreeMap`
* `immutable.TreeSet`
* `immutable.Vector`

The non-affected ones (i.e. either inheriting a fast version of `concat` or defining their own) are:
* `immutable.HashSet`
* `immutable.IntMap`
* `immutable.ListSet`
* `immutable.LongMap`
* `immutable.VectorMap`

Why there is a difference between for example `immutable.HashSet`/`immutable.ListSet` on the one side and `immutable.TreeSet` on the other, I do not know. I would expect it has to do with how the trait hierarchy is linearized (causing the former pair to inherit the fast implementation of `concat` from `immutable.SetOps`, but the latter to inherit the slow implementation from `collection.StrictOptimizedSetOps` instead).

**Comment by joshlemer** [comment]
Also, see https://github.com/scala/scala/pull/7192, where I've implemented a much much faster HashMap#concat method, which will be copied to HashSet if and when that PR is accepted

**Comment by adriaanm** [comment]
Can we close this one? Looks like the relevant PR was merged

**Comment by szeiger** [comment]
I've taken another look at the current state of the implementations that are listed as inheriting the slow implementation above. These ones should all be OK:
- `immutable.ArraySeq`, `immutable.List`, `immutable.Queue`, `immutable.Vector`:  Inherits `StrictOptimizedSeqOps.concat` which calls `appendedAll`; implements an optimized `appendedAll`
- `immutable.BitSet`: Uses `collection.BitSetOps.concat`
- `immutable.HashMap`, `immutable.TreeSet`, `immutable.TreeMap`: Implements `concat`

Only one still uses the default implementation:
- `immutable.ListMap`: Uses `collection.StrictOptimizedMapOps.concat`

Should we move the default implementations from `collection.StrictOptimized(Map|Set)Ops` to `mutable.StrictOptimized(Map|Set)Ops` (which doesn't exist yet) since they are not really well suited for immutable collections?

**Comment by szeiger** [comment]
It looks like the lazy implementations aren't any better so we'd have to add immutable versions of the strict implementations, too.

**Comment by szeiger** [comment]
Oops, I had a PR checked out that was based on 2.13.x before https://github.com/scala/scala/pull/7647 which added `immutable.StrictOptimized(Map|Set)Ops` with a suitable implementation. It looks like https://github.com/scala/scala/pull/7657 is the last bit of this puzzle, so I'm adding the "has PR" label again.
