### ISSUE TITLE
invalid main warning lies about signature

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/bug#11142]
```scala
object Foo { def main(args: Array[Int]) = () }
```

> Foo has a main method with parameter type Array[String], but Foo will not be a runnable program.
  Reason: main method must have exact signature (Array[String])Unit

Note that the main method doesn't actually have a main method with parameter type `Array[String]`

**Comment by som-snytt** [comment]
Ultimately,
```
badmain.scala:4: warning: not a valid main method for foo.Foo,
  because main methods must have the exact signature (Array[String])Unit.
  To define an entry point, please define the main method as:
    def main(args: Array[String]): Unit

object Foo { def main(args: Array[Int]) = () }
                 ^
one warning found
```
Institutional wisdom encoded in https://github.com/scala/scala/pull/7252

**Comment by NthPortal** [comment]
is this worth backporting to 2.12?

**Comment by som-snytt** [comment]
I'm not sure it's worth asking if it's worth backporting.

Martijn's 2.12 PR which IIRC was deemed too verbose could be committed and thereby encourage folks still grappling with `main` to upgrade. Who knows how many Scala adopters were dissuaded because "it said something weird about main"? They can try again with 2.13 and wonder why Scala still cares whether `main` takes args or why they can't write `App` with ordinary semantics.
