### ISSUE TITLE
`Ywarn-unused` of `var` setter in trait is not specific enough

### ISSUE THREAD

**Issue by beaushinkle** [scala/bug#11238]
scala version: `2.12.7`

scala:
```
import scala.collection.mutable.ListBuffer

trait Foo {
  private var appendedStrings: ListBuffer[String] = ListBuffer("a")

  private def appendString(str: String) {
    appendedStrings += str
  }

  def doAThing(): String = {
    appendString("b")
    appendString("c")
    appendedStrings.foldLeft("")(_ + _)
  }
}

class Bar extends Foo

object Main extends App {
  val bar = new Bar
  println(bar.doAThing())
}
```
in build.sbt:
```
scalacOptions ++= Seq("-Ywarn-unused:privates")
```

project link: https://github.com/beaushinkle/scala-private-false-warning

output:
```
sbt:hello-world> compile
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/beaushinkle/projects/sources/scala-private-false-warning/target/scala-2.12/classes ...
[warn] /Users/beaushinkle/projects/sources/scala-private-false-warning/src/main/scala/Main.scala:4:14: private var appendedStrings in trait Foo is never used
[warn] 	private var appendedStrings: ListBuffer[String] = ListBuffer("a")
[warn] 	            ^
[warn] one warning found
[info] Done compiling.
```

**Comment by beaushinkle** [comment]
It seems like having the `private var appendedStrings` in a `trait` which is extended by the class is at least part of the problem. If we create the `Bar` class directly instead of inheriting from Foo we get a different warning.

**Comment by som-snytt** [comment]
It's not a false positive, but it should warn that the `var` is not updated. The `+=` is a method call, not an assignment. Change it to `append` or `appended` in 2.13, for instance. Change `var` to `val` to eliminate the warning.

I'll take a look at refining the message.

Another useful warning would be to highlight this case, where the receiver of `+=` is a `var` which is not otherwise assigned. This is an obvious source of confusion.
