### ISSUE TITLE
StringLike#linesIterator not properly splitting on \r

### ISSUE THREAD

**Issue by lihaoyi** [scala/bug#11241]
This fails to split and returns a single string:

```scala
@ "hello\rworld".linesIterator.toArray.length
res5: Int = 1
```

This is inconsistent with the JVM `String#lines: java.util.stream.Stream[String]` method:

```scala
@ "hello\rworld".lines.toArray.length
res4: Int = 2
```

The standard `java.io.BufferedReader#readLines` method:

```scala
@
val x = new BufferedReader(new InputStreamReader(new ByteArrayInputStream("hello\rworld".getBytes)))
x: BufferedReader = java.io.BufferedReader@5769e7ae

@ x.readLine()
res2: String = "hello"

@ x.readLine()
res3: String = "world"

@ x.readLine()
res4: String = null
```

Or other languages like Python

```python
>>> "hello\rworld".splitlines()
['hello', 'world']
```

Shouldn't it do the same thing?

**Comment by som-snytt** [comment]
```
scala 2.13.0-M5> "hello\n".stripLineEnd
res0: String = hello

scala 2.13.0-M5> "hello\r".stripLineEnd
"es1: String = "hello

scala 2.13.0-M5> "hello\r".stripLineEnd.length
res2: Int = 6
```

**Comment by szeiger** [comment]
Should `\r` still be recognized as a line separator today? AFAIK it was only used by the old MacOS which got replaced almost 2 decades ago. Not recognizing `\r` makes the implementation simpler and probably faster, too.

**Comment by som-snytt** [comment]
Compatibility with `String.lines` is pretty compelling.

OTOH, `a\rb` could be understood as an overstrike, and therefore one line.

[Padding of `\r\n`](https://en.wikipedia.org/wiki/Newline#History) suggests it shouldn't be a heuristic, but a mode, so that in `CRNL` mode, `\r\r\r\n` and `\r\u0000\n` are a single line separator.

When I `scalac file.scala > scala.out ; vim scala.out`, vim picks a mode and shows `^M` where scalac emits mixed output because it doesn't respect the line separator.

Since the future of scala is opinionated, it has the option of ignoring line separator and `String.lines` and solo CR.

**Comment by lihaoyi** [comment]
Not just `String.lines`, but `BufferedReader` and all that. Surely wrapping a string in a `new BufferedReader(new StringReader(s))` is simple enough in terms of implementation?

**Comment by som-snytt** [comment]
As another data point, CR is a line break for regexes, also matched by `\R`.

**Comment by adriaanm** [comment]
Could someone take this one and implement compat with `String.lines`? WWJD FTW

**Comment by som-snytt** [comment]
Rust issue 55743 covers the same territory.
