### ISSUE TITLE
@SerialVersionUID not serializable

### ISSUE THREAD

**Issue by ckchow** [scala/bug#11279]
The annotation @SerialVersionUID itself is not serializable.

**Comment by SethTisue** [comment]
I confess ignorance: does it matter whether an annotation is serializable?

**Comment by ckchow** [comment]
I'm using Apache Beam, and it seems to complain that the annotation is not serializable when I try to make a distributed collection of a class annotated with that.

**Comment by ckchow** [comment]
Maybe it's a case of the maintainer of the Beam library that I'm using should filter out annotations. Are they used for stuff at runtime?

**Comment by NthPortal** [comment]
It was my impression that Scala annotations do not exist at runtime, so there shouldn't be anything to serialise.

**Comment by lrytz** [comment]
`@SerialVersionUID` is special in that it makes the backend generate a field in the annotated class. But the annotation itself indeed doesn't end up in the classfile, other than the Scala signature, and instances don't have any reference to the annotation. So I also think it's an issue in Apache Beam. Can you check on that end, and re-open the issue here in case we need to do something?

**Comment by lrytz** [comment]
`StaticAnnotation` means it's persisted in the Scala signature, but not written to the classfile like Java annotations. `ClassfileAnnotation` was intended for that, but it was never implemented. In 2.13, we're more honest (https://github.com/scala/scala/pull/6143), `SerialVersionUID` extends `ConstantAnnotation` (which requires the arguments to be constants).
