### ISSUE TITLE
Incorrect compiler error involving auto-tupled arguments

### ISSUE THREAD

**Issue by prSquirrel** [scala/bug#11281]
```
scala> def const(x: Any): Boolean = true
const: (x: Any)Boolean

scala> const(1)
res29: Boolean = true

scala> const(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22)
res30: Boolean = true

scala> const(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23)
<console>:13: error: 22 more arguments than can be applied to method const: (x: Any)Boolean
       const(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23)
```

Arguments are auto-tupled, but error says `22 more arguments`, which is not correct.

Scala versions: 2.12.5, 2.12.7
JVM version: Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131

**Comment by NthPortal** [comment]
I think that the error is technically correct (the worst kind of correct), but I agree it's very strange and confusing.

My understanding is that because 23 arguments cannot be auto-tupled (because tuples can only have at most 22 elements), it doesn't try to tuple them, and you're left with the fact that there are 23 arguments passed to a method which takes 1, which is 22 too many.

**Comment by Jasper-M** [comment]
It's a bit strange, possibly confusing, that the error message changes after a certain threshold.

```
scala> def const(x: Any, y: Any): Boolean = true
const: (x: Any, y: Any)Boolean

scala> const(1,2,3,4)
                 ^
       error: too many arguments (4) for method const: (x: Any, y: Any)Boolean

scala> const(1,2,3,4,5)
                 ^
       error: 3 more arguments than can be applied to method const: (x: Any, y: Any)Boolean
```

**Comment by som-snytt** [comment]
The gradual message is definitely a feature.

The commit message suggests that a very long arg list is probably machine-generated.

The use case is a moderate number of parameters, a comparable number of arguments, some of which are probably named and out of order, with defaults supplying other values, so that it's difficult to tell at a glance what is missing or what does not apply.

**Comment by som-snytt** [comment]
The linked PR trusts the user to count to 22, and just reports a found and expected number of args.

Where tupling may have failed, it says so. If a tuple is expected, it reports the tuple size.

**Comment by SethTisue** [comment]
remains reproducible in 2.13.2

**Comment by som-snytt** [comment]
The improved messaging:
```
t8667.scala:37: error: too many arguments (found 3, expected 2) for method f2: (i: Int, j: Int): Int
t8667.scala:64: error: too many arguments (found 3, expected 2-tuple) for method t: (t: (Int, Int)): Nothing
t8667.scala:51: error: too many arguments (found 24, which exceeds the largest Tuple) for method movi: (x: Object): Int
    movi(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24)
```
So the "variant" help is restricted to the parentheses, and tries to give simplest clarification.
