### ISSUE TITLE
Ant and XML utilities are missing in 2.13.0-M5

### ISSUE THREAD

**Issue by lexspoon** [scala/bug#11286]
The Ant utilities and the scala-xml library are missing in 2.13.0-M5.  They were in scala-compiler.jar for M3, but they are missing in M4 and M5, and it's not obvious where else to go for them.

Were these intentional changes, or did they just fall out due to build script changes? For Ant, I have a small project using Ant, and it would be helpful to keep building it that way if that's feasible. There are a lot of little customizations in the build file in question, and it would take a few hours to bring them forward to any other build system.

For XML, it's even harder to wean off of.

**Comment by SethTisue** [comment]
yes, intentional:

* scala-xml: see https://github.com/scala/scala/pull/6436. scala-xml has a been a separate JAR since 2.11.0, but remained a dependency of scala-compiler in 2.11 and 2.12 for accidental rather than essential reasons; the dependency was finally cut in 2.13. you'll now need to explicitly add the dependency to your build
* ant: see https://github.com/scala/scala/pull/6255. the removed code could be resurrected by the community, similarly to how Maven and Gradle support for Scala are community-maintained
