### ISSUE TITLE
Repl 2.13 versus 2.12 API - do not change signature of `beQuietDuring`

### ISSUE THREAD

**Issue by Sciss** [scala/bug#11316]
This breaks source compatibility unnecessarily:

Before:
https://github.com/scala/scala/blob/2.12.x/src/repl/scala/tools/nsc/interpreter/IMain.scala#L211

```scala
def beQuietDuring[T](body: => T): T 
```

After:
https://github.com/scala/scala/blob/2.13.x/src/repl/scala/tools/nsc/interpreter/Interface.scala#L43

```scala
def beQuietDuring(body: => Unit): Unit
```

(type of `body` is swallowed)

**Comment by SethTisue** [comment]
maintaining source compatibility for the REPL internals between releases isn't really a goal. this is the kind of thing that can change even in a minor release, let alone a major release.

if working around this is somehow causing real difficulty, let us know (and explain why), otherwise it falls under "sorry but oh well"
