### ISSUE TITLE
`AssertionError` on anonymous class with refinement type and missing type parameters

### ISSUE THREAD

**Issue by propensive** [scala/bug#11337]
The following combination causes a compiler crash in typer with Scala 2.12.1:

```scala
trait Foo[T]
object Foo {
  val foo: Foo[Any] { type Bar = Any } = new Foo { def baz(): Any = () }
}
```

I think the correct behavior should be to just output the error regarding the missing parameters on `new Foo`, and give up. Full output is here: [error.txt](https://github.com/scala/scala-dev/files/873808/error.txt).

The crash also appears with 2.12.0, but not 2.11.8.

**Comment by SethTisue** [comment]
someone want to check if this 1) should remain open and 2) isn't a duplicate?

**Comment by joroKr21** [comment]
It's still a problem. There are 5 other issues about `foundType is Erroneous`:
#10803, #10015, #10003, #9960, #1472

**Comment by joroKr21** [comment]
```scala
tree.tpe = <error>{}
tree.tpe.isErroneous = false
```
:thinking:

**Comment by SethTisue** [comment]
Dotty:

```
  |                                   found:    Object with Foo[Nothing]{...}
  |                                   required: Foo[Any]{Bar = Any}
```

**Comment by joroKr21** [comment]
But dotty doesn't issue an error about `trait Foo takes type parameters` because it has type inference on `extends` (I think there's an issue about that but can't find it). The problem is that:
```scala
new Foo { def baz(): Any = () }
```
desugars to something like:
```scala
{
  class anon$1 extends Foo { // here dotty infers Nothing but scalac doesn't try to
    def baz(): Any = ()
  }
  new anon$1
}
```
Instead `anon$1` ends up having an error type as a parent as in `class anon$1 extends <error>`. But `TypeMap` and by extension `isErroneous` don't look in the parents.

However `AdaptTypeError` exposes the parents:
https://github.com/scala/scala/blob/284a9c03c650c76e2b5295fee5c03565bcdf5246/src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala#L215

**Comment by joroKr21** [comment]
I believe we should not try so hard to construct a meaningful type mismatch error for an anonymous class with erroneous definition.
