### ISSUE TITLE
Double.NaN.signum returns 0

### ISSUE THREAD

**Issue by kamilkloch** [scala/bug#11386]
```scala
println(java.lang.Math.signum(Double.NaN)) //NaN
println(scala.math.signum(Double.NaN)) //NaN
println(Double.NaN.signum) //0
```
What is the rationale? `RichDouble.scala` line 48:
```scala
override def signum: Int               = math.signum(self).toInt  // !!! NaN
```

**Comment by sjrd** [comment]
> I think a fix could target 2.12.x

I don't think so. The signature needs to be changed to returning a `Double`, which is definitely not a binary-compatible change.

**Comment by SethTisue** [comment]
in that case, we should rush a fix in. volunteer?

**Comment by kamilkloch** [comment]
I'll give it a shot.

**Comment by kamilkloch** [comment]
`scala.runtime.ScalaNumberProxy.signum` cannot return `T` - as a result, `scala.runtime.RichByte.signum`would have to return `Byte`. Any ideas?

**Comment by Ichoran** [comment]
I think the existing behavior, weird though it is, is as correct as you can get with a generic interface that doesn't explicitly provide for `NaN` eating all values and always returning false.  You run into a similar problem when considering using `compare` to order values based on `NaN`.  You would think that `a < b` if and only if `a.compare(b) < 0`.  Also, `a > b` if and only if `a.compare(b) > 0`.  But throw `NaN` into the mix and there's no way to achieve this.

I think the way to fix this is to leave the NumberProxy stuff alone, at a lower priority, and to explicitly have a higher-priority `signum` extension method for `Double` that gives the correct behavior for `Double`.  You end up equally confused when working generically but you _always_ end up confused when working generically; this at least recovers the expected behavior when you know you have a `Double`.

**Comment by kamilkloch** [comment]
@Ichoran Pls take a look.

**Comment by szeiger** [comment]
It's hard to imagine a correct Int-valued signum function for floating point numbers that is consistent with signum for integral types. The Java implementation always keeps the sign of the original number while converting all valid non-zero numbers to 1. This means that `abs(x) * signum(x)` is identical to `x` even in corner cases (+0 vs -0, +Inf vs -Inf, and even the most esoteric one, +NaN vs -NaN).

> scala.runtime.ScalaNumberProxy.signum cannot return T - as a result, scala.runtime.RichByte.signumwould have to return Byte

That seems fair enough. `min`, `max` and `abs` also return `T`, why should `signum` be any different?

**Comment by eed3si9n** [comment]
I have an alternative PR here that returns `T` - https://github.com/scala/scala/pull/7861
Much like `min` and `max`'s implementation in RichShort, RichDouble etc I am delegating `Int`, `Long`, `Float`, and `Double` handling to the corresponding `scala.math.signum(...)`, and using `scala.math.signum(Int)` for `Short`, `Char`, and `Byte`. This hopefully keeps most consistency with Java and `scala.math.*`.
