### ISSUE TITLE
Wrong answer coming

### ISSUE THREAD

**Issue by supreet11agrawal** [scala/bug#11394]
I came across an issue whiling going through a tutorial
```
scala> def bigger(o:Any): Any = {
     | o match{
     | case i: Int if i<0 =>i-1
     | case i: Int =>i+1
     | case d: Double if d<0.0 => d- 0.1
     | case d: Double =>d+0.1
     | case text: String => text + "s"
     | }
     | }
bigger: (o: Any)Any

scala> val a = bigger(5)
a: Any = 6

scala> val a = bigger(5.3)
a: Any = 5.3999999999999995

scala> val a = bigger(-.3)
a: Any = -0.4

scala> val a = bigger(.3)
a: Any = 0.4

scala> val a = bigger(4.3)
a: Any = 4.3999999999999995
```
Maybe it's wrong. But since I am new so I decided to put it here.
Ran it in sbt console
OS - Ubuntu 18.04

**Comment by SethTisue** [comment]
@supreet11agrawal welcome! we ask that questions like this go here: https://users.scala-lang.org . when you're new to the language, it's highly likely that any unexpected behavior you encounter is actually expected, rather than being a new, previously unreported bug.

as for the content of the report, this is expected behavior according to IEEE 754. you will get the same answers in Java, JavaScript, and other languages. for example, in JavaScript:

```
> 4.3 + 0.1
4.3999999999999995
```
