### ISSUE TITLE
Unused warning for existentials flag import

### ISSUE THREAD

**Issue by johanandren** [scala/bug#11467]
We're trying to start failing on compiler warnings in Akka and discovered the following (having to support both 2.12 and 2.13):

In 2.12 the compilation fails on using existentials without import but when adding that it fails on 2.13.0-M5 claiming the import is not used.

```
// required on 2.12, fails on 2.13 
import scala.language.existentials

trait OtherType[T]
case class Existensialism(field: OtherType[_])
```

Complete reproducer project:
https://github.com/johanandren/compiler-warnings-repeater

(We are fine just not using existentials in the actual code, but @SethTisue asked me to ticket)

**Comment by SethTisue** [comment]
What I'm seeing is that the import is required in 2.11 but not 2.12 or 2.13.  That seems to me like a progression in 2.12. (Why? The error refers to `inferred existential type Option[OtherType[_$1]] forSome { type _$1 }, which cannot be expressed by wildcards`, not the use of `Option`, that's because of the generated unapply method. Since it's a generated method, the 2.11 warning is inappropriate.)

And since the import isn't required in either 2.12 or 2.13, it seems like actually a progression in 2.13 that you get an unused warning.

So I think there is no bug here, just a dilemma about how to get warning-free cross-compilation, which (unless you use Scala-version-specific sources) is often but not always possible.

I would suggest omitting the import and using `-language:existentials` in your `scalacOptions` on 2.11 only, or omit `-feature` and/or `-Xfatal-warnings`.

**Comment by SethTisue** [comment]
@som-snytt do you agree with this analysis?

**Comment by johanandren** [comment]
Thx for looking into it @SethTisue

**Comment by SethTisue** [comment]
> We're trying to start failing on compiler warnings in Akka

(You might consider aiming at this only for a single Scala version, or only two of your three Scala versions.)

**Comment by SethTisue** [comment]
In some circles, it's rumored that having entirely warning-free cross-compilation between three major Scala versions is a special ninja power wielded only by @sjrd, not attainable by other humans without special dispensations from the gods and/or the devil.

**Comment by sjrd** [comment]
Three major versions? You underestimate me. The 0.6.x branch does that all the way back to 2.10.2 and up to the latest 2.13.x HEAD. 😆

**Comment by som-snytt** [comment]
As mentioned on the ticket https://github.com/scala/bug/issues/6541 adding `-Xsource:2.12` to the 2.11 options is a workaround for the compiler bug. No feature import is needed.

**Comment by SethTisue** [comment]
> adding -Xsource:2.12

(but I'd be a bit worried that might have other, unintended side effects)

**Comment by som-snytt** [comment]
I had the same thought, but I was too lazy to follow up. Now a quick grep shows that there are two other bug fixes that hinge on the flag:

Implicit import shadowing bug:
https://github.com/scala/scala/pull/4118

Clashing synthetic apply:
https://github.com/scala/scala/pull/5846

It also affects the default for `-Xxml:coalescing`. I was also too lazy to find the release notes to see if this info is conveniently summarized.
