### ISSUE TITLE
mutable ArrayBuffer constructor throws on negative size

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/bug#11482]
`new scala.collection.mutable.ArrayBuffer(-1)` throws `NegativeArraySizeException` in 2.13.0-RC1, but runs fine in 2.12.x

**Comment by SethTisue** [comment]
seems like a progression rather than a regression?

**Comment by martijnhoekstra** [comment]
Not sure -- I couldn't find documentation of the change or its reasoning. It seems marginally likelier to me that it'll break peoples code than that it'll catch bugs. 2.12 sets the minimum size of the underlying array to at least 1. It has been that way at least since the old collections were new.

Maybe the bug is that the constructor is undocumented?

**Comment by som-snytt** [comment]
It ought to throw `IllegalArgumentException`.

**Comment by Ichoran** [comment]
There is no reason an advisory parameter like this should throw an exception rather than implementing the most sane behavior under the circumstances.  Something like `take(-1)` is much more likely to be an error of logic than this is, yet we _advocate_ for the safety of `take`.

So this should be regarded, unreservedly, as a bug.  And fixed.

**Comment by som-snytt** [comment]
WWJD? `ArrayList` throws.

**Comment by Ichoran** [comment]
> WWJD? `ArrayList` throws.

This is entirely within character _for Java_, as `ArrayList` consists almost entirely of brittle low-level methods.

**Comment by som-snytt** [comment]
Brittle as in peanut?
```
scala> val buf = new ArrayBuffer
buf: scala.collection.mutable.ArrayBuffer[Nothing] = ArrayBuffer()

scala> buf.remove(0, -1)
java.lang.IllegalArgumentException: removing negative number of elements: -1
  at scala.collection.mutable.ArrayBuffer.remove(ArrayBuffer.scala:204)
  ... 29 elided
```
Normally, I would suggest "fluent" API wants to be forgiving, but `Unit` methods and certainly constructors should be inclined to fail. Constructors especially should result in a well-defined state, but is `new ArrayBuffer(-1)` sized to zero or the default?
```
scala> val buf = new ArrayBuffer(42)
buf: scala.collection.mutable.ArrayBuffer[Nothing] = ArrayBuffer()

scala> buf.remove(-1)
java.lang.IndexOutOfBoundsException: -1 is out of bounds (min 0, max -1)
  at scala.collection.mutable.ArrayBuffer.checkWithinBounds(ArrayBuffer.scala:91)
  at scala.collection.mutable.ArrayBuffer.remove(ArrayBuffer.scala:188)
  ... 29 elided
```

**Comment by martijnhoekstra** [comment]
The 2.12 collections set the underlying array size to `max(arg, 1)`, which seems like a reasonable size, but I have no strong preference between 0, 1 or default (or, indeed throwing an `IllegalArgumentException`)

The `remove(-1)` behaviour sounds correct to me, though that out of bounds message is confusing, and probably needs to be special-cased for when the collection is empty.

The `remove(0, -1)` behaviour sounds like something that could be argued about, throwing andnot removing anything both seem plausible things to do.

These are both significantly different from the constructor argument in that the constructor argument is only a bookkeeping argument for which an unexpected value shouldn't impede normal handling. I guess you could argue that if the argument is important enough for the constructor to exist, out of range values should be important enough to be errors, and if you don't care enough about the value you pass in out of bounds values, maybe the entire things shouldn't exist/be used.

I'm not going to argue any of those points, I'm just reporting the change in behaviour

**Comment by Ichoran** [comment]
> Normally, I would suggest "fluent" API wants to be forgiving, but `Unit` methods and certainly constructors should be inclined to fail. Constructors especially should result in a well-defined state, but is new ArrayBuffer(-1) sized to zero or the default?

The array-expanding math is simplest if zero is forbidden, so it would be 1.

Constructors and `Unit` methods have a responsibility to do the very best job they can to do something sane, and throw exceptions only as a last resort.  Sensible defaults, unless used in a context where it essential to die if doing anything other than exactly what you asked for, are one way to accomplish sanity.  Alternatively, you can divide your API in to a "brittle low-level" part that throws exceptions if any i is missing its dot, and a "forgiving high-level" part that does as close to the right thing as practical.  Overwhelmingly the collections library is the latter type, so in ambiguous cases I'd advocate for the latter behavior.

You can't `remove` _and return back_ something that isn't there--so trying should be an exception, yes--but asking to remove less than nothing should, almost surely, just be interpreted as a request to remove nothing.

**Comment by diesalbla** [comment]
I am not sure if this should be regarded as a bug, but rather as a design feature of the library. 

On the one hand, this breaks a basic intuition of the `ArrayBuffer` class. Much like an `ArrayList` from the Java standard library, an `ArrayBuffer` is expected to act as a wrapper around an array, with the special logic to insert an array and to resize and move elements when an array grows full. From the point of view of transparency, the exceptions of this class regarding indices  should be just as to those of any array: if we ask or assign at a position with negative or over-the-top index, we should throw an `IndexOutOfBoundsException`. Likewise, if we as to create an array buffer of negative (or zero) size, we should throw an exception.

I understand that the idea of a forgiving API sounds nice, but I think it would be a mistake.

The worst kind of software error is not the one that throws an exception. It is the one that moves undetected and unchecked all the way to the database, or to any core component, where it can  cause to the data, or to other assets, damage beyond all repair. To my view, any program that, by some curious set of circumstances, ends up issuing a call to create a new array (buffer) of negative size, is more likely to be the result of a programmer's error, or foul intentions, that a deliberate design choice. That is why we should keep throwing an exception in this case.

**Comment by Ichoran** [comment]
@diesalbla - Can you please explain why this reasoning does not also hold for `take` and `drop`?

(This is different to assignment, as assigning out-of-bounds has no sane alternative.  In particular, the invariant of `x(i) = a; x(i) == a` cannot possibly be upheld if invalid assignments are elided.  One could say instead that the invariant is `(i >= 0 && i < x.length) implies { x(i) = a; x(i) == a }`, but it's much harder to work with this one than the "if I put something somewhere, I can get it back from the same place" version.)

As an aside, if bad data due to incorrectly allocating an array buffer size is in any danger whatsoever of causing "damage beyond all repair" to one's data, it's probably a good idea to look into a more robust backup solution.

**Comment by diesalbla** [comment]
@Ichoran Since you mention it, I am not sure that `take` or `drop` should accept a negative number of  elements to take or drop. Accepting a number larger than the length is a bit of a different story, of course.

> As an aside, if bad data due to incorrectly allocating an array buffer size is in any danger whatsoever of causing "damage beyond all repair" to one's data, it's probably a good idea to look into a more robust backup solution.

I am sorry if the particular common example did not made the general point. Allow me to restate it:   library calls that are more likely caused by a programmer's errors (like asking for negative array sizes) should be defended against. You are more likely to benefit programmers by giving them exceptions, than from letting a very probably wrong system work unchecked.

**Comment by Ichoran** [comment]
@diesalbla - Well, perhaps they shouldn't.  But they do.  So does slice; you can ask for `slice(2, 1)` for example, and it won't explode, even though a negative-length slice is meaningless.

So, what is going on?  Why bother allowing all this imprecision?

I think the answer is because very often the attention to detail is meaningless.  Having to specify bounds which are wrong and then panicking of you fail to meet them is a pointless exercise much of the time.  If you are going to manually pick off one items (if available) and then want the rest to go into a buffer, it's really easy to write `val buffer = new ArrayBuffer[Foo](n - 1)`.  it's totally correct.  You _haven't_ totally handled all the logic about "what if n < 1" because _it doesn't matter_ at this point.  Later on you'll have to check your sizes _anyway_, so at this point you're best off just getting the clear obvious logic right, and letting the corner cases not destroy everything.

Wasting attention on getting irrelevant bounds exactly right results in a less powerful language that can be used for smaller problems.

There are times when precision is necessary and desired, but a lot of times it isn't important, or only one bound is important.  People can always add assert statements.  They can't easily catch exceptions when they know some boundary case doesn't matter but the library has decided it better throw them just in case they didn't think through in `n - m` whether `m` could ever possibly be larger than `n`.

**Comment by som-snytt** [comment]
I appreciated diesalba's eloquent comment yesterday.

I don't have a strong opinion, but I just remembered contributing a fix of the `arg max 0` ilk, maybe for https://github.com/scala/bug/issues/9936 which was wrong behavior for `indexOf(x, from = -1)`. Clearly I'm inured to robust handling rather than throwing; but the bug suggests early validation is an ethos.

In the case of `indexOf`, you get back an `index >= from` if the element is found. Does `from` itself have to be a valid index? That can only mean valid for the given collection, since an empty has no valid index. Or does "index" always mean non-negative? Suppose I just create an `ArrayBuffer` with the value from `indexOf`; if that value is `-1`, I just mean I want a small array which I probably won't put much into. `new ArrayBuffer(xs.indexOf(x))`. So I agree this should not throw. This is the same as Ichoran's last example, except that it's obvious that `indexOf` represents an index, even the sentinel value `-1`.

**Comment by diesalbla** [comment]
@Ichoran I have already laid out the main arguments that I thought are worth considering for this choice. I am happy to leave it to those maintaining the library to do what they find best.

**Comment by SethTisue** [comment]
just briefly: I consider `take` and `drop` exceptions. they are forgiving because it's an incredibly useful and consciously made API design choice, not just by blind compliance with some policy of forgiving-ness being the default.

I think unforgivingness is the right default; code should blow up on invalid input.

I also have a general intuition that in a higher-level API, it makes more sense to be forgiving, and in low-level code, you really want to be strict. Forgivingness should be pushed to the outer edges of the program. In the context of the collections API, `take` and `drop` seem like high level calls to me, while the `ArrayBuffer` constructor is super low level stuff.

but idk, it's not terrible either way

**Comment by eed3si9n** [comment]
If we truly want to fix the logical errors in some unknown code base, that way we should approach this should be introducing `NonNegativeInt` type, not introducing a _new_ runtime error that the user may not hit until it's too late.

**Comment by dwijnand** [comment]
I'm persuaded by @Ichoran's argumentation (after being in the other camp).  To use @diesalbla's worst-case scenario, I'm having difficulty coming up with how creating an array of size 1 rather than a thrown runtime exception could cause damage beyond all repair to data or other assets.

**Comment by diesalbla** [comment]
@dwijnand Attempting to create the array, in itself, would not **cause** damage. My point was, for a  program to do such a strange thing, is probably a sign of something else being wrong.

**Comment by som-snytt** [comment]
Because none of my clothes fit anymore, I really need a `damage beyond all repair` t-shirt. I would also take a cap with `a bit late to this conversation`. I think dbar may be serviceable to replace fubar.

**Comment by martijnhoekstra** [comment]
I can imagine it's useful in a `take` or `splitAt` operation that needs buffering. There are lots of ways I can imagine you might want a buffer that's probably not going to be bigger than x, and calculating x can get you below 0.

**Comment by LPTK** [comment]
@eed3si9n First-class compiler support for a `Nat` type (opaque wrapper over `Int`) would be a game changer IMHO. Too bad it's too late to introduce it in 2.13 along with the new collections.

**Comment by ashawley** [comment]
Should this change have been caught by the collection laws test suite?  

Are they not testing `new`?  Is it only testing positive values?  Seems like it missed one or both of these scenarios.

**Comment by Ichoran** [comment]
Right now constructors are not tested by collection-laws.  Given the non-uniformity of the constructors, that's better done in some other test suite.
