### ISSUE TITLE
[RFC] using mkdocs to replace jekyll for spec.

### ISSUE THREAD

**Issue by sequencer** [scala/bug#11493]
The pdf issue have struggled for a long time :(
How about abandon jekyll, porting whole docs to mkdocs by python, which support pandoc well, and easy to call a latex backend.
jekyll is out of date in such modern case.
I think it's not hard to port.

**Comment by SethTisue** [comment]
fwiw, the PR that adds PDF generation is really verrrrry close to crossing the finish line. I haven't forgotten about it and I plan to do the last little bit after Scala 2.13.0 is out. help with it would be welcome

I don't enough enough about mkdocs to comment on your proposal. I'm closing this ticket since it isn't really the kind of thing we use scala/bug for
