### ISSUE TITLE
Scala 2.13.0-RC1 - revert ControlThrowable to a marker trait (cross compilation not possible)

### ISSUE THREAD

**Issue by Sciss** [scala/bug#11494]
[This commit](https://github.com/scala/scala/commit/bd368a7e336b99d299681c96415fde75b025a92a#diff-a0a615b38d66f1e6405e81cdc4c861e1) is problematic, it breaks code:

```scala
object RollbackError extends Error with ControlThrowable
```

This compiles from 2.10 through 2.13.0-M5 but breaks in 2.13.0-RC1 because (why?) `ControlThrowable` no longer is a mixin trait.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/7413, @som-snytt @lrytz?

**Comment by som-snytt** [comment]
Motivation on the ticket https://github.com/scala/bug/issues/11116

**Comment by sjrd** [comment]
The breakage was a known issue at the time the change was done. We had to change Scala.js' `UndefinedBehaviorError` because of that. See https://github.com/scala-js/scala-js/commit/03faf11c670ed0c8eb973e792a771a91c265c320 for an example of the changes you might want to apply in your code.

**Comment by Sciss** [comment]
So is `java.lang.Error` not considered fatal? Cause if I simply drop the `ControlThrowable` mixin:

```scala
object RollbackError extends Error /* with ControlThrowable */

def test(bla: => Unit) = try {
  bla
  "nothing happened"
} catch {
  case util.control.NonFatal(ex) => "caught"
}

test(throw RollbackError)  // caught!
```
(under Scala 2.12). From the Java API on `java.lang.Error`:

> An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch.

So isn't the behaviour of `NonFatal` thus wrong?

**Comment by som-snytt** [comment]
`NonFatal` does not mean `NonNotSomethingYouShouldCatch` to imply go ahead and catch it.

[`NonFatal`](https://github.com/scala/scala/blob/2.13.x/src/library/scala/util/control/NonFatal.scala#L41) has a bit of history about what it detects. A better name might be `NonOperational` to mean the throwable does not have "operational" semantics as opposed to business logic.

Flow control should be a `ControlThrowable` and not an `Error`, but obviously I'm not conversant with the particular needs for a `RollbackError`. Is that when a Little League catcher tries to get the ball back to the pitcher? That's clearly operational, which is why the pitcher never catches it.

I think Seb was recommending his build.sbt and not his choice of Error to extend? Or I may be wrong about his suggestion. Letting `Rollback` masquerade as a `VMError` doesn't sound right to me, I don't really have an opinion without trying it out.

**Comment by NthPortal** [comment]
To summarize from the motivation from various discussions (including on the ticket @som-snytt linked): we wanted to disable exception suppression for `ControlThrowable` for several reasons, and could not do so without making it a class.

The new intended use is to directly extend `ControlThrowable; in your case that would be `object RollbackError extends ControlThrowable` (or even just `Rollback`, as it's not really an error).

The reason for `Error` not being matched by `NonFatal` despite Java's documentation is that unfortunately, not all `Error`s are actually fatal (see #10166 for an example). It would be nice if they were, but alas.

**Comment by som-snytt** [comment]
I'll double-check that the migration info is available in the release notes, which might mean amending the PR description. The [scaladoc](https://scala-lang.org/files/archive/api/2.13.0-RC1/scala/util/control/ControlThrowable.html) is not overly verbose but hits a few points. I'd forgotten "can't catch a break" in the example. It adds: "As a convenience, NonFatal does not match ControlThrowable." NonFatal also mentions CT. However, the phrase "harmless Throwable" is an oxymoron.
