### ISSUE TITLE
String interpolation allows command execution?

### ISSUE THREAD

**Issue by barhaterahul** [scala/bug#11505]
Hi,
During security code review , I found that some one is passing user input to ${ } to make use of string interpolation. After little digging into this syntax, I observed that OS commands can be executed if we pass this to  interpolation,
```
println(s"1 + 1 = ${sys.runtime.exec("ls")}")

```
Is this a expected behaviour?? or a security issue in interpolation.I see there no mention of this in SIP-11.Or guidance on how to use is safely.

**Comment by raboof** [comment]
Don't take my word to be authorative, but I would say this is expected behavior.

You are referring to 'user input', but I do not see any user input in your example. `s"1 + 1 = ${sys.runtime.exec("ls")}"` is not a string, and could not have come from user input.

The `sys.runtime.exec("ls")` part is indeed evaluated, but it is part of the code, written by the developer at compile time, and cannot be passed in as user input to execute arbitrary code at run time.

Of course if you would write `sys.runtime.exec(someVariableWithUserInput)` that would be a bad idea and a security issue, but that is the case whether or not it is part of an interpolated string.

**Comment by barhaterahul** [comment]
Ok, what I meant was,
a parameter which is user input say for e. g.
testParam - > controlled by end user of web app not developer,
and we interpolate like
```
println(s"1 + 1 = ${testparam}")
```
and user pass testparam value as 
```
sys.runtime.exec("ls")  
```

**Comment by raboof** [comment]
so `testparam` is a variable of type `String`. Interpolating `s"1 + 1 = ${testparam}"` will take the string value of the `testparam` expression and insert it into the string. 

That means when the testparam value is "`sys.runtime.exec("ls")`", the resulting string will be "`1 + 1 = sys.runtime.exec("ls")`". It will never be evaluated - in fact, evaluating arbitrary strings is not something ver easily possible in Scala even if you wanted to.

You can relatively easily try this out online with 'scastie', by pasting the following program:

```
val testparam: String = """sys.runtime.exec("ls")"""
println(s"1 + 1 = ${testparam}")
```

into https://scastie.scala-lang.org/ and hitting 'run'.

**Comment by barhaterahul** [comment]
Thanks that make sense. :)

**Comment by SethTisue** [comment]
please ask questions on https://users.scala-lang.org
