### ISSUE TITLE
Spurious "cannot be checked at runtime" in latest 2.12.x (regression wrt. 2.12.8)

### ISSUE THREAD

**Issue by sjrd** [scala/bug#11534]
Trying to build the latest 0.6.x branch of Scala.js with the latest 2.12.x, I get a warning that I do not get with 2.12.8.

Repro:
```
$ git clone git@github.com:scala-js/scala-js.git
$ cd scala-js
$ git checkout fa02c74
$ sbt
> set resolvers in Global += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"
> ++2.12.9-bin-ae27fe9
> compiler/compile
[...]
[warn] compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala:4421: The outer reference in this type test cannot be checked at run time.
[warn]         case JSUnaryOpMethodName(code) if argc == 0 =>
[warn]                                 ^
```
The line mentioned is here:
https://github.com/scala-js/scala-js/blob/fa02c745a64b869127b8cb68d594f5ca6c1b2d4e/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala#L4421

The warning was not reported by 2.12.8.

Note that the next case with `JSBinaryOpMethodName`, which is extremely similar, does not emit a warning.

A similar problem exists on our `master` branch (commit  https://github.com/scala-js/scala-js/commit/9f4f59b13051d9dfcc2fc34f6c37ecd9ac1ff69d), where this becomes an *error* because we have `-Xfatal-warnings`.

**Comment by eed3si9n** [comment]
It's 2 weeks before 2.12.9, but it doesn't look like there's an activity on this, so I am bumping this to 2.12.10.

**Comment by lrytz** [comment]
This is caused by one of the commits in https://github.com/scala/scala/compare/8257b83...ae27fe9. With the parent merge commit (8257b83) the warning doesn't appear. @retronym

**Comment by Jasper-M** [comment]
Not a clue if that's the cause&mdash;or how it could possibly be the cause&mdash;but it seems that `name.newName(str)` no longer retains the "cachedness" of the `Name`.

**Comment by retronym** [comment]
Here's a smaller repro:

```scala
// scalac: -Xfatal-warnings -unchecked
object Test1 {
    val g: scala.tools.nsc.Global = ???
    import g._
    def test(sym: Symbol) = sym.name match {
        case _: TermName  =>
    }
}
```

[`ExplicitOuter` opts](https://github.com/scala/scala/blob/515916c42f8f2f5c476ffabd6774e5a903feda10/src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala#L463) not to emit an outer test anymore because although `TermName` has an outer accessor, it is now a final class. This is somehow tied up in the morass of #4440.

Ideally the compiler would be smart enough to avoid the runtime test in this case as we statically know that the prefixes are the same. But `sym.name` has an exotic type: `sym.NameType` an abstract type defined by ` >: Null <: Test1.g.Name`.  The code that tries to statically unify the prefixes doesn't [deal with this correctly](https://github.com/scala/scala/blob/515916c42f8f2f5c476ffabd6774e5a903feda10/src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala#L352).
