### ISSUE TITLE
Main Page of Repo can confuse new contributors

### ISSUE THREAD

**Issue by bomberm** [scala/bug#11610]
If a new contributor is unfamiliar with github and wishes to contribute to scala, the lack of an 'issues' tab on the main repo page can be confusing and discourage involvement. While the link to 'submit issue' can be found in the readme.md, this is not a common workflow.

**Comment by SethTisue** [comment]
The split between scala/bug and scala/scala is unfortunate, but it’s also not clear how it can be remedied. Do you have a suggestion?

**Comment by nogurenn** [comment]
I'm still new to contributing, and even have very sporadic presence due to real life events, so I basically read the entire scala/scala readme. Right after the `Welcome!` header is `How to contribute`, and I immediately started reading that section. My point is new contributors are likely going to look for the documentation on contributing instructions instead of just looking for an Issues tab. I'm wondering about two things that can be touched, and both be implemented.

1. Explicitly say that the scala/scala issues reside in scala/bug, while PRs to those issues will be directed to scala/scala. Something that makes the current structure explicit.
2. See the screenshot below. We could change the highlighted text to something like "For contributors and bug reports, see scala/bug".
<img width="679" alt="Screen Shot 2020-05-23 at 3 44 27 AM" src="https://user-images.githubusercontent.com/15997393/82704456-2789c300-9ca8-11ea-8618-6340310db106.png">
I actually think people rarely notice this part of the github UI, so it might be better to drill down on making the repo structure and workflow explicit in the readme for both bug reports and general contributions.

**Comment by nogurenn** [comment]
Would a photo/diagram suffice? I want to try making a simple one, but to be honest, I don't really see photos in any of the scala readme docs. Makes me think it's a conscious decision not to have photos?

**Comment by nogurenn** [comment]
I'll work on it the soonest today/tomorrow.
