### ISSUE TITLE
scala.util.hashing.MurmurHash3 produces different outputs on 2.12 and 2.13

### ISSUE THREAD

**Issue by pshirshov** [scala/bug#11646]
The following code 

```
  def hash(bytes: Array[Byte]): Array[Byte] = {
    BigInt(MurmurHash3.arrayHash(bytes)).toByteArray
  }
  hash("abc".getBytes(StandardCharsets.UTF_8))
```

produces different output on 2.12 and 2.13. This is not something expected to happen. In case the implementation is considered unstable/incompatible with others it must be explicitly stated in the documentation.

**Comment by Ichoran** [comment]
I think this is a documentation issue--hashes of this nature (fast, non-cryptographic) tend to evolve rapidly and shouldn't be relied upon to be the same from version to version (not even in point releases!) because annoying weaknesses are often detected and fixed, and you don't want to be (dangerously) tied to old problematic versions for a long time.

Also, it would be good to have a stable (if perhaps deprecated) version that gives you a guaranteed algorithm, even if it is weak.  But that's a longer-term fix.

In the short run, assuming that the algorithm matches what it's supposed to, we should just fix the documentation to explain that hashes can't be relied upon across versions, with a brief note about why.  (I think for people who work seriously with hashing this would be the expectation, but a lot of people use hashes without becoming hashing experts, and we should help them out.)

**Comment by pshirshov** [comment]
I agree, documentation fix would work. At least it will allow people to avoid unnecessary confusion.

**Comment by nogurenn** [comment]
I can write something concise for this, but for completion, are there any other types that deserve clarification? I have zero knowledge of hashing algorithms to be able to know this specific nuance for documentation.

**Comment by SethTisue** [comment]
@nogurenn `scala.util.hashing` also has `ByteswapHashing`, but it isn't used anywhere, not sure if people are using it elsewhere. it's not worth worrying about IMO
