### ISSUE TITLE
Case class private constructor is accessible from Java

### ISSUE THREAD

**Issue by DieBauer** [scala/bug#11729]
When creating a case class with a private constructor, I still can create an instance from Java. 

```scala
case class MyCaseClass private(a: Int)
```
calling from java: 
```java
    final MyCaseClass myCaseClass = new MyCaseClass(1);
```
just works. Which is not what I'd expect. 

When doing the same exercise with a regular class
```scala
class MyClass private(a: Int)
```
calling from java: 
```java
    final MyClass myClass = new MyClass(1);
```
I get compilation errors, as expected. 

When accessing the constructors in Scala both give an compilation error: 
```scala
new MyCaseClass(1)
new MyClass(1)
```

Reproducer: 
https://github.com/DieBauer/scala-private-case-class 
`sbt +compile`

```
java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

**Comment by lrytz** [comment]
This is not avoidable because the synthetic `apply` method in the companion object needs to be able to call the constructor.

```
scala> :se -Vprint:typer

scala> case class C private (x: Int)
        case class C extends AnyRef with Product with Serializable {
          private def <init>(x: Int): C = {
            C.super.<init>();
            ()
          };
       }
        <synthetic> object C extends scala.runtime.AbstractFunction1[Int,C] with java.io.Serializable {
          case <synthetic> def apply(x: Int): C = new C(x);
        }
```

For methods other than the construcutor, when the Scala compiler needs to make them accessible, it changes the name to include some synthetics. That's however not possbile for the constructor.

So probably this is a won't-fix.

**Comment by som-snytt** [comment]
Also `C(42)` is rewritten to `new C(42)` everywhere. snippy:

```
$ scala -Vprint:typer,refch
Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 11.0.3).
Type in expressions for evaluation. Or try :help.

scala> :pa -raw
// Entering paste mode (ctrl-D to finish)

package p { case class C private (c: Int) }

// Exiting paste mode, now interpreting.

scala> p.C(42)
[[syntax trees at end of                     typer]] // <console>
        private[this] val res0: p.C = p.C.apply(42);

[[syntax trees at end of                 refchecks]] // <console>
        private[this] val res0: p.C = new p.C(42);
```

**Comment by DieBauer** [comment]
Thanks @som-snytt @lrytz for the explanations! 

@som-snytt I'm not sure what you mean with your edit. Is this issue still relevant or shall I close it?

**Comment by som-snytt** [comment]
Let's leave this open but `s/Java/REPL`. In my REPL example, it still rewrites `C.apply` to `new C`.

Actually this problem is identified [already](https://github.com/scala/scala/pull/4675#issuecomment-126587701).

I wonder if they can fix the visibility issue by making companions nestmates under JDK11. But I guess close this for now.
