### ISSUE TITLE
BigDecimal plus operator behavior change between scala 2.13 and 2.12 on big numbers

### ISSUE THREAD

**Issue by ghostbuster91** [scala/bug#11764]
The following code in scala 2.12.10 :
```
(10 to 126).foreach { n =>
      val x = BigDecimal(10).pow(n) + BigDecimal(0.1)
      println(s"n: $n result: ${x.bigDecimal.compareTo(BigDecimal(10).pow(n).bigDecimal)}")
}
```
produces expected results:
```
n: 10 result: 1
n: 11 result: 1
n: 12 result: 1
...
n: 126 result: 1
```
for all `n`s from the range.

Running the same code in scala 2.13 gives us:
```
n: 28 result: 1
n: 29 result: 1
n: 30 result: 1
n: 31 result: 1
n: 32 result: 1
n: 33 result: 0
n: 34 result: 0
n: 35 result: 0
n: 36 result: 0
n: 37 result: 0
n: 38 result: 0
```
All results for n starting from 33 up to 126 are equal to 0.

**Comment by plokhotnyuk** [comment]
Since 2.13.x Scala does not ignore the math context (that is MathContext.DECIMAL128 by default) for `+`, `-`, and other operations:
https://github.com/scala/scala/commit/ace11c068b7a0ec67b70e67da465da23277e1287

W/A is to set desirable value for the math context explicitly:
```
(10 to 126).foreach { n =>
      val x = BigDecimal(10, java.math.MathContext.UNLIMITED).pow(n) + BigDecimal(0.1,  java.math.MathContext.UNLIMITED)
      println(s"n: $n result: ${x.bigDecimal.compareTo(BigDecimal(10, java.math.MathContext.UNLIMITED).pow(n).bigDecimal)}")
}
```

BEWARE: do not use `java.math.MathContext.UNLIMITED` in operations with untrusted input.

**Comment by SethTisue** [comment]
PR was https://github.com/scala/scala/pull/6884
