### ISSUE TITLE
 finding some fault of writing on scala partial function

### ISSUE THREAD

**Issue by Hamza-Meknassi** [scala/bug#11822]
I found an issue that is still open which is: "Scaladoc member link only gets me in the neighborhood,
then I use Streetview to find my destination #11805" this issue tries to find a solution for the scala liaison and partialFunction.applyOrElse and
in this issue there is a link to the scala documentation on partialFunction and we found an
error
in the documentation on the sentence "If an exception is not thrown, evaluation may result in an arbitrary value."
and they should make "the" before evaluation.

**Comment by hrhino** [comment]
I personally think that "... evaluation [of this method] may result in an arbitrary value" sounds perfectly fine.

**Comment by SethTisue** [comment]
yeah, I don't see a problem here

**Comment by som-snytt** [comment]
As a native speaker of English from a traditionally monolingual English-speaking culture, I also don't hear a problem there, but I can also sympathize.

> it is not guaranteed [that] `apply` will throw

> `isDefinedAt` allows to test [allows testing] if [whether] a value is in the domain

> It is the responsibility of the caller [Client code must]

Or how about, "If `isDefinedAt` is false, `apply` may return an arbitrary value instead of throwing an exception. Only call `apply` after using `isDefinedAt` to determine that it returns a meaningful value. Or even better, prefer `applyOrElse`, which can be more efficient."

I hope someone explains why it was OK to say "evaluation" instead of "any evaluation" (if that was intended) or "the evaluation". Was it understood that every evaluation is contextual? "Candy tastes good," and "The candy tastes good." "If candy does not taste good, it may be poison." "If the candy does not taste good, it may be poison." I guess the reason the evaluation is a hypothetical any evaluation is that if you just called `apply` without checking `isDefinedAt`, it's too late, you're already dead.

Also, I would not call it "evaluation." It is an "application." Then the argument is about whether one applies args to a function or a function to args. I believe an application is application of args to a function, which is pre-existing and awaiting args which come along for application, the way Harvard is pre-existing and just sits there awaiting student applications.  I think people who prefer to apply functions think of applying as an active state, "the application of power." But really it's more like an application of paint, a layer, a covering, a veneer. We daub some args on a function and it assumes a different aspect we call the result value.

"The application of power" in the world is also just the production of surface effects.

I think we can say that all issues of semantics can be addressed on a PR and that a bug report is not necessary before proposing a change of this magnitude.

**Comment by som-snytt** [comment]
Worth noting [the assumption](https://www.artima.com/pins1ed/case-classes-and-pattern-matching.html#15.7) the passage controverts:

> One other generalization is worth noting: a sequence of cases gives you a partial function. If you apply such a function on a value it does not support, it will generate a run-time exception.
