### ISSUE TITLE
Class parameter no longer final in 2.12.11

### ISSUE THREAD

**Issue by dragos** [scala/bug#11985]
## reproduction steps

```scala
class Lazy[T](initializer: => T) extends Serializable {
  private[this] lazy val value: T = initializer
  def apply(): T = value
}
```

## problem

The field `initializer` used to be final in 2.12.10, and it's no longer final in 2.12.11. Moreover, this causes the class to be incompatible serialization-wise (the serialver is different now).

```diff
$ diff lazy-2.12.10.txt lazy-2.12.11.txt 
1c1
< Classfile /Users/iulian.dragos/sandbox/classes/Lazy.class
---
> Classfile /Users/iulian.dragos/sandbox/classes1/Lazy.class
3c3
<   MD5 checksum 31db753755aadb00cb5a1e755df1204f
---
>   MD5 checksum e64a02ad89e3431bc8de81503832d53e
73c73
<   private final scala.Function0<T> initializer;
---
>   private scala.Function0<T> initializer;
75c75
<     flags: ACC_PRIVATE, ACC_FINAL
---
>     flags: ACC_PRIVATE
```

## expectation

The same behavior as in 2.12.10

**Comment by lrytz** [comment]
This is actually a bugfix for a feature: https://github.com/scala/scala/pull/8514

Because `value` is a lazy val, `initializer` is caputred in a field - it has to be available when the lazy val is computed. The compiler identifies that the field is not otherwise used and therefore emits code to null it out.

**Comment by iuliand-db** [comment]
Great, thanks for the explanation! I'm closing this.

**Comment by dragos** [comment]
Great, thanks for the explanation, I'm closing this.
