### ISSUE TITLE
Map within a Map - forgetfulness

### ISSUE THREAD

**Issue by renpe** [scala/bug#12031]
## reproduction steps

using Scala (2.13.2) / (2.10.6)

```scala
scala> import scala.collection.mutable
import scala.collection.mutable

scala> val col = mutable.Map[Int, mutable.Map[Int, Int]]().withDefaultValue(mutable.Map[Int, Int]().withDefaultValue(0))
col: scala.collection.mutable.Map[Int,scala.collection.mutable.Map[Int,Int]] = Map()

scala> col(2)(5) += 1

scala> println(col, col(2), col.get(2))
(Map(),Map(5 -> 1),None)
```

## problem

I expect
```scala
(Map(2 -> Map(5 -> 1)),Map(5 -> 1),Some(Map(5 -> 1)))
```

**Comment by SethTisue** [comment]
I don't think this is a bug. `withDefaultValue` is working as designed here. `withDefaultValue` never creates new map entries, it only controls what gets returned by `apply` when the key isn't found. So that's why `col` remains empty even after `col(2)(5) += 1`.

I would add that there's a second reason what you're trying to do with nested mutable maps in combination with `withDefaultValue` won't work. You seem to be assuming that you'll get a fresh inner map for each key in the outer map, but `withDefaultValue` doesn't take a call-by-name parameter; it returns the exact same (`eq`) value each time:

```
scala 2.13.2> import scala.collection.mutable
import scala.collection.mutable

scala 2.13.2> val m = mutable.Map[Int, AnyRef]().withDefaultValue(new AnyRef)
val m: scala.collection.mutable.Map[Int,AnyRef] = Map()

scala 2.13.2> m(0) eq m(1)
val res11: Boolean = true
```

and thus

```
scala 2.13.2> col(3)(5)
val res24: Int = 0

scala 2.13.2> col(2)(5) += 1

scala 2.13.2> col(3)(5)
val res26: Int = 1
```

:scream:, surely this was not your intent.

Perhaps you're looking for `getOrElseUpdate`, which does take a by-name parameter.

**Comment by SethTisue** [comment]
by the way, these sorts of usage questions are really better on https://users.scala-lang.org
