### ISSUE TITLE
Repeated warning about experimental.macros in REPL

### ISSUE THREAD

**Issue by nogurenn** [scala/bug#12051]
## reproduction steps

using Scala 2.13.2 (OpenJDK 11.0.7),

```scala
scala> import scala.language.experimental.macros
                                          ^
       warning: Unused import
import scala.language.experimental.macros

scala> def impl(c: scala.reflect.macros.whitebox.Context) = c.Expr[Unit](c.parse("println(2)"))

       import scala.language.experimental.macros
                                          ^
<synthetic>:2: warning: Unused import

(To diagnose errors in synthetic code, try adding `// show` to the end of your input.)
def impl(c: scala.reflect.macros.whitebox.Context): c.Expr[Unit]
```

## problem

Found this while doing https://github.com/scala/docs.scala-lang/issues/1710. On first import, the warning already shows. It keeps showing up. Maybe it's by design though, because of the specific language feature?

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/7722

If repl root imports goes ever goes in https://github.com/scala/scala/pull/8593 then the follow-up is the PR that does all history imports as root imports instead of "injected into source template".

Current workaround is to turn off linting in console.
