### ISSUE TITLE
A wrong link in src/library/rootdoc.txt

### ISSUE THREAD

**Issue by ShapelessCat** [scala/bug#12068]
## problem
Here is a part of the _rootdoc.txt_:
```
Additional parts of the standard library are shipped as separate libraries. These include:

  - [[scala.reflect       `scala.reflect`]]   - Scala's reflection API (scala-reflect.jar)
  - [[https://github.com/scala/scala-xml `scala.xml`]]    - XML parsing, manipulation, and serialization (scala-xml.jar)
```
``[[scala.reflect       `scala.reflect`]]   - Scala's reflection API (scala-reflect.jar)`` uses a wrong link. From the context, it should point to a separate library, and I think it is the separately shipped https://github.com/ShapelessCat/scala/tree/2.13.x/src/reflect/scala/reflect. However, the existing link, the first `scala.reflect` in `[]`, points to the reflection package in the not separately shipped standard library.

**Comment by ShapelessCat** [comment]
I can fix this, but I have a question about which link is preferred?
Here are the candidate links:
1. API: https://www.scala-lang.org/api/current/scala-reflect/scala/reflect/index.html
2. API: https://www.scala-lang.org/api/2.13.3/scala-reflect/scala/reflect/index.html
3. GitHub: https://github.com/ShapelessCat/scala/tree/2.13.x/src/reflect/scala/reflect

**Comment by SethTisue** [comment]
choice 1 is correct

**Comment by ashawley** [comment]
Yes, since scala-library uses `scala.reflect` namespace, any Scaladoc links in scala-library point to the `scala.reflect` in scala-library not scala-reflect.  This is an issue with rootdoc, but there are probably other references to `scala.reflect` in the library docs that also don't work either.

In addition to the namespace issues, there's another issue where scala-reflect isn't a dependency of scala-library in the build.  It's the other way around.  So even though scala-reflect has an `apiURL` with the right version in the name (e.g.  https://www.scala-lang.org/api/2.13.3/scala-reflect/scala/reflect/index.html) it can't be used.  If it could, this would work:

```
  - `scala.reflect` - Scala's reflection API (scala-reflect.jar)
    - [[scala.reflect.api    `scala.reflect.api`]]
    - [[scala.reflect.macros `scala.reflect.macros`]]
```
