### ISSUE TITLE
misleading error message with `-Wconf`

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#12098]
you're supposed to follow `-Wconf` with a colon and some more stuff, like `-Wconf:any:warning-verbose`, that kind of thing, but if you don't supply the colon, then (Scala 2.13.3):

```
% scalac -Wconf -bootclasspath foo S.scala
scalac error: missing argument for -bootclasspath
  scalac -help  gives more information
scalac error: bad option: '-bootclasspath'
  scalac -help  gives more information
```

neither part of the error message makes sense

**Comment by som-snytt** [comment]
`-Wconf` behaves differently because of `prepend = true` https://github.com/scala/scala/commit/39d3b3a93cd3cf01303ba9aba487b742943d8e57#diff-d7da7216ed859145d1d161cf3de4a829R811

but the args that are reversed can be either colon args `-x:a` or regular args `-x a -y`.

Probably the latter feature is never used; for example, no one writes `-Yimports java.lang scala scala.Predef` or `-Wconf cat=deprecation:ws cat=feature:ws cat=optimizer:ws`. This is the behavior for `MultiStringSetting` only.
