### ISSUE TITLE
Inner class method shadows the outer class method with different signature

### ISSUE THREAD

**Issue by texasbruce** [scala/bug#12101]
## reproduction steps

using Scala 2.13.2,

```scala
class Outer {
  def foo(s: String): Unit = ()

  class Inner {
    def foo(s1: String, s2: String): Unit = ()
    foo("")
  }
}
```

## problem

Compiler errors:

    On line 5: error: not enough arguments for method Foo: (s1: String, s2: String): Unit.
           Unspecified value parameter s2.

## expected outcome

Compiler should be able to select the correct method in the outer class depending on the signature of the call.

**Comment by SethTisue** [comment]
I don't think this is a bug. The inner `foo` shadows the outer `foo`, as it should.

**Comment by texasbruce** [comment]
> I don't think this is a bug. The inner `foo` shadows the outer `foo`, as it should. Shadowing is per-identifier, not per-overload. (And, Dotty agrees.)
> 
> When you overload, the overloads share an identifier; they aren't separate identifiers.

They have different signatures. Shouldn't be considered the same imo

**Comment by som-snytt** [comment]
"Name binding" only considers the name. https://scala-lang.org/files/archive/spec/2.13/02-identifiers-names-and-scopes.html

With an overload, it's already complicated to figure out which may apply, because it changes how arguments are typechecked. Many of the tickets pertaining to overload resolution include an intuition that "it's obvious that the other one is intended", and sometimes inference or overloading is tweaked to improve the user experience.

In a future without autotupling, for instance, perhaps arity could be used to select the shadowed member, as you imply. Or maybe that would be too complicated. Such a scheme would also imply any of several imports supplying a name `f` might be the right one, whereas now it would be ambiguous.

Implicit lookup is changed in Scala 3 to consider signatures only (and nesting depth) instead of how a name is bound. So this sort of change is conceivable, but the current behavior is not a bug.

**Comment by joroKr21** [comment]
Overloading works only wrt the same target. Having random methods in scope overload each other would be very hard not just to implement but also to use (source compatibility would be even worse than it is now).
