### ISSUE TITLE
Anonymous functions with the same vals in a closure are not equal

### ISSUE THREAD

**Issue by oscar-broman** [scala/bug#12148]
## reproduction steps

using Scala 2.13.3,

```scala
def fn(a: Int) = (b: Int) => a + b
val f1 = fn(1)
val f2 = fn(1)
println(f1 == f2)
```

## problem

`f1.equals(f2)` should be true

**Comment by dwijnand** [comment]
Yeah, if anything "`f1.equals(f2)` shouldn't compile".  But alas, `Object#equals`...

**Comment by oscar-broman** [comment]
Wouldn't it be possible to do something like this automatically?
```scala
def fn(a: Int) = {
  case class Fn(a: Int) extends (Int => Int) {
    def apply(b: Int) = a + b
  }
  Fn(a)
}

val f1 = fn(1)
val f2 = fn(1)
println(f1 == f2) // true
```

**Comment by dwijnand** [comment]
Yes, theoretically.  But at the cost of increasing the size of everything lambda: first back to an actual class (instead of using JVM 8+ lambda support) and then even more so to a case class, with all its (bytecode) bits-and-bobs.

It also would only function with captured values that themselves have structural equality (like int and case classes).  Anything else and it would continue to return false for seemingly equal things.

**Comment by oscar-broman** [comment]
Got it!
