### ISSUE TITLE
Failure in application of a higher type to a type constructor with a path type as its type parameter's bound

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12142]
## reproduction steps

using Scala 2.13.3,

```scala
	trait Bounds {
		type Upper <: Bounds
	}

	trait Template[+X <: Bounds] extends Bounds { outer =>
		val body :X
		type Bound >: body.Upper <: Bounds

		type Copy[+A <: Bound] <: Template[A] 

		type High[T[+A <: Narrow] <: Bounds]

		def applied(narrow :Template[Narrow]) :High[narrow.Copy] //this fails
		def indirect(narrow :Template[Narrow]) :High[({ type T[+A <: Narrow] = narrow.Copy[A] })#T]  = { //but this works
		    implicitly[Narrow <:< narrow.Bound] //no problem
                    ???
		}
	}

	trait Narrow extends Bounds {
		type Upper >: Narrow <: Bounds
	}
```

## problem
```
Error:(23, 42) kinds of the type arguments (narrow.Copy) do not conform to the expected kinds of the type parameters (type T).
                     narrow.Copy's type parameters do not match type T's expected parameters:
                     type A's bounds <: Template.this.Bound are stricter than type A's declared bounds <: Playground.Narrow
		         def applied(narrow :Template[Narrow]) :High[narrow.Copy]
```

Judging how a level of indirection in the form of a type lambda fixes the issue I'd say it's a bug.

## motivation
Judging by the discussion, the simplification of reproduction steps made it hard to wrap ones head around for humans. Here's what I was doing, for ilustration (won't compile):
```scala
trait Chain { //HList flavour with a hierarchy of 'links'
    type Clone //reconstruction of non-sigleteon bound of 'this.type'
}
trait ColouredChain extends Chain

class Empty extends ColoredChain
object Empty extends Empty {
    type Clone = Empty
}

trait NonEmptyChain 

trait Link[+Tail <: Chain, Payload] extends NonEmptyChain {
    val payload :Payload
    val tail :Tail
   
    type Bound //???
    type Copy[+A <: Bound, B] <: Link[A, B]
    def copy[A <: Bound, B](t :A, b :B) : Copy[A, B] = ???
   
    type Clone = left.Clone Copy Payload
}


trait BlueLink[+T <: ColouredChain, H] extends Link[T, H] with ColouredChain
trait RedLink[+T <: ColouredChain, H] extends Link[T, H] with ColouredChain
trait PaintLink[+T <: Chain, H] extends Link[T, H] with ColouredChain
```

Problem: implement `Link[_, _]#copy` as a copy constructor, which should preserve the link colour, in as much useful way as possible. What the `Bound` type should be? It can't be `Chain`, because then we won't be able to define it as `BlueLink` in `BlueLink`, etc. So, first attempt:
```scala
trait Link[+T <: Chain, P] extends NonEmptyChain {
/* .... */ 
    type Bound = ColouredChain
    type Copy[A <: ColouredChain, B] <: Link[A, B]
}
trait BlueLink[+T <: ColouredChain, H] extends Link[T, H] with ColouredChain {
     type Copy[A <: ColouredChain, B] = BlueLink[A, B]
}
trait RedLink[+T <: ColouredChain, H] extends Link[T, H] with ColouredChain {
     type Copy[A <: ColouredChain, B] = RedLink[A, B]
}
trait PaintLink[+T <: Chain, H] extends Link[T, H] with ColouredChain {
     type Copy[A <: ColouredChain, B] = PaintLink[A, B] 
}
```
Now, `PaintLink[_, _]#Copy[_, _]` has a narrower left upper bound than it could have otherwise, but there is no good way around it. The problem: type `Link[_, _]#Clone` fails to compile because it applies `T <: Chain` to a type which has a `ColouredChain` upper bound. So we'd love to have:
```scala
    trait Link[+T <: Chain, H] extends NonEmptyChain {
        /* ... */
       type Bound >: left.Clone | ColouredChain <: Chain //not in scala, sadly.
    }
```
Attempt:
```scala
    trait Chain {
        /* ... */
       type UpperBound >: Clone <: Chain //LUB of Clone and ColouredChain
    }
    trait ColouredChain extends Chain {
        override type UpperBound = ColouredChain
        override type Clone <: ColouredChain
    }
    trait GrayChain extends Chain {
        override type UpperBound = Chain
    }
    trait Link[+T <: Chain, H] {
        override type Bound >: left.UpperBound <: Chain
    }
```
Going this way would let us have in `Link` both `type Clone = Copy[left.Clone, H]` and a `copy` declaration which is of some (limited) use in generic context of `Link[T, H]`, but with full functionality one would want in `BlueLink` and `PaintLink` when we know more about `left.Bound`. Now, the real thing was more complex, and there were more type definitions in `Chain` than just `Clone` which all conformed to `UpperBound`, so that `Link[_,_]#copy[A <: left.UpperBound, B]` was actually quite useful to have.

**Comment by joroKr21** [comment]
Didn't you mean to write `type Copy[+A <: Bounds] <: Template[A]` (Bound**s**)?

**Comment by noresttherein** [comment]
No, the problem is exactly in the `Bound` member type serving as the upper bound. A word of explanation: it is a degeneration of a class hierarchy, where the upper bound on the type parameter to `Template` varies. Ergo, the type bound on their supertype - `Template` - must be their LUB, meaning it's wider than, say, `Specific[+A <: Narrow] extends Template[A]`. This introduces a problem how to define methods returning 'like' objects, like copy constructors. One solution would be to declare `Copy` accepting an intersection type of all upper bounds of all subclasses of `Template`, but then `Copy` becomes inapplicable to `A` - the wider type parameter of `Template` and `body` cannot be used as a parameter. In an ideal world, this would be solved with a type union. Currently, I tried to circumvent the issue by having the type bound as a member type, which uses `body.Upper` - a sort of 'actual, invariant type of `body`' as its lower bound, so that `Copy` remains sort of applicable to `A` (well, not A, but its 'copy type').

**Comment by joroKr21** [comment]
Hmm I'm not sure what it means to have an abstract type member as an upper bound but it sure looks not compatible with having a concrete upper bound of `Narrow`. So the bug is that the type lambda compiles?

**Comment by noresttherein** [comment]
And what's exactly wrong with using a type member as an upper bound? Clearly `Narrow <: narrow.Bound ` and thus `narrow.Copy <:  [+A <: Narrow] <: Template[A]`. Why shouldn't it work?

**Comment by joroKr21** [comment]
> Clearly Narrow <: narrow.Bound

That doesn't sound right. We don't know what `narrow.Bound` is. It could be some other subtype of `Bounds`, like imagine we define a `Narrow2`.

**Comment by noresttherein** [comment]
But `narrow.body.type <:< Narrow`, so `Narrow <:< narrow.body.Upper`, so `Narrow <:< narrow.Bound` (and `narrow.Bound <:< Bounds`). I mean I can get implicit evidence to all the above.

**Comment by NthPortal** [comment]
I'm going to write down more type constraints, for my sake if no one else's (and also just kinda run through this as a brain dump).

1. `Bounds#Upper <:< Bounds`
2. `Narrow <:< Bounds`
3. `Narrow <:< Narrow#Upper`
4. `Narrow#Upper <:< Bounds` (same as {1})
5. `Template[+A] <:< Bounds` (where `A <:< Bounds`)
6. `Template[+A]#body.type <:< A <:< Bounds`
7. `Template[_]#Bound <:< Bounds`
8. let `t: Template[_]`; `t.body.Upper <:< t.Bound`
9. let `t: Template[_]`; `t.Copy[+A] <:< Template[A]` (where `A <:< t.Bound`)

Those are the constraints explicit in the code.

Now, let us look at what constraints are required by `Template[_]#High[_[_]]`.

10. let `Template[_]#High[T[_]]`; ` T[_] <:< Bounds` (constraint A)
11. let `Template[_]#High[_[+A]]`; `A <:< Narrow` (constraint B)

Let us examine the `Template[_]#applied` method.

12. let `t: Template[_]`, `narrow: Template[Narrow]`
13. the desired return type of `t.applied(narrow)` is `High[narrow.Copy]`

Does `narrow.Copy` satisfy constraint A (in {10})?

14. from {9}, `narrow.Copy[X] <:< Template[X]`
15. from {5}, `Template[_] <:< Bounds`
16. therefore ({14}, {15}) `narrow.Copy[_] <:< Bounds`
17. YES, it satisfies constraint A

Does `narrow.Copy` satisfy constraint B (in {11})?

18. let `type A` s.t. `narrow.Copy[A]` typechecks
19. from {9}, `A <:< narrow.Bound`
20. from {7}, `narrow.Bound <:< Bounds`
21. therefore `A <: Bounds`
22. from {6}, `narrow.body.type <:< Narrow`
23. from {8}, `narrow.body.Upper <:< narrow.Bound`
24. therefore ({20}, {23}) `narrow.body.Upper <:< Bounds`

I'm honestly not sure where to go to prove that it satisfies constraint B. Happy for input here pointing out what I missed.

> so `Narrow <:< narrow.Bound`

The problem is, in order to satisfy constraint B, we need to know that `narrow.Bound <:< Narrow`, not the other way around. Constraint B requires that `A <:< Narrow`, but the combination of `Narrow <:< narrow.Bound` and `A <:< narrow.Bound` do not guarantee that `A <:< Narrow`; `A` could be a subtype of a *different* subtype of `narrow.Bound`, or a direct subtype of `narrow.Bound`.

**Comment by joroKr21** [comment]
There might be a missing (or wrong) application of `asSeenFrom`.
Trying to debug this I noticed that we lose the path dependent type when comparing the bounds.

**Comment by noresttherein** [comment]
I start to suspect it might for me be a case of a 'false theory deduced intuitively from limited application' then, but I must say I reached the moment of highest cognitive disonance. It is clearly not your job to educate me, but this is worrying, because the existence of required implicit `<:<`s and the fact that type lambda compiles is in line from what I'd expect I have no idea where I make a mistake in assumptions (or reasoning).

I always intuitively assumed, that given
```
let A <:< B; let C <:< D;
let type V[+X <: B] = C; let type W[+X <: A] = D
```
Then `V <:< W` (if it is even correct to naturally lift the subtype relationship to type constructors).
Everything certainly behaves that way if `A` and `B` are not abstract - I can pass `V` as a type argument for a higher type parameter `W[+X <: A] <: D`. For example, this compiles:

```
		type Generic[+A <: Bounds] <: Bounds
		type H = High[Generic]
```
This of course relies on existance of (not documented/not existing?) contravariance in upper type bounds. Was I wrong about it?

I am not sure I understand exactly what and how you are trying to prove with the constraint B, but it seems to me you are a going in the wrong direction (being covariant): from the existence of 
```
let type C = narrow.Copy[X] forSome { type X }
```
You try to check `T[+A <: Narrow]` - the type of the `High`'s type parameter - is applicable to any such `X`, which it obviously isn't. But it's not `X` that is the argument, it's the type constructor `narrow.Copy`, and we should care if `narrow.Copy` is applicable to any argument `X` such that `T[X]` type checks for any `T[+A <: Narrow]`. Which it does, I think we can agree?   Certainly `implicitly[Narrow <:< narrow.Bound]` validates this.

Obviously, I do not know what exact rules compiler applies - it certainly doesn't accept some cases where, assuming the type system is a transitive partial order, types can be mathematically proven to be in a `<:<` or `=:=` relation. So this can be only semi-formal

**Comment by joroKr21** [comment]
@noresttherein sorry if confusing you, the example is a bit of a mind twister so it is a bit difficult to reason about.
I think in the end of the day you are right and the code should compile.
I suspect the problem is that the compiler is losing information the path dependent type bound.
What I mean by that is that `A` in `narrow.Copy` should have upper bound `narrow.Bound`, but by the time we check the kinds the compiler has lost this info and thinks the bound is `Template.this.Bound`.

This patch makes your example compile, but other tests are failing: https://github.com/scala/scala/pull/9193

**Comment by noresttherein** [comment]
Thx. Sorry about it being a mind twister, I tried to minimize it from the real life problem and proceded a bit haphazardly about it, so that it became unintuitive. I'll edit the report to include a 'motivation' section.
