### ISSUE TITLE
wrong "private default argument not used"

### ISSUE THREAD

**Issue by dragos** [scala/bug#12168]
## reproduction steps

Scala 2.12.11

```scala
case class Sequencing private (foo: String = "") {
    override def toString: String = foo
}

object Sequencing {
  val EMPTY: Sequencing = Sequencing()
}
```

## problem

```
 scalac -d classes -Ywarn-unused:_  dead-code.scala
dead-code.scala:1: warning: private default argument in object Sequencing is never used
case class Sequencing private (foo: String = "") {
                               ^
one warning found
```

The default argument is used in the companion object, but the compiler believes it's not used. Making the case class constructor non-private will remove this warning.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/7707
Fixed in 2.13.
Note that the default arg to the companion apply is used in the example, not the constructor default arg.
(Historical note: The fix was just not to warn about it, but there was an earlier attempt to be smarter about the rewrite of apply to new; but there was a change at some point to always respect private on constructor.)
