### ISSUE TITLE
require parens around lambda argument with type annotation

### ISSUE THREAD

**Issue by adriaanm** [scala/bug#12218]
`{ x: Any => }` looks confusingly like a self-type; write `{ (x: Any) => ... }` instead.

**Comment by som-snytt** [comment]
This happens as a warning under the scala 3 migration scheme. I can't try out the latest `-X` options because the PR hasn't been fully reviewed yet by @SethTisue oh IIRC it's `-Xsource:3migration` to warn, `-Xsource:3cross` to error as shown.

And hey, it's quick-fixable!

Do I have to edit my excellent SO answer on this parser question? I never saw it as a special case, but a consequence of Scala being a scalable language, in the sense that the scales fall from your eyes.

```
➜  snips scala -Xsource:3
Welcome to Scala 2.13.12 (OpenJDK 64-Bit Server VM, Java 21).
Type in expressions for evaluation. Or try :help.

scala> List(42).map { i: Int => i + 1 }
                       ^
       error: parentheses are required around the parameter of a lambda
       Use '-Wconf:msg=lambda-parens:s' to silence this warning. [quickfixable]
       Scala 3 migration messages are errors under -Xsource:3. Use -Wconf / @nowarn to filter them or add -Xmigration to demote them to warnings.
       Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=scala3-migration

scala>
```

**Comment by som-snytt** [comment]
@tpolecat also anything from pre-pandemic qualifies as retro-computing!
```
scala> trait Foo { (this: Any) => }
                   ^
       error: self-type annotation may not be in parentheses
```
oh also, just to show that when the Lord slams one door in your face, etc,
```
scala> List(42).map(implicit (i: Int) => implicitly[Int] + 1)
val res0: List[Int] = List(43)
```
