### ISSUE TITLE
Mysterious constructor overload starring a type class

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12233]
Maybe it's the late hour, but this one is so baffling it's funny:
## reproduction steps

using Scala 2.13.4,

```scala
	import reflect.ClassTag
	trait TypeClass[T]
	class Hehe[T: TypeClass](private val cls: Class[T], val tpe: Int) {
		def this(tpe: Int)(implicit hehe: TypeClass[T], tag: ClassTag[T]) =
			this(tag.runtimeClass.asInstanceOf[Class[T]], tpe)
	}
```

## problem
```
too many arguments (found 3, expected 1) for constructor Hehe: (implicit evidence$1: Playground.TypeClass[T]): Playground.Hehe[T]
			this(tag.runtimeClass.asInstanceOf[Class[T]], tpe)
```

Fortunately, changing from the type class notation to explicit implicit parameter list fixes the issue. I double checked if I wasn't going crazy, but I do have plenty of classes with constructors using ~view~context bounds.

**Comment by SethTisue** [comment]
this is sort of on the path to being minimized, but it's not there.

here's the next step in a minimization:

```
scala 2.13.4> trait TypeClass[T]
            |   class Hehe[T :TypeClass](private val cls :Class[T], val tpe :Int) {
            |       def this(tpe :Int)(implicit hehe :TypeClass[T]) =
            |           this(null, tpe)
            |   }
              			this(null, tpe)
              			^
On line 4: error: too many arguments (found 2, expected 1) for constructor Hehe: (implicit evidence$1: TypeClass[T]): Hehe[T]
```

I leave finding further steps, or determining that none exist, to another commenter.

**Comment by som-snytt** [comment]
Dotty is more misterioso:
```
➜  snips ~/scala3-3.0.0-M1/bin/scalac -d /tmp t12233.scala
-- Error: t12233.scala:7:54 ----------------------------------------------------
7 |    this(tag.runtimeClass.asInstanceOf[Class[T]], tpe)
  |                                                      ^
  |ambiguous implicit arguments: both value hehe and value evidence$1 match type TypeClass[T] of an implicit parameter of constructor Hehe in class Hehe
1 error found
```
Recall that context bound evidence is prepended to the implicit parameter section:
```
➜  snips cat t12233c.scala

trait TypeClass[T]
class Hehe[T: TypeClass](i: Int, j: Int) {
  def this(i: Int)(implicit hehe: TypeClass[T], j: Int) = this(i, j)
}
```
whence the power of three:
```
➜  snips scalac -Vprint:typer t12233c.scala
t12233c.scala:4: error: too many arguments (found 3, expected 1) for constructor Hehe: (implicit evidence$1: TypeClass[T]): Hehe[T]
  def this(i: Int)(implicit hehe: TypeClass[T], j: Int) = this(i, j)
                                                          ^
[[syntax trees at end of                     typer]] // t12233c.scala
package <empty> {
  abstract trait TypeClass[T] extends scala.AnyRef;
  class Hehe[T] extends scala.AnyRef {
    <paramaccessor> private[this] val i: Int = _;
    <paramaccessor> private[this] val j: Int = _;
    implicit <synthetic> <paramaccessor> private[this] val evidence$1: TypeClass[T] = _;
    def <init>(i: Int, j: Int)(implicit evidence$1: TypeClass[T]): Hehe[T] = {
      Hehe.super.<init>();
      ()
    };
    def <init>(i: Int)(implicit evidence$2: TypeClass[T], hehe: TypeClass[T], j: Int): Hehe[T] = {
      Hehe.this.<init>(i, j)(evidence$2, hehe, j);
      ()
    }
  }
}

1 error
```
For some reason, it uses the wrong parameter list.

**Comment by Jasper-M** [comment]
```
scala> class Hehe[T: Ordering](val a: Int) {
     |   def this()(implicit hehe: Ordering[T]) = this(0)
     | }
         def this()(implicit hehe: Ordering[T]) = this(0)
                                                  ^
On line 2: error: too many arguments (found 2, expected 1) for constructor Hehe: (implicit evidence$1: Ordering[T]): Hehe[T]
```

```
scala> class Hehe[T: Ordering](val a: Int) {
     |   def this() = this(0)
     |   def ord = implicitly[Ordering[T]]
     | }
class Hehe

scala> new Hehe[Int].ord
val res2: Ordering[Int] = scala.math.Ordering$Int$@749ae690
```

I think this is intentional, but not sure about spec or anything like that. 
I vaguely recall this coming up in a previous issue.

The error is weird and confusing though.

**Comment by Jasper-M** [comment]
There's a real error here too, as also pointed out by @som-snytt. It's masked by the duplicated implicit, but becomes clearer when using 2 separate typeclasses.

```
scala> class Hehe[T: Ordering](n: Numeric[Int]) {
     |   def this()(implicit num: Numeric[Int]) = this(num);
     | }
         def this()(implicit num: Numeric[Int]) = this(num);
                                                  ^
On line 2: error: too many arguments (found 2, expected 1) for constructor Hehe: (implicit evidence$1: Ordering[T]): Hehe[T]
```

This compiles in Dotty.

**Comment by noresttherein** [comment]
@Jasper-M wait, when an implicit constructor parameter is declared as a type class, there is no need to specify it for other constructors? I mean I checked and it is so, but was it always like that? I'm pretty sure more than once I got an error coming from forgetting about the implicit parameter, so maybe I really am going mad.

**Comment by Jasper-M** [comment]
I'm not aware that this has changed somehow.

Once you've come to grips with it, it kind of makes sense. The type parameter list of the class applies to both primary and secondary constructors, so also any context bounds in that type parameter list.

**Comment by som-snytt** [comment]
That is per spec, per my comment:

> Recall that context bound evidence is prepended to the implicit parameter section

**Comment by noresttherein** [comment]
> 
> 
> That is per spec, per my comment:
> 
> > Recall that context bound evidence is prepended to the implicit parameter section

I know well how context bounds work on methods, and constructors are just special methods. That's why I was surprised that context bound on a constructor prepends a parameter to all other constructors - it breaks away from the 'just syntax sugar on another implicit parameter' view. I can see the reasoning behind it and I am happy to know, as adding implicit parameters is bothersome and I was always the one for having a choice and not 'there's one way to do it'. And the bug is independent from that anyway.

**Comment by som-snytt** [comment]
I haven't looked at code, but there was a rare spec change https://github.com/scala/scala/pull/4610/files changing "Also, a method or class with view- or context bounds may not define any additional implicit parameters." to "Evidence parameters are prepended to the existing implicit parameter section, if one exists." oh, the first commit message says it changed in 2.10.

**Comment by SethTisue** [comment]
Note that `T: Typeclass` is a "context bound", not a "view bound". (View bounds, `<%`, are deprecated and rarely used these days.)

**Comment by SethTisue** [comment]
The relevant spec section is [SLS 7.4](https://scala-lang.org/files/archive/spec/2.13/07-implicits.html#context-bounds-and-view-bounds), "Context Bounds and View Bounds". I don't see any language that clearly applies (or clearly doesn't apply) to secondary constructors, so @som-snytt I'm not sure why you're so sure this "That is per spec".

**Comment by SethTisue** [comment]
Regardless, it does seem logical that secondary constructors should get the evidence parameters, especially since Scala 3 agrees.

So there are two to-dos here:

1) perhaps clarify the spec
2) try to fix the cases where Scala 2 gets confused

I can't get very interested in the second (though it's a valid bug), but I'm interested in getting this clarified at the spec level.

**Comment by som-snytt** [comment]
Sorry that Scala is still mired in hierarchical terms such as primary and secondary; see nytimes coverage of IETF efforts.

This goes to the heart of Scala's self-representation: functions are first-class objects.

We can move away from classist language by using traits; and backporting top-level members from Scala 3; prefer `val` to `object`. We should also do something about the pejorative use of `lazy`.

There is no need to avoid packages, because everyone likes getting packages during pandemic.

@SethTisue yes, that is the spec section I pointed out above. The language could be improved, but it says if a class has context bounds, they become evidence parameters; since traits don't take constructor parameters, they can't have context bounds.

The section Dale quoted also says the scope for the ctor signature includes class type parameters, which implies the encoding as evidence parameters to the [auxiliary] ctor.

Actually, surprisingly, the bogus implicit arg list is constructed by parser. Probably it just shouldn't do that. Maybe there was an early assumption that all constructor alternatives (to use the egalitarian language of overloading) see the same evidence.
```
[[syntax trees at end of                    parser]] // t12233c.scala
package <empty> {
  abstract trait TypeClass[T] extends scala.AnyRef;
  class Hehe[T] extends scala.AnyRef {
    <paramaccessor> private[this] val i: Int = _;
    <paramaccessor> private[this] val j: Int = _;
    implicit <synthetic> <paramaccessor> private[this] val evidence$1: TypeClass[T] = _;
    def <init>(i: Int, j: Int)(implicit evidence$1: TypeClass[T]) = {
      super.<init>();
      ()
    };
    def <init>(i: Int)(implicit evidence$2: TypeClass[T], hehe: TypeClass[T], j: Int) = {
      <init>(i, j)(evidence$2, hehe, j);
      ()
    }
  }
}
```
Ordinary overload resolution should work for the RHS of the auxiliary ctor, the "self-invocation". I guess it would be trickier in Scala 3 where more than one param list is significant for overloading; but as someone recently mentioned, overloading is evil so no one goes overboard with it.

Also we shouldn't use words such as "significant" which privilege the signifier. Let's say instead, "That parameter list is honest and hard-working. It is pleasant to interact with and never has a mean thing to say about anyone."

**Comment by som-snytt** [comment]
Just a quickie during the lunch hour.

**Comment by som-snytt** [comment]
Peering into the mists of time, probably it used to work because of the restriction mentioned above https://github.com/scala/bug/issues/12233#issuecomment-732265850
