### ISSUE TITLE
JLine: completion for `:` doesn't work very well

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#12264]
@lrytz reports:

> completing `:` shows `:` as an option on the first line (like scala/scala-dev#697)
>
> Also, maybe unrelated, completing `:p` doesn't show any results (it should show `:power` and `:paste`).

**Comment by jxnu-liguobin** [comment]
`: p` will show paste and power, but `:p` will not, if there is not have a space.

**Comment by jxnu-liguobin** [comment]
Could  you please tell me about the expected results? Although I know something about repl, I still don't know what the problem is when I see this issue. @SethTisue

**Comment by SethTisue** [comment]
here is how 2.12.13 behaves; this is the desired behavior:

```
scala 2.12.13> :<TAB>
completions   help      h?        implicits   line   paste   quit     require   save   settings   type   warnings   
edit          history   imports   javap       load   power   replay   reset     sh     silent     kind              

scala 2.12.13> :s<TAB>
save   sh   settings   silent

scala 2.12.13> :p<TAB>
paste   power
```

**Comment by jxnu-liguobin** [comment]
Oh. It seems that adding a space after the question mark is just like 2.12.13, which is too weird.

```
scala> :
completions   imports       line          power         require       settings      type
help          javap         load          quit          reset         sh            warnings
implicits     kind          paste         replay        save          silent
```

```
scala> : s
save       settings   sh         silent
```

```
scala> : p
paste   power
```

**Comment by SethTisue** [comment]
yeah, off-by-one problem somewhere, I suppose?

**Comment by jxnu-liguobin** [comment]
I think that's the problem
```scala
  private val commandish = """(\S+)(?:\s+)?(.*)""".r
```
![image](https://user-images.githubusercontent.com/29496873/108624951-16622280-7483-11eb-85a5-0637b7e5fca6.png)

![image](https://user-images.githubusercontent.com/29496873/108624967-28dc5c00-7483-11eb-887b-1cb766c7f798.png)

**Comment by som-snytt** [comment]
I took a quick look, because it's been my dream to someday understand jline completion. It's like the mirage of the oasis in the desert that recedes continuously.

The completion result must include the colon. (For expression completion, the accumulator holds the current text.) With that fix:

```
scala> :load\
No such command ':load\'.  Type :help for help.
```
Jline auto-escapes the space after the command. Ha, ha. I'll spend a few minutes with it later. Possibly, the "command line parser" will handle any shell escapes and quotes. Or maybe there is a setting to turn off escapes in jline.

Worth noting that jline is built for "shell commands" and not "scala expressions". We supply the parser, but maybe other components are subject to this bias, such as completion results.

**Comment by jxnu-liguobin** [comment]
The colon uses CommandParser, while the other commands use ScalaParser.
Yesterday, I tested once. There was a problem in parsing the input line if it without spaces after the colon, which led to the failure of jline in match.
Maybe it's about configuration or jline3?
