### ISSUE TITLE
2.13.4: Using an upper bound causes a false positive non-exhaustive match warning 

### ISSUE THREAD

**Issue by neko-kai** [scala/bug#12277]
## reproduction steps

using Scala `2.13.4`,

https://scastie.scala-lang.org/Jhe2tNcHRaW4JA8gVIEI1Q

```scala
sealed trait A
final case class B() extends A
final case class C() extends A

object x extends App {

  def matcher[A1 <: A](a1: A1) = a1 match {
    case x @ (_: B | _: C) => println("B")
  }
  
}
```

## problem

```
match may not be exhaustive.
It would fail on the following input: (x: A1 forSome x not in (B, C))
```

## workaround

adding `a1:  A` ascription fixes the issue

https://scastie.scala-lang.org/Jhe2tNcHRaW4JA8gVIEI1Q

```scala
sealed trait A
final case class B() extends A
final case class C() extends A

object x extends App {

  def matcher[A1 <: A](a1: A1) = (a1: A) match {
    case x @ (_: B | _: C) => println("B")
  }
  
}
```

**Comment by dwijnand** [comment]
This requires `-Xlint:strict-unsealed-patmat` because the scrutinee type `A1` is unsealed, which is also why this is only present as of 2.13.4.

So it operates considering that `A1` has `Nil` known subtypes (`enum unsealed (A1,type A1,false,false)`), compared to `A` (`enum trait A sealed, subclasses: List(class B, class C)`), so it lacks the pinning eq axioms:

```
Or(Set(V1=B#4, V1=C#5))
AtMostOne(List(V1=B#4, V1=C#5))
```

I don't know what the criteria is but on some condition(s) we need to widen to `A` to get the range of "B or C"...  Would widening once if we get `Nil` do bad things?  🤔
