### ISSUE TITLE
Erroneous matching exhaustivity warning

### ISSUE THREAD

**Issue by tnielens** [scala/bug#12298]
## reproduction steps

Using Scala 2.12.11, the following snippet produces a compiler warning.

```scala
  sealed trait A
  object BObject extends A
  val B = BObject: A

  BObject match {
    case B  => println("all good")
  }
```
```
match may not be exhaustive.
It would fail on the following input: BObject
  BObject match {
```

## problem
The compiler warning is erroneous.

**Comment by SethTisue** [comment]
Is the problem reproducible on Scala 2.13.4?

**Comment by som-snytt** [comment]
Yes
```
scala> {
     | sealed trait T ; object X extends T
     | def f(t: T) = X match { case `t` => }
     | }
       def f(t: T) = X match { case `t` => }
           ^
On line 3: warning: local method f in value res1 is never used
       def f(t: T) = X match { case `t` => }
                     ^
On line 3: warning: match may not be exhaustive.
       It would fail on the following input: X
```

**Comment by dwijnand** [comment]
This isn't erroneous because the pattern matcher analysis isn't going to look at the definition `val B = BObject: A`.  As far it knows the match is inexhaustive and it's telling you that the case BObject is the one it wants to see.  The behaviour of `equals` on the value `B` isn't visible at compile-time, so the compiler has to be assume it might fail for `BObject`.

The best I think we could do is be less assertive and say something like "It may fail on the following input: BObject" but I don't think it's a good idea.

**Comment by som-snytt** [comment]
```
scala> {
     | sealed trait T ; object X extends T
     | def f(t: T) = X match { case _:`t`.type => }
     | }
       def f(t: T) = X match { case _:`t`.type => }
                     ^
On line 3: warning: match may not be exhaustive.
       It would fail on the following input: X
```
It's OK with the normal `def g(t: T) = t match { case _: X.type => }`

I don't know if the warning text is meaningful. The input is `X`.

As the amended example shows, `X eq X` the only possible singleton instance.
