### ISSUE TITLE
inconsistent error for "invalid unicode escape" in multiline string

### ISSUE THREAD

**Issue by unkarjedy** [scala/bug#12294]
using Scala 2.13.4

"invalid Unicode escape" error behaves strangely/inconsistently in the presence of other backslashes in multiline string literals.
Taking into account that Unicode escape sequences are deprecated and that existing code shouldn't be broken I think that all 4 errors from the screenshot shouldn't be present. `\u...` should not be treated as an error in any context.

```scala
"""\u"""
"""a \u"""
"""\u b"""
"""a \u b"""
"""\a \u"""
"""\u \b"""
"""\a \u \b"""
"""\a \u0 \b"""
"""\a \u00 \b"""
"""\a \u002 \b"""
"""\a \u0025 \b"""
```

![image](https://user-images.githubusercontent.com/3989292/102982601-dc74ae80-451b-11eb-9cf9-2058c4c98e38.png)

@martijnhoekstra

**Comment by martijnhoekstra** [comment]
The inconsistency is that \u doesn't introduce a Unicode escape (and also can't fail) when the first `u` is less than 4 characters before the end of the string. The other escapes are a red herring. Unicode escape handling returns an error when there is space for a Unicode escape so handling is attempted, but the escape is invalid. `"""\u    """` returns an error just as much as `"""\u  \b"""` does. I wouldn't be opposed personally to not making them errors at all anymore but returning the literal part escape. I have no strong opinion either way whether to also do that in non-triple quoted strings (if you do, \u would be the only sequence that could be a literal sequence instead of an escape, so it leads to an inconsistency there).

There may be some more inconsistencies when the escape has more `u`'s (Unicode escapes can have more than one u? Yes!)

Pre 2.13.2 invalid escapes were always an error, so there are no situations where an invalid escape now no longer compiles but did so before, so at least it's not a regression.

**Comment by unkarjedy** [comment]
>I have no strong opinion either way whether to also do that in non-triple quoted strings (if you do, \u would be the only sequence that could be a literal sequence instead of an escape, so it leads to an inconsistency there).

I don't think non-triple should be altered (except for raw literals, which as I understand behave exactly like triple-quote?).
`\u` is not a valid sequence in single-quote literals anyway, so we couldn't have valid single-quote string  with "\u"

- before 2.13.2 everything was consistent:
![image](https://user-images.githubusercontent.com/3989292/102996465-3b462200-4534-11eb-8916-f440ac1391ac.png)

- after 2.13.2 there are **two** types of inconsistency:
1. `"""` is not consistent with `"` in some cases (when potential incomplete unicode symbol is close to the string end
2. `"""` is not consistent with itself, and this inconsistency depends on the positioning of `\u` in the string, which is quite hard to understand from the user perspective
![image](https://user-images.githubusercontent.com/3989292/102997010-29b14a00-4535-11eb-896d-c9e229b40c0b.png)
![image](https://user-images.githubusercontent.com/3989292/102996558-5f096800-4534-11eb-9dd1-310a2f495fd2.png)

>There may be some more inconsistencies when the escape has more u's (Unicode escapes can have more than one u? Yes!)

Yeah, I discovered that just last weak =) And this check:
>when the first u is less than 4 characters

makes it only less clear, cause these 4 characters represent `0-9a-fA-F` part of unicode escape sequence, but not `u`, so it's strange to see an error here:
`\uuuuu`

I think it would be better to leave just one type of inconsistency: 1. and eliminate 2.
Didn't see the current implementation, but looks like it should simplify the code and understanding:
If literal contains `\\u+[0-9A-Fa-f]{4}` it is treated as a Unicode char, otherwise it's just a plain text.

**Comment by som-snytt** [comment]
I agree there must be something wrong with the heuristic.

I accept the principle that \u in multiline isn't processed in Scala 3, so in Scala 2 you get a deprecation for a valid escape and an error if it looks like you intended a valid escape.

I don't understand the following error.

```
scala> """\u"""
val res15: String = \u

scala> """\u """
val res16: String = "\u "

scala> """ \u """
val res17: String = " \u "

scala> """\t \u """
               ^
       error: invalid unicode escape at index 5 of \t \u

scala>
```
If it can't be explained in a one-liner, I would expect "it errors the same as before but valid is deprecated".

I would expect Scala 3 behavior under `-Xsource:3` but I haven't tried it.

**Comment by martijnhoekstra** [comment]
> I would expect "it errors the same as before but valid is deprecated".

That's indeed what was intended, but shown here not to always be the case.
