### ISSUE TITLE
Trying to access the this of another class with instanceOf singleton

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12312]
## reproduction steps

using Scala 2.13.4,

```scala
scala> object X
object X

scala> X.isInstanceOf[X.type]
error: Error while emitting <console>
assertion failed:
  Trying to access the this of another class: tree.symbol = class $read, class symbol = class iw compilation unit: <console>
     while compiling: <console>
        during phase: jvm
     library version: version 2.13.4
    compiler version: version 2.13.4
  reconstructed args: -deprecation -feature -Wconf:cat=feature:w -Wconf:cat=deprecation:w -Wconf:cat=deprecation:ws -Wconf:cat=feature:ws -Wconf:cat=optimizer:ws

  last tree to typer: Literal(Constant(type))
       tree position: <unknown>
            tree tpe: Class(classOf[])
              symbol: null
           call site: constructor $iw in package $line4

== Source file context for tree position ==
```

or
```scala
package $line4 {
  sealed class $read extends _root_.scala.Serializable {
    sealed class $iw extends _root_.java.io.Serializable {
      object X
    };
    val $iw = new $iw
  };
  object $read extends scala.AnyRef {
    val INSTANCE = new $read
  }
}
package $line5 {
  sealed class $read extends _root_.scala.Serializable {
    val $line4$read: $line4.$read.INSTANCE.type = $line4.$read.INSTANCE;
    import $line4$read.$iw.X;
    sealed class $iw extends _root_.java.io.Serializable {
      val res1 = X.isInstanceOf[X.type]
    };
    val $iw = new $iw
  };
  object $read extends scala.AnyRef {
    val INSTANCE = new $read
  }
}
```

## problem

Expected the compiler to be less assertive.

**Comment by SethTisue** [comment]
outside the REPL, it doesn't happen:

```
object X
object Y extends App {
  X.isInstanceOf[X.type]
}
```

(though presumably a non-REPL reproducer could be constructed by imitating whatever REPL wrapper stuff is relevant)

**Comment by dwijnand** [comment]
REPL code minimised 

```scala
class A { object X }

class C {
  val a = new A; import a.X
  class D {
    val res1 = X.isInstanceOf[X.type]
  }
}
```

**Comment by dwijnand** [comment]
Had a look at this one.  ExplicitOuter rewrites

```scala
      def res1(): Boolean = C.this.a().X().isInstanceOf[C.this.a.X.type]();
```

into

```scala
      def res1(): Boolean = D.this.$outer().a().X().isInstanceOf[C.this.a.X.type]();
```

which Erasure rewrites to

```scala
      def res1(): Boolean = C.this.a().X().eq(D.this.$outer().a().X());
```

which contains the illegal C.this reference.  The problem is that in rewriting the TypeTree into a "real" value tree Erasure uses `gen.mkAttributedQualifier`, but that tree is only valid before ExplicitOuter.  The problem already has precedents in LambdaLift and Async, where `explicitOuter.OuterPathTransformer` is being reused to try to fix the tree up.  So that's where I took my hands out of my hair and stopped trying to fix this..

**Comment by retronym** [comment]
It would be worth looking for kindred bugs (e.g. in `asInstanceOf[X.type]` or `classOf[X.type]`. They might actually not be a problem depending on how they are erased.

I would first try to get `ExplicitOuter` to rewrite the type argument to some tree that contains the outer reference, and then have `Erasure` emit that tree when emiting the `eq`.

Why do I suggest modifying `ExplicitOuter` rather than making `Erasure` use `OuterPathTransformer`, like `Async` / `LambdaLift`? The outer reference that we want to make explicit is _already_ in the tree, not introduced by a later phase like `async`.

How could we actually represent the tree to contain the outer reference? That part will take a some trial and error. A fallback approach is to use a tree attachment on the `TypeTree` as a "back channel", but it may also be possible to create something like `TypeTree(D.this.$outer().a().X.type)`.
