### ISSUE TITLE
upgrade to ASM 9.1, for JDK 17 support

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#12332]
9.1 came out yesterday, as per https://asm.ow2.io/versions.html (thanks @mkurz for the heads up)

sequel to #12328

I should get this done in time for both 2.12.14 and 2.13.5, it's better for us to stay on top of this

**Comment by mkurz** [comment]
Just as a reminder what else needs to be done:

- [ ] We could also already add `17` as `-target` flag like done in https://github.com/scala/scala/pull/9481 I think that should be OK, since the `-target` flag currently only is used to write the class file version in the generated class files. I don't think there is anything wrong doing that for Java 17 already as well.
- [ ] Also upgrade to ASM 9.1 in dotty, like https://github.com/lampepfl/dotty/pull/11293 (including updating target flag)

**Comment by mkurz** [comment]
@SethTisue Now that Scala 3.0.0-RC1 should be out by end of the week, would it be possible that you cut a new release of https://github.com/scala/scala-asm asap? So we can upgrade it in dotty before the RC happens (like https://github.com/lampepfl/dotty/pull/11293)? Thanks!

**Comment by SethTisue** [comment]
I can get it done by Wednesday at the latest, probably Tuesday.

**Comment by mkurz** [comment]
> I can get it done by Wednesday at the latest, probably Tuesday.

Great, thanks!

**Comment by som-snytt** [comment]
It's Tisue Tuesday.

**Comment by SethTisue** [comment]
well it's Tuesday in Europe: https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.1.0-scala-1/

**Comment by SethTisue** [comment]
2.12.x PR is scala/scala#9488, 2.13.x PR is scala/scala#9489
