### ISSUE TITLE
REPL: tab completion: entire name may show as "deprecated" even if only one overload is

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#12338]
for example, if one tab-completes `get` on a `String`:

```
scala> "foo".get
getBytes( (deprecated)   getChars(                getClass() (universal)
```

`getBytes` shows as deprecated, but (as scala/scala#9476 helps us see), actually only one of its overloads is deprecated:

```
scala> "foo".getBytes
def getBytes(): Array[Byte]
def getBytes(x$1: java.nio.charset.Charset): Array[Byte]
def getBytes(x$1: String): Array[Byte]
def getBytes(x$1: Int, x$2: Int, x$3: Array[Byte], x$4: Int): Unit (deprecated)
```

**Comment by SethTisue** [comment]
this is a mistake I made in https://github.com/scala/scala/pull/8905

**Comment by som-snytt** [comment]
This is really pushing the repl ui to its limit.

**Comment by jxnu-liguobin** [comment]
@SethTisue All overload methods should  be deprecated?

**Comment by SethTisue** [comment]
@jxnu-liguobin only one of the overloads is deprecated, as per https://docs.oracle.com/javase/8/docs/api/java/lang/String.html

therefore instead of:

```
scala> "foo".get
getBytes( (deprecated)   getChars(                getClass() (universal)
```

I should see

```
scala> "foo".get
getBytes(                getChars(                getClass() (universal)
```

**Comment by jxnu-liguobin** [comment]
@SethTisue Hi, I'm reproducing  this question, but ```"1".get<tab>``` always gets the following prompt 
![image](https://user-images.githubusercontent.com/29496873/107845247-145deb00-6e15-11eb-905b-dfd3a2935f92.png)

How to disable  it during debugging? Or can it be displayed all possibilities ?

In normal terminal, double-click Tab or y-key is usually used to display all the data.

**Comment by SethTisue** [comment]
@jxnu-liguobin I'm afraid I don't know, this isn't a question I've run into myself. Maybe look at the source code for JLine? If you really get stuck, let me know. (Sorry, I'm out of time to help any further this week, but I could help next week.)

**Comment by jxnu-liguobin** [comment]
Does this look like a feature provided by jline?

**Comment by SethTisue** [comment]
yes, in `reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java`

**Comment by jxnu-liguobin** [comment]
> yes, in `reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java`
@SethTisue 
This is because multiple candidates are all `getBytes`. When they are put into the `Map`, they are just covered by the last `getBytes`, Jline doesn't show duplicate candidates.

![image](https://user-images.githubusercontent.com/29496873/108449656-caef1f00-729e-11eb-9016-546ffc66e693.png)

![image](https://user-images.githubusercontent.com/29496873/108449753-f5d97300-729e-11eb-95a8-0d7d0662bc1a.png)

This one doesn't look easy to fix. It's not even a problem.

**Comment by jxnu-liguobin** [comment]
One solution is that we group the candidates with descriptions independently, so that we can show two of the same methods at the same time. Like this:
![image](https://user-images.githubusercontent.com/29496873/108450961-f7a43600-72a0-11eb-8f17-6868707afb02.png)

It's very simple. We only need to modify one line of code:
![image](https://user-images.githubusercontent.com/29496873/108450894-dba09480-72a0-11eb-9609-421a8969d34d.png)

Of course, this will change some existing behaviors. I'm not sure if there is a better way. But the test of `CompletionTest.scala` has passed completely. Maybe it's just a change in the display, and it doesn't affect the number of candidates? 😅

**Comment by jxnu-liguobin** [comment]
@SethTisue Maybe It should be closed
