### ISSUE TITLE
Enmeration withName

### ISSUE THREAD

**Issue by krmoore2010** [scala/bug#12346]
## reproduction steps

using Scala (2.13.4),

object TestEnum1 extends Enumeration {
  val ONE = Value(12)
}

object TestEnum2 extends Eumeration {
    val ONE = Value("X")
}

## problem

With TestEnum1   TestEnum1.withName("ONE") will return an enumeration

With TestEnum  TestEnum2.withName("ONE") will fail with java.util.NoSuchElementException: No value found for 'ONE'
With TestEnum  TestEnum2.withName("X")  will return the enumration ONE - surely this is wrong?

Surely "withName" should just be looking only at the name of the Enumeration i.e. ONE not the String in Value?

**Comment by krmoore2010** [comment]
i.e. some that works like this:-

 def withName(in:String): Value = {
      val clz = this.getClass
      val fields = clz.getDeclaredFields().toList
      val field = fields.find(_.getName == in)
      field.map(x => x.get(this).asInstanceOf[Value]).getOrElse(throw new NoSuchElementException(s"No value found for '$in'"))
    }

**Comment by dwijnand** [comment]
> Surely "withName" should just be looking only at the name of the Enumeration i.e. ONE not the String in Value?

https://users.scala-lang.org/ is the forum we use for asking questions, rather than the issues here.

`withName` uses the name for the value, which is calculated automatically at construction time if you use `Value` or `Value(Int)` (like `Value(12)`) but if you use `Value("X")` then you are giving the value the name "X", despite calling the `val` "ONE", so that's your choice.  `withName` is just using the name you specified.

**Comment by krmoore2010** [comment]
Yes that's what it's doing but it doesn't make sense in the above example the name of the Enumeration is ONE not the value assigned to it.

**Comment by dwijnand** [comment]
> Yes that's what it's doing but it doesn't make sense in the above example the name of the Enumeration is ONE not the value assigned to it.

I don't agree with you.  The name of the enumeration is TestEnum2.

The value in it has a compile-time name and a runtime name - `TestEnum2.ONE` vs `TestEnum2.withName("ONE")`.  Because it's good that these two names match, there is a mechanism for which you only name the val and the runtime name matches it: `val ONE = Value`.  However, you are allowed to directly define these two, for reasons of your own, for instance `val ONE = Value("X")` but then you can't be surprised if the val is still called "ONE" while the runtime name is now "X" instead.  Why are you using `Value("X")` if you want the name to be "ONE"?

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org/ for questions
