### ISSUE TITLE
Scala3 bug - type in an anonymous function in method

### ISSUE THREAD

**Issue by tomasherman** [scala/bug#12364]
## reproduction steps
clone https://github.com/tomasherman/netty4s, remove `asInstanceOf` on the [offending line][line] and try to cross compile (`+compile`) 
## problem
The code that compiles under scala2.13 won't compile under scala3 (i hotfixed it with `asInstanceOf` - see [the offending line][line]

The error message is:
```
[error] -- [E007] Type Mismatch Error: /Users/tomas.herman/workspace/netty4s/core/src/main/scala/netty4s/core/server/netty/channel/RoutingChannel.scala:20:88
[error] 20 |      case Action.UpgradeWithWebsocket(handler) => upgradeToWebsocket(ctx, request.uri, handler) // scala3 bug?
[error]    |                                                                                        ^^^^^^^
[error]    |Found:    (handler : netty4s.core.server.api.WebsocketHandler[F$1])
[error]    |Required: netty4s.core.server.api.WebsocketHandler[F]
[error]    |
[error]    |where:    F   is a type in class RoutingChannel with bounds >: F$1 and <: [_$1] =>> Any
[error]    |          F$1 is a type in an anonymous function in method channelRead0 with bounds <: F
[error] one error found
```

[line]: https://github.com/tomasherman/netty4s/blob/e1fbfba2ec77e6141b108e3d36182d47e3fef24a/core/src/main/scala/netty4s/core/server/netty/channel/RoutingChannel.scala#L20

**Comment by smarter** [comment]
- This is the Scala 2 bug trackers, Scala 3 bugs go to github.com/lampepfl/dotty/issues
- As far as I can tell, this is not a bug, the problem is that in https://github.com/tomasherman/netty4s/blob/master/core/src/main/scala/netty4s/core/server/api/Action.scala, `UpgradeWithWebsocket` is defined with an invariant type parameter `F[_]` when its parent trait is defined with a covariant type parameter `+F[_]`, in almost all cases you should align variances between parents and children (either make them both covariant or both invariant). Not doing so will prevent the compiler from inferring equality constraints in some situations. The problem is that Scala 2 is broken and will infer invalid equality constraints so people don't notice this issue until they upgrade to Scala 3.

**Comment by tomasherman** [comment]
thank you :)
