### ISSUE TITLE
-Ymacro-annotations, deprecated case class, lazy val with the same name of case class does not compile

### ISSUE THREAD

**Issue by qiujiangkun** [scala/bug#12366]
The problem is from slick-codegen and `-Ymacro-annotations`. When I enable `-Ymacro-annotations`, my previously working code does not compile.
## reproduction steps

using Scala 2.13.5,

```scala
object Test {
  @deprecated
  class Inner() {
  }

  lazy val Inner = new Inner()
}

```

## problem
When`-Ymacro-annotations` is enabled, code does not compile
```sbt
scalacOptions ++= Seq(
  "-Ymacro-annotations",
)
```
```log
Inner is already defined as (compiler-generated) case class companion object Inner
lazy val Inner = new Inner()
```

**Comment by lrytz** [comment]
I took a breif look; `-Ymacro-annotations` enables a subclass of `Namers` which creates funky self-destroying companion object for annotated classes

https://github.com/scala/scala/blob/8a2cf63ee5bad8c8c054f76464de0e10226516a0/src/compiler/scala/tools/nsc/typechecker/MacroAnnotationNamers.scala#L166

I guess it can be changed so that this companion is not genarted when there's such a lazy val.

**Comment by jxnu-liguobin** [comment]
> I guess it can be changed so that this companion is not genarted when there's such a lazy val.

if doesnot have a lazy will also report an error, which is in line with expectations?
```scala
sandbox/Test.scala:9: error: Inner is already defined as (compiler-generated) case class companion object Inner
   val Inner = new Inner()
```

**Comment by lrytz** [comment]
The cause is the same, whether the val is lazy or not.

Let me give a bit more background. Here is an example without macro annotations, plain Scala:

```
scala> object T { case class C(x: Int); object C }
object T

scala> object T { case class C(x: Int); val C = new {} }
                                            ^
       error: C is already defined as (compiler-generated) case class companion object C
```

When compiling a case class, the compiler generates a "companion" object to generate the `apply` method for example. If the companion already exists (as in the first case), the `apply` method is added to it.

If the companion does not exists, it is created. In case there's already a `val` with the same name, this results in an error (second case).

With macro annotations, the compiler creates a companion object whenever the class has some annotation and there is no companion object already. This causes the same error.

My suggestion: for the case of macro annotations, we could change the compiler so that the companion object is only generated if there is no conflicting value. This would mean that a macro annotation would probably not work correctly in this case though.

**Comment by jxnu-liguobin** [comment]
thanks, I try it as follow:
```scala
    protected def weakEnsureCompanionObject(cdef: ClassDef, creator: ClassDef => Tree = companionModuleDef(_)): Symbol = {
      val m = patchedCompanionSymbolOf(cdef.symbol, context)
      if (m != NoSymbol && currentRun.compiles(m)) m
      else {
        val existsVal = context.tree.children.find {
          case ValDef(_, term, _, _) if cdef.getterName == term  => true
          case _ => false
        }
        if (existsVal.isDefined) NoSymbol else {
          val mdef = atPos(cdef.pos.focus)(creator(cdef))
          enterSym(mdef)
          markWeak(mdef.symbol)
        }
      }
    }
```
and test `test/files/jvm/innerClassEnclMethodJavaReflection.scala` failed, because 
```
(sandbox.Test$Test$,java.lang.IncompatibleClassChangeError: sandbox.Test and sandbox.Test$Test$ disagree on InnerClasses attribute)
(sandbox.Test$MyTest,java.lang.IncompatibleClassChangeError: sandbox.Test and sandbox.Test$MyTest disagree on InnerClasses attribute)

```
