### ISSUE TITLE
Wrong "isInstanceOf[Array[_]]"

### ISSUE THREAD

**Issue by flomebul** [scala/bug#12373]
## reproduction steps

using Scala (add version here),

```scala
scala> 1.isInstanceOf[Array[_]]
val res0: Boolean = false

scala> 1.asInstanceOf[Array[_]]
val res1: Array[_] = 1

scala> (1: Any).isInstanceOf[Array[_]]
val res2: Boolean = false

scala> (1: Any).asInstanceOf[Array[_]]
val res3: Array[_] = 1
```

## problem

Even is `isInstanceOf` return `false`, `asInstanceOf`return something (wrong of course)

**Comment by SethTisue** [comment]
This is working as designed. Please use https://users.scala-lang.org for questions

**Comment by flomebul** [comment]
Oops. I forget that `is...` must be used to prevent a wrong use of `as...` Surry

**Comment by SethTisue** [comment]
no worries! saw your Dotty bug, that one's real

**Comment by SethTisue** [comment]
note that `asInstanceOf[Array[_]]` has surprising (but correct behavior):

```
scala 2.13.5> 1.asInstanceOf[Array[String]]
java.lang.ClassCastException: java.lang.Integer cannot be cast to [Ljava.lang.String;
  ... 32 elided

scala 2.13.5> 1.asInstanceOf[Array[_]]
val res5: Array[_] = 1
```

it's because at the bytecode level, there is no such thing as a generic array. there are only specific array types such as `Array[Int]` and `Array[AnyRef]`. `Array[Int]` and `Array[AnyRef]` have no common supertype, so there's nothing the erasure can be except `AnyRef`. So that's why `asInstanceOf` behaves as it does here; `asInstanceOf` inserts a runtime cast to the erased type, but after `1` has been autoboxed to `java.lang.Integer`, it conforms to `Object`.
