### ISSUE TITLE
Inconsistent initialization order in subclass when using final override and no type annotation

### ISSUE THREAD

**Issue by texasbruce** [scala/bug#12401]
## reproduction steps

using Scala 2.13.x,

```scala
class Creature {
  val range: Int = 100
  println(range)
}

class Ant1 extends Creature {
  override val range = 1
}

class Ant2 extends Creature {
  override val range: Int = 1
}

class Ant3 extends Creature {
  final override val range = 1
}

class Ant4 extends Creature {
  final override val range: Int = 1
}


new Ant1
new Ant2
new Ant3
new Ant4

```

## problem

It outputs:

```
0
0
1
0
```

It should print all `0`s. However when using `final override` and not type annotated, it prints 1

**Comment by som-snytt** [comment]
`final val x = 42` is a ["constant value definition"](https://scala-lang.org/files/archive/spec/2.13/04-basic-declarations-and-definitions.html#value-declarations-and-definitions). So it is inlined everywhere.

As an implementation detail, the accessor does not read the field (which is not yet initialized in the example) but returns the constant.

To me, the confusing part is that your `Ant4` also prints `1` under Scala 3. It's not obvious that this is just a benign optimization. I opened [an issue](https://github.com/lampepfl/dotty/issues/12570), but I don't think they have bandwidth to make fine distinctions, especially since the syntax is replaced by unambiguous `inline` in Scala 3.

As pointed out on discord, the FAQ recommends constant value definition as a workaround for initialization order problems.

**Comment by texasbruce** [comment]
> 
> 
> `final val x = 42` is a ["constant value definition"](https://scala-lang.org/files/archive/spec/2.13/04-basic-declarations-and-definitions.html#value-declarations-and-definitions). So it is inlined everywhere.
> 
> As an implementation detail, the accessor does not read the field (which is not yet initialized in the example) but returns the constant.
> 
> To me, the confusing part is that your `Ant4` also prints `1` under Scala 3. It's not obvious that this is just a benign optimization. I opened [an issue](https://github.com/lampepfl/dotty/issues/12570), but I don't think they have bandwidth to make fine distinctions, especially since the syntax is replaced by unambiguous `inline` in Scala 3.
> 
> As pointed out on discord, the FAQ recommends constant value definition as a workaround for initialization order problems.

I see the bug in dotty, but it is still valid bug for Scala 2 no? The last one should also print 1

**Comment by som-snytt** [comment]
To me, the behavior on this ticket is expected because we ask for a "constant value definition". The last line is not a constant value because of the explicit type. (That is just a quirky bit of syntax.)

I confirmed that Scala 3 does not inline the last case; but it does elide the field and return a constant. I would argue that it shouldn't do that unless we specify "constant value def" or "inline". Also, it is suspicious that it does it if the method is final but not if the class is final. That makes the optimization seem unintended to me.

I know people have asked about whether the compiler should be eliding fields; the use case is reflective access or serialization.
