### ISSUE TITLE
Mutable and immutable sets working in opposite fashion

### ISSUE THREAD

**Issue by sshashan** [scala/bug#12425]
## reproduction steps

```scala
var jetSet = Set("Indigo","Vistara") --->var jetSet: scala.collection.**immutable**.Set[String] = Set(Indigo, Vistara)
jetSet += "KF" 
println(jetSet) --> Set(Indigo, Vistara, KF)
```
Immutable jetSet is created but after adding one element , the original jetSet set is modified instead of returning a new set.

Second case:

```scala
import scala.collection.mutable
val movieSet = mutable.Set("Hitch", "Poltergeist") -->val movieSet: scala.collection.**mutable**.Set[String] = HashSet(Hitch, Poltergeist)
movieSet += "Shrek"
println(movieSet) --> val res38: movieSet.type = HashSet(Hitch, Shrek, Poltergeist)
```

Instead of modifying the original movieSet, it returned a new set

using **Scala 2.13.6.** 

## problem
If we append new element in a mutable set, same set should get modified instead of returning new set.
And if we append new element in an immutable set, same set should not get modified and should return a new set.

**Comment by odd** [comment]
This is working as expected, I believe the problem might be a misunderstand of the meaning of `val` and `var`.

`val`: A name that cannot change what it is referring to (after having been defined).
`var`: A name that can change what it is referring to. 

The difference between a name defined with `val` or `var` is not about the mutability of the value the name refers to but instead about the mutability of the name itself.

In the first case you are defining `jetSet` as a `var` (i.e. a name that can change what it refers to), then you use the `+=` operator to add `"KF"` to it. Here a Scala feature comes into play which rewrites `jetSet += "KF"` to `jetSet = jetSet + "KF"` (since no `+=` method is defined on `immutable.Set` and `jetSet` is a `var`). So the immutable set is not mutated, instead you are getting a new immutable set back from the `+` operation and this returned value is then rebound to the `jetSet` variable.

In the second case you are defining `movieSet` as a `val` (i.e. a name that cannot change what it refers to), then you use the `+=` operator to add `"Shrek"` to it. In this case `mutable.Set` has a `+=` method so that method gets called with the argument `"Shrek"` and returns the same set (but `movieSet` is not rebound since the `+=` was not rewritten as an assignment in this case, even if it was rewritten the rebounding would have failed since `movieSet` is a `val`).  

So in both cases it works as expected.

**Comment by SethTisue** [comment]
@sshashan please use https://users.scala-lang.org for questions
