### ISSUE TITLE
-Wunused:params don't work for unimplemented methods

### ISSUE THREAD

**Issue by gatisnolv** [scala/bug#12592]
## Reproduction steps

Scala version: 2.13.8

```scala
  object Example {
    def unusedImplicit(implicit i: Int) = ???

    def unusedExplicit(i: Int) = ???

    def unusedContextBound[A: Ordered] = ???
  }
```
with the compiler option
`"-Wunused:params"`

(or with `
"-Wunused:explicits",
"-Wunused:implicits",
"-Wunused:synthetics"
`)

## Problem

I expect the unused implicit, explicit and context bound parameters to be reported as 'never used'  for each method respectively, but there are no warnings for these unimplemented methods (so the specific example in the [implementing PR](https://github.com/scala/scala/pull/9346#issue-751107749) does not actually produce warnings, as those methods are also unimplemented with `???`). If the methods are implemented to e.g. return `1`, the expected warnings are produced.

**Comment by SethTisue** [comment]
@som-snytt I feel like I'm vaguely remembering you did this intentionally?

**Comment by som-snytt** [comment]
Yes, that is a long-time feature that was recently augmented under https://github.com/scala/bug/issues/11856

Maybe when the compiler options page is refreshed, linting behavior could be expanded upon, or I guess the word is expatiated. Although there lints that can be selected, the general goal is to avoid many knobs and levers, and find a sweet spot that is useful but not noisy, so that `Xlint` can be ordinarily enabled.

Maybe someone will get back to https://github.com/scala/docs.scala-lang/issues/1711

**Comment by gatisnolv** [comment]
@som-snytt So just to clarify - it's intended behavior, that in the case of unimplemented methods (with '???') these parameters are not being reported as unused, correct?

**Comment by som-snytt** [comment]
> Yes, that is a long-time feature that was recently augmented under https://github.com/scala/bug/issues/11856

**Comment by SethTisue** [comment]
The design justification is that `???` indicates explicit intent on the part of the user not to fill in an implementation.

If that design decision doesn't suit your codebase's needs, consider adding a Scalafix rule (or use Wartremover or whatever) to your build that complains if `???` is ever used at all.

**Comment by gatisnolv** [comment]
Thanks, all clear now.
