### ISSUE TITLE
Range.contains appears to have issues when start is sufficiently negative

### ISSUE THREAD

**Issue by morgen-peschke** [scala/bug#12635]
## Reproduction steps

Scala Version: 2.13.8

```scala
def comment(s: String): Unit = {
  println()
  println(s)
}

def check(r: Range) = {
  val rejected = r.toList.filterNot(r.contains)
  println(s"$r does not contain $rejected")
}

comment("I'm not sure what makes this Range special, as an org.scalacheck.Gen[Range] I'm working on produced it.")
val testCase = Int.MinValue until 1092265081 by 359972081

comment(s"$testCase is small, and only contains a few elements:")
println(s"testCase: ${testCase.toList}")

comment("Expectation: a range will contain every value it produces, so check should produce List()")
check(testCase)

comment("Attempting to minimize the problematic range starts correctly identifying some of the elements, but doesn't fully solve the issue")
check(testCase.drop(1))
check(testCase.drop(2))

comment("I'm not sure why -1067567405 is the threshold at which it starts working again")
check(testCase.drop(3))

comment("Quick check using Interator.iterate to verify that Range.toList is not the issue:")
println(Iterator.iterate(Int.MinValue)(_ + 359972081).take(9).toList)

comment("Eliminating the range's gap doesn't change the behavior")
check(testCase.start to testCase.last by testCase.step)

comment("Likewise, switching `until` for `to` doesn't change the behavior")
check(testCase.inclusive)
```

Reproduced using Scastie for versions:
- [3.1.3](https://scastie.scala-lang.org/2DZzoW75R6eaAM5tpbbIog)
- [2.13.8](https://scastie.scala-lang.org/a8vEyjT1RfyMqvwSBGRK4Q)
- [2.12.16](https://scastie.scala-lang.org/8ViIH4xNSmGLk0wV71LhwA)
- [2.11.12](https://scastie.scala-lang.org/BjQtR73fSlu6eyFPl8DMYQ)

### Reproduction Output
```
I'm not sure what makes this Range special, as an org.scalacheck.Gen[Range] I'm working on produced it.

Range -2147483648 until 1092265081 by 359972081 is small, and only contains a few elements:
testCase: List(-2147483648, -1787511567, -1427539486, -1067567405, -707595324, -347623243, 12348838, 372320919, 732293000)

Expectation: a range will contain every value it produces, so check should produce List()
Range -2147483648 until 1092265081 by 359972081 does not contain List(12348838, 372320919, 732293000)

Attempting to minimize the problematic range starts correctly identifying some of the elements, but doesn't fully solve the issue
Range -1787511567 until 1092265081 by 359972081 does not contain List(372320919, 732293000)
Range -1427539486 until 1092265081 by 359972081 does not contain List(732293000)

I'm not sure why -1067567405 is the threshold at which it starts working again
Range -1067567405 until 1092265081 by 359972081 does not contain List()

Quick check using Interator.iterate to verify that Range.toList is not the issue:
List(-2147483648, -1787511567, -1427539486, -1067567405, -707595324, -347623243, 12348838, 372320919, 732293000)

Eliminating the range's gap doesn't change the behavior
Range -2147483648 to 732293000 by 359972081 does not contain List(12348838, 372320919, 732293000)

Likewise, switching `until` for `to` doesn't change the behavior
Range -2147483648 to 1092265081 by 359972081 does not contain List(12348838, 372320919, 732293000, 1092265081)
```

## Problem
`Range.contains` produces false negatives for several elements that it should contain, based on `Range.toList` and reproducing the stepwise calculation manually (see `res0` and `res5`).

**Comment by SethTisue** [comment]
@scala/collections ?

**Comment by sjrd** [comment]
This is the problematic line:
https://github.com/scala/scala/blob/1d1b6d748136b3b02861a2ad9372021dd7dc6e01/src/library/scala/collection/immutable/Range.scala#L376

When `start` is a sufficiently large negative number and `x` is a sufficiently large positive number, `x - start` can overflow.

There's the same issue in the case `step < 0`.

**Comment by som-snytt** [comment]
Someone who is in the office in Lausanne needs to change the sign which says

> It has been _8 1/2_ years since Range.contains is wrong https://github.com/scala/bug/issues/6736

That is since the fix; we didn't quite make it a decade since the last issue was raised.

**Comment by Ichoran** [comment]
Oh bother.  I should have caught this when I rewrote it last time.  (It was there before...I caught other things, but not this.)  `posOf` is also wrong.

If we are allowed to use Java 8's Integer.remainderUnsigned, then it's easy: `Integer.remainderUnsigned(x - start, step) == 0`.  (Use `divideUnsigned` for `posOf`.)

If not, then maybe we're allowed to use `Long` this time, at least with a conditional?  (I think we were trying to avoid `Long` because of JS?)

```scala
val y = x - start
if y >= 0 then (x - start) % step == 0
else (x.toLong - start) % step == 0
```

**Comment by sjrd** [comment]
I don't see why we couldn't use `remainderUnsigned`. Both Scala.js and Scala Native support it.

**Comment by morgen-peschke** [comment]
It looks like `NumericRange.containsTyped` has the same behavior, should that be handled as part of this issue, or should I file a separate bug?

**Comment by SethTisue** [comment]
I'd say this ticket can cover both

**Comment by Ichoran** [comment]
> It looks like `NumericRange.containsTyped` has the same behavior, should that be handled as part of this issue, or should I file a separate bug?

Oh, good call.  That's a tricky one.  There are lots of issues to consider there, including numeric precision and whether modulus of a negative number is negative or positive.

I don't have time to write code (even pseudocode) that I'm confident in right now.  The strategy in general would be to break up the range into chunks: from start (which must be negative if we're going forward--one needs to write the backwards case also with the signs flipped) to check from start to start + floor(abs(start + 1)/step)*step; if you're in that range you either hit the endpoint or can use the naive algorithm.  If you're not in that range, consider 0 to last, also with the naive algorithm.  I think that hits everything: the first range covers every negative value, the second zero through any positive value.

If division might be imprecise, you'd need a little bit of extra logic to be sure you didn't spill over or under your bounds and fix it up otherwise.  (In particular, `start + ...` should still be negative, but it should be greater than or equal to `-step`.)

Either way, I recommend that we fix it all at the same time (both `Range` and `NumericRange`).
