### ISSUE TITLE
Missing "unused import" warning when implicit is considered but discarded

### ISSUE THREAD

**Issue by lrytz** [scala/bug#12690]
With `-Wunused`:

```scala
class X
class Y extends X
object A { implicit val x: X = new X }
object B { implicit val y: Y = new Y }
class C {
  import B._
  import A._ // missing unused warning
  def t = implicitly[X]
}
```

Both implicits are eligible. During ranking to find the best one, a reference to each is type checked and a usage is recorded.

Swapping the two imports makes the "unused import" warning show.

**Comment by som-snytt** [comment]
> Previously, implicit search would mark every import it touched as a lookup.
> Instead, let subsequent type check perform the lookup.

https://github.com/scala/scala/pull/4616

This isn't directly relevant but demonstrates fragility https://github.com/scala/bug/issues/11690

The macro writers have wanted the ability to mark elements as used.

**Comment by som-snytt** [comment]
More amusing buried history:

> Per review, adds a function that clarifies the purpose
of the code path that collects imported implicits,
namely, to examine qualifying imported implicits and
then collect them. In the context of doing something
with the import (besides importing), it's clear why we
don't want to record that we used the import, that is,
because we might be doing something other than using.
>
> That's clear, right?

What's clear is that the attempt was to thread a flag whether to "record usage", instead of locating the multiple points in the code where a symbol is used after lookup. `importedSelectedSymbol` is the API to help bubble up the (implicit) symbol with its import selector.

**Comment by som-snytt** [comment]
This is a good error message, in the middle of refactoring:
```
[error] .../scala/src/compiler/scala/tools/nsc/typechecker/Contexts.scala:1099:79: value ::= is not a member of List[Contexts.this.ImplicitInfo]
[error]   Expression does not convert to assignment because:
[error]     not found: value sym
[error]     expansion: impls = impls.::(ImplicitInfo(to, pre, <sym: error>, imp, selector))
[error]           def addSelected(selected: Symbol, selector: ImportSelector) = impls ::= ImplicitInfo(to, pre, sym, imp, selector)
[error]                                                                               ^
```
Scala 2 messaging improvements went largely unappreciated.

**Comment by som-snytt** [comment]
Reminder in the dotty PR, the implicit knows its import, which is marked used on success.

https://github.com/lampepfl/dotty/pull/14524/files#diff-f4cd371ae1b557102e0cd0737061b10774664632f355696846f30bedfd5d696bR45
