### ISSUE TITLE
REPL doesn't report op= mutations

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12894]
## Reproduction steps

Scala version: 2.13

```scala
scala 2.13.12> var x = 42
var x: Int = 42

scala 2.13.12> x = 17
// mutated x

scala 2.13.12> x += 10

scala 2.13.12> x
val res1: Int = 27
```

## Problem

It should say that x was mutated by assignment `+=`.

**Comment by SethTisue** [comment]
This would be a good little starter project for somebody, either in Scala 2 or Scala or both.

In Scala 3 (3.4.0-RC3), instead of "mutated x" it actually shows the new value, which seems like a better design.

But Scala 3 also fails to handle `+=` and friends the same way it handles plain assignment

```
scala> var x = 42
var x: Int = 42
                                                                                                    
scala> x = 20
x: Int = 20
                                                                                                    
scala> x += 10
                                                                                                    
scala> 
```
