### ISSUE TITLE
sbt publishLocal fails with javadoc: error invalid flag -s

### ISSUE THREAD

**Issue by hillol-pal** [scala/bug#12891]
## Reproduction steps
I have a play project with below scala and sbt version
scala version 2.12.15
sbt: 1.6.2 
java Version : 1.8 Openjdk

sbt publishLocal fails with Unexpected javac output: javadoc: error - invalid flag: -s

## Problem

Added following to build.sbt to prevent doc generation 

Compile / doc/ sources := Seq.empty
Compile /packageDoc / publishArtifact :=true

But it seems it had no effect and keeps giving me the error

Appreciate your help on the same.

**Comment by eed3si9n** [comment]
Hi, I think this is the wrong forum to discuss this since scala/bug is used for tracking bugs in Scala compiler and standard libraries, and the issue likely has nothing to do with Scalac.

At the bottom of https://www.playframework.com/ there's a section called community support, where you might have better luck.
