### ISSUE TITLE
default value ignored in @main

### ISSUE THREAD

**Issue by iomedico-beyer** [scala/bug#13001]
## Reproduction steps

Scala version: 3.4.2

```@main def main(mode: String = "foo"): Unit = ???```

At runtime: 
> Illegal command line: more arguments expected

## Problem

- Please either support default values in @main 
- or exit compilation with an error (to fail fast).

**Comment by som-snytt** [comment]
> (Is the bug only in Scala 3.x? If so, report it at [scala/scala3](https://github.com/scala/scala3/issues/new/choose) instead.)

Please open at scala3.

**Comment by iomedico-beyer** [comment]
Sorry, but this is somewhat confusing to me. What is this project for then?

**Comment by SethTisue** [comment]
Scala 3 ticket is https://github.com/scala/scala3/issues/20485

@som-snytt one of the benefits of having Scala 3 now at scala/scala3 (instead of lampepfl/dotty) is that we can transfer issues between repos in the same organization. so we could have just transferred this rather than requiring the reporter to open a new ticket. perhaps you have access to transfer issues yourself? if so, feel free to do so when appropriate. if not, feel free to @-mention me to ask for a transfer.

"Transfer issue", if you have access to it, is in the bottom right:

<img width="258" alt="Screenshot 2024-05-28 at 9 55 00 AM" src="https://github.com/scala/bug/assets/161079/6ab4e793-2f70-4365-b485-9c48731d3aeb">

**Comment by som-snytt** [comment]
@SethTisue thanks, I missed orientation. @iomedico-beyer sorry for the extra work! I totally forgot about the org change obviating the new ticket. And here I thought I was being so Seth.
