### ISSUE TITLE
Scalac should remove comments before translating unicode escapes

### ISSUE THREAD

**Issue by scabug** [scala/bug#3220]
Consider this code:
```scala
object LinePrinter {
  def main(args: Array[String]){
    // Note: \u000A is Unicode representation of linefeed (LF)
    val c: Char = 0x000A
    print(c)
  }
}
```
This code does not compile, giving the following error method:

```scala
LinePrinter.scala:3: error: not found: value is
  // Note: \u000A is Unicode representation of linefeed (LF)
                  ^
one error found
```

The problem is that the compiler transforms unicode escapes before removing the comments, leading to the following code given to the next compile phase:

```scala
object LinePrinter {
  def main(args: Array[String]){
    // Note:
 is Unicode representation of linefeed (LF)
    val c: Char = 0x000A
    print(c)
  }
}
```

This feature/bug is described in the Java book "Java Puzzlers" (see the sampler, it is Puzzle 2) as "thoroughly confusing". Corresponding Java spec is [JLS 3.4].

I would like to suggest removing lines of comments before converting escapes, because how it works now is highly surprising and unexpected.

**Comment by SethTisue** [comment]
this has been raised again at https://ashannon.us/articles/scala-comment-exec.html

I think if we went around on this again in 2018, the outcome might be different than the 2010 outcome. personally, I'd support a deprecate-then-remove on this.

**Comment by som-snytt** [comment]
I didn't read the long parts, but `\\` is the dual of `//`

```
trait T {
  def s = "\u000A"    // \\u000A is the bomb
}
```

**Comment by martijnhoekstra** [comment]
What's the process here @SethTissue? SIP? It needs a spec change and I guess a deprecation cycle.

**Comment by Ichoran** [comment]
I think it should just be done away with, with no deprecation, and only a migration tool.

As if comments weren't enough of a problem, there are a variety of other surprising behaviors and undesirable possibilities.

Problems include:

First, the feature enables difficult-to-understand variants of common code patterns:

```scala
val sq = (x: Int) \u21D2 x * x
val i\u006ec = (x: Int) => x + 1
va\u0072 x = 7  // Am I mutable?
```

None of these add any value at all.  If they are there, it's probably a mistake.

Secondly, we have the comment issue, as previously addressed:

```scala
// Maybe you should try \u000a println("Ha ha, you already tried it!")
```

Thirdly, string literals have rather non-intuitive behavior (meaning that they're not really literal):

```scala
scala> """\n"""
res11: String = \n

scala> """\u000A"""
res12: String =
"
"scala> """\\u000A"""
res13: String = \\u000A

scala> """\\\u000A"""
res14: String =
"\\
"
```

Note that this behavior means you can't actually write the text of a unicode escape into a raw string in any straightforward way, which is especially weird since you'd expect it to be easiest there.

Fourth, unlike decades ago, UTF-8 is ubiquitous.  You can just insert the character you care about in the code if you need it, greatly assisting readability.

```scala
// Which is better?
val jérôme = 7
val j\u00e9r\u00f4me = 7
```

Fifth, there is no reason why late interpolation can't insert as many non-ASCII unicode characters as your heart desires into strings, characters, and backticked identifier names, and any existing instances should be able to be automatically translated.

So I don't see any reason to keep it as it is for any cycles at all.  It facilitates unclear code, presents difficulties for catching malicious code, creates irregularities in raw string processing, is useless in its full generality, and can be automatically converted anywhere UTF-8 or UTF-16 are allowed (which is approximately everywhere--and a compiler flag could be used to rescue people who are irreversibly attached to Windows-1252).

**Comment by SethTisue** [comment]
> What's the process here @SethTisue? SIP? It needs a spec change and I guess a deprecation cycle.

When something is a lot of work to implement, then involving the SIP committee first can save work, if something is just going to end up being rejected. But it also costs time.

This one probably isn't much work to implement, so I'd suggest that someone simply submit a pull request (and yes, best if it includes a spec change). If the pull request becomes contentious, a SIP might eventually be asked for. Often that doesn't happen and the PR can just be merged.

Even if a SIP does end up being asked for, it's still good to have the pull request in hand, because every SIP ultimately needs an implementation, and anyway having a green pull request to refer to makes any discussion so much more grounded and concrete.

**Comment by SethTisue** [comment]
Calling attention to the issue on https://contributors.scala-lang.org can help rally support

**Comment by SethTisue** [comment]
fyi @adamdecaf

**Comment by som-snytt** [comment]
Is there a label for `won't fix without a fight`?

**Comment by adamdecaf** [comment]
Thanks for bumping the bug related to this. I couldn't quite find one. As @Ichoran pointed out unicode escapes often cause more problems than they fix and as we've seen can lead to problematic code. 

I'll help where I can to get this pushed through. Just let me know!

**Comment by martijnhoekstra** [comment]
> Calling attention to the issue on https://contributors.scala-lang.org can help rally support. Or unexpected opposition, but if that's coming, you might as well find out :-)

https://contributors.scala-lang.org/t/escaping-unicode/1894

**Comment by SethTisue** [comment]
@martijnhoekstra I think this can go forward if you're still interested

(if you don't plan to tackle it, also let us know, since perhaps someone else would step up)

**Comment by ashawley** [comment]
I ran in to this and added some tests to document the status quo https://github.com/scala/scala/pull/6501

I didn't know about this ticket.  I guess the files should be renamed to `t3220`, since `u000a` is cryptic.

**Comment by martijnhoekstra** [comment]
Oh dear, I missed the ping on this one. I'll get back on this

**Comment by martijnhoekstra** [comment]
Status update: Needs to be ported to dotty too, to prevent progression regressing again when dotty becomes scala 3.

**Comment by som-snytt** [comment]
> since u000a is cryptic.

It's `u` for `unit test`. Let's rename all the tests from `t` to `u`. And convert decimal bug numbers to hex, which will make them much easier to read. PR soon. 

I'll also look for any old tests named `bugNNNN`.

**Comment by ashawley** [comment]
> Needs to be ported to dotty too, to prevent progression regressing again when dotty becomes scala 3.

There's isn't a broader initiative to update Dotty with Scala 2.13 tests?  I know they just updated the collections in Dotty with what's in 2.13.0.  Hopefully, the tests will get refreshed as well at some point.

**Comment by ashawley** [comment]
> Let's rename all the tests from `t` to `u`. And convert decimal bug numbers to hex, which will make them much easier to read.

I agree.  This is what the people want.

**Comment by martijnhoekstra** [comment]
@ashawley it's the fix that needs to be ported to dotty, not the test.

Well, also the tests, I suppose.

**Comment by som-snytt** [comment]
smarter recently made a plea for ongoing syntax tweaks in Scala 2 to get fixes in dotty. We might consider an umbrella ticket in dotty to track these differences?

**Comment by martijnhoekstra** [comment]
Tracking them is nice, but someone still needs to implement. A situation where migrating to scala 3 means regressing in recent changes in scala 2 makes for a terrible migration story. Being able to point at an umbrella ticket doesn't change that.

Dotty being the ruggedly handsome swashbuckling research compiler making bold forays into uncharted territory may need a lot of convincing that these kinds of boring syntax changes are worthy of it's time.

**Comment by eed3si9n** [comment]
Did we make 

```scala
scala> def \u0061 = "foo"
a: String
```

illegal in a patch release? Until 2.13.2, this was the second paragraph of [the Scala Language Spec](https://scala-lang.org/files/archive/spec/2.12/01-lexical-syntax.html):

> In Scala mode, _Unicode escapes_ are replaced by the corresponding Unicode character with the given hexadecimal code.

**Comment by SethTisue** [comment]
@eed3si9n https://github.com/scala/scala/pull/8282
