### ISSUE TITLE
explicit case class companion does not extend Function / override toString

### ISSUE THREAD

**Issue by scabug** [scala/bug#3664]
When explicitly defining the companion object of a case class, the compiler does not add a `FunctionN` parent and does not override `toString`.

working as expected:

```scala
scala> object u { case class C(x: Int) }
defined module u

scala> u.C
res1: u.C.type = C

scala> val f: Int => u.C = u.C
f: (Int) => u.C = C

scala> 

```

unexpected:
```scala
scala> object t { object C; case class C(x: Int) }
defined module t

scala> t.C
res0: t.C.type = t$$C$$@5e58a983

scala> val f: Int => t.C = t.C
<console>:6: error: type mismatch;
 found   : t.C.type (with underlying type object t.C)
 required: (Int) => t.C
       val f: Int => t.C = t.C
                             ^
```

**Comment by HuStmpHrrr** [comment]
hi all, yet another case. this is a fundamental mistake, no? we either shouldn't inherit `FunctionX` or inherit it automatically, shouldn't we? this looks entirely inconsistent.

**Comment by S11001001** [comment]
@HuStmpHrrr It's hard to say. It's inconsistent, and a frequent gotcha, but the obvious solutions have problems.

*Never extend function type*: Well, this is just piling on the inconvenience. Thanks but no thanks.

*Extend function type even when explicitly defining `object`*: This is the most intuitive behavior, and probably what you want 95% of the time. But it's not all sunshine and roses: what if you *don't* want to extend the function type? What if you want to extend the function type, but at different type parameters?

```scala
case class Foo(b: Bar)

object Foo extends (Baz => Foo) {
  def apply(bz: Baz): Foo = apply(bazToBar(bz))
}
```

This is a direct example, but you might also be extending the function type indirectly, via extending some other trait you wish your `object` to extend. This would not compile if the `case class` machinery insisted on a `Bar => Foo` superclass (depending on `Bar`/`Baz`'s subtyping relationship, of course).

It just so happens that, in the absence of any syntax saying you *don't* want the function extend, the syntax for saying so is to declare the `object` explicitly without the function extend. So the 5% case is the default, the 95% case is more verbose, but at least you can do everything you might need to.

**Comment by som-snytt** [comment]
One proposal to signal `don't extend FunctionN` is to supply a private `apply` with the matching signature. A linter for unused members would probably want to ignore that use case.

**Comment by hmemcpy** [comment]
I just ran into this by attempting to use `tupled`:

```scala
case class Person(name: String, age: Int)
val p = ("Abe", 42)
```

Calling:
`Person.tupled(p)` works when there's no companion object for `Person`.

Would really love to see this fixed.

**Comment by HuStmpHrrr** [comment]
wow this issue is still open.

one potential fix I can come up with is to add a piece of syntax so that intention is revealed properly. for example,

```scala
case class Person(name: String, age: Int)
object Person {
// something
}
```

this creates a `Person` companion object which does not have any builtin function etc.

imagine the syntax is augmented:

```scala
case class Person(name: String, age: Int)
extend object Person {
// something
}
```

in this imaginary case, the `something` inside is added into the companion object.

in general, the fact that we are not able to add additional functionality to companion objects is quite absurd imo.

**Comment by Jasper-M** [comment]
> the fact that we are not able to add additional functionality to companion objects is quite absurd

But you can. Everything that you write in the body of `object Person { ... }` is effectively added to the `Person` companion object _in addition to_ the generated `apply` and `unapply` methods. Only the `FunctionN` supertype is not automatically added.

The weird thing is this:

```
scala> case class Foo(); object Foo
class Foo
object Foo

scala> Foo.isInstanceOf[Serializable]
val res4: Boolean = true

scala> object Bar // not a companion object
object Bar

scala> Bar.isInstanceOf[Serializable]
val res5: Boolean = false
```

The `Serializable` supertype _is_ added even to the custom companion object. Wouldn't it be possible to also automatically add the `FunctionN` parent iff the custom companion object still has a public compatible `apply` method?

**Comment by HuStmpHrrr** [comment]
I guess @hmemcpy just mentioned that `tupled` doesn't work? probably only `apply` and `unapply` are special?

there is a good reason to believe these two functions are special too.

in any case, it's always good to have syntax to distinguish intentions, otherwise once it's "fixed", someone else is going to complain.

**Comment by som-snytt** [comment]
Folks were still commenting here a year after the matter was settled at https://github.com/lampepfl/dotty/issues/6190.

Note that the companion extended `runtime.AbstractionFunction`, which matters for N <= 2 because of specialization.

It would be or have been nice to balk only at mixing in traits where it is expensive, imposing the parent class where feasible.

The dotty solution includes eta-expanding `C.apply`.
