### ISSUE TITLE
2.9.0 compiler crash with scala.tools.nsc.symtab.Symbols$CyclicReference: illegal cyclic reference involving method ...

### ISSUE THREAD

**Issue by scabug** [scala/bug#4612]
[Edited to minimize.]

The following code crashes the 2.9.0 compiler, with "scala.tools.nsc.symtab.Symbols$CyclicReference: illegal cyclic reference involving method ..."

```scala
class CyclicReferenceCompilerBug {
  trait Trait[A] {
    def foo: A
  }
  
  class Class extends Trait[Class] {
    def foo = new Class
    
    trait OtherTrait extends Trait[OtherTrait] { 
      self: Class =>
      
      def foo = new Class
    }
  }
}
```

**Comment by diesalbla** [comment]
I have tried the code on the Scala console. It no longer crashes. 
```
 Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)
*******************
// Exiting paste mode, now interpreting.

<console>:22: error: type mismatch;
 found   : CyclicReferenceCompilerBug.this.Class
 required: _1
             def foo = new Class
                       ^
```

This is somehow expected behaviour. The second call should fail, because since `Cris` extends `Ann[Cris]`, it follows that `Cris.foo` should have type `Cris`, but a `new Bob` is not an instance of `Cris`. Not sure, however, is something can be done about the `_1` symbol.

**Comment by SethTisue** [comment]
@diesalbla yeah the error message isn't optimal but I don't think it's worth keeping this ticket open over it. thanks for checking on this, triaging old tickets like this is highly welcome!
