### ISSUE TITLE
For loops with -optimize have much worse performance than while loops

### ISSUE THREAD

**Issue by scabug** [scala/bug#4633]
According to Tiark Rompf, "With -optimize, scalac should compile simple for comprehensions to the equivalent of a while loop. If it does not it's a bug (either in the library or in the compiler) and it needs fixing. So if there is indeed a bug, gather solid performance numbers [and] submit a ticket"

Here are performance numbers for loops nested 1, 3, 5, or a variable number of levels deep; in every case, the innermost operation occurs one billion times.  The leftmost number is a checksum (the first three should be the same; the fourth is different):

// These are while loops
-1243309312 While1 Elapsed: 0.314 s
-1243309312 While3 Elapsed: 0.301 s
-1243309312 While5 Elapsed: 0.316 s
-17609343 While? Elapsed: 1.151 s

// These are for loops with ranges
-1243309312 Limit1 Elapsed: 0.923 s
-1243309312 Limit3 Elapsed: 0.885 s
-1243309312 Limit5 Elapsed: 2.527 s
-17609343 Limit? Elapsed: 3.308 s

// These use a C-for-like-method that takes an anonymous function
// Note that the JVM gets confused about how to optimize repeated uses
-1243309312  Cfor1 Elapsed: 9.794 s
-1243309312  Cfor3 Elapsed: 0.324 s
-1243309312  Cfor5 Elapsed: 0.450 s
-17609343 Cfor?? Elapsed: 5.662 s

Code is attached.

**Comment by SethTisue** [comment]
why is this a separate ticket from #1338? (no reason?)

**Comment by som-snytt** [comment]
This ticket was for the [Tiark Challenge](https://www.scala-lang.org/old/node/9637), you had to create a ticket with solid numbers in order to get a t-shirt. On the back it said, "Rompf in the Swampf".

Previous to that was the [Paulp-off](http://scala-programming-language.1934581.n4.nabble.com/optimizing-simple-fors-td2545502.html).

The conversations (including the links here) follow similar twists and turns from quick optimizations to plugins to areas of research.

With `-optimize` or equivalent:
```
[info] Running ForWhile 
version 2.12.8
[snip]
while range 1   : -536870912 took  0.547 s
while range 2   : -536870912 took  0.549 s
while array 1024: -536870912 took  0.593 s
for   range 1   : -536870912 took  0.547 s
for   range 2   : -536870912 took  0.553 s
for   array 1024: -536870912 took  4.422 s

[info] Running ForWhile 
version 2.13.0
[snip]
while range 1   : -536870912 took  0.546 s
while range 2   : -536870912 took  0.548 s
while array 1024: -536870912 took  0.591 s
for   range 1   : -536870912 took  0.546 s
for   range 2   : -536870912 took  0.548 s
for   array 1024: -536870912 took  0.595 s
```
Probably additional issues for 2.13 would require a more narrowly-scoped ticket.
