### ISSUE TITLE
final and immutable members are accessed via invokevirtual instead of getfield

### ISSUE THREAD

**Issue by scabug** [scala/bug#4689]
The following code when compiled with Scala version 2.9.0-1 yields a different bytecode when compared to previous versions.

```scala
final class AtomTest(vIn:Int) {
      final val v = vIn       
      def square = v*v
}
```

For the method "square":
Scala 2.7.7 and 2.8.1 with -optimise :
```scala
public int square();
  Code:
   0:   aload_0
   1:   getfield        #12; //Field v:I
   4:   aload_0
   5:   getfield        #12; //Field v:I
   8:   imul
   9:   ireturn
```

Scala 2.9.0-1 with -optimise:
```scala
public int square();
  Code:
   0:   aload_0
   1:   invokevirtual   #14; //Method v:()I
   4:   aload_0
   5:   invokevirtual   #14; //Method v:()I
   8:   imul
   9:   ireturn
```

Note that invokevirtual is now being generated for field access.

I don't have a benchmark to prove that this degrades performance, for two reasons:
- A simple one class benchmark will get instantly optimised by JIT and will not show any degradation
- I have some production code which does run slowly with Scala 2.9.0-1 but there might be other factors affecting the performance of that code. For example, there seems to be a known degradation in Hashset addition method which my production code uses frequently.

**Comment by SethTisue** [comment]
2.12 still generates the `invokevirtual` calls

**Comment by harpocrates** [comment]
This also happens in 2.13 and unsurprisingly also affects `putfield`:

```scala
class Test(final var foo: Int) {
  def baz(): Unit = {
    foo = foo * 3 + 1
  }
}
```

turns into

```
  public void baz();
    Code:
       0: aload_0
       1: aload_0
       2: invokevirtual #22                 // Method foo:()I
       5: iconst_3
       6: imul
       7: iconst_1
       8: iadd
       9: invokevirtual #24                 // Method foo_$eq:(I)V
      12: return
```

AFAICT, if the field is `final` or `private` all gets and sets within the class could safely be switched to `getfield` and `putfield`. Is this correct? If so, I might take a stab at fixing this.

**Comment by lrytz** [comment]
I'm not convinced we should do this. If the field is non-`private[this]` there's an intention to have it accessible outside the class, and those have to keep using the accessors (to allow binary compatible refactoring). Using direct field access only within the class seems like an ad-hoc optimization.

The fact that the inliner (`-opt:l:inline`) doesn't inline getters / setters [is by design](https://github.com/scala/scala/blob/d89a951114edce13c5122326afef067d7a93b4fd/src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala#L347). The reason is that inlining accessors can prevent further inlining / optimization, for example:


```scala
class C {
  var x = 0
  def mogrify(f: Int => Int): Unit = x = f(x)
}
object T {
  def foo = {
    val c = new C
    c.mogrify(_ + 10)
    c.x
  }
}
```

If you compile the above with `-opt:l:inline '-opt-inline-from:**'`, the result is (cfr-decompiler):

```java
public class T {
    public int foo() {
        C c = new C();
        c.x_$eq(c.x() + 10);
        return c.x();
    }
}
```

Now if you enforce the getter `x` to be inlined

```scala
  def mogrify(f: Int => Int): Unit = x = f(x: @inline)
```

then `mogrify` directly accesses the private field `x`, and it can therefore no longer be inlined into class `T`, doing so would cause an `IllegalAccessError` (`-Vinline _` tells you that).

So the result is

```java
public class T {
    public int foo() {
        C c = new C();
        c.mogrify((Function1<Object, Object>)(JFunction1.mcII.sp & Serializable)x$1 -> x$1 + 10);
        return c.x();
    }
}
```

So I suggest we keep this as they are and close this ticket.

**Comment by harpocrates** [comment]
This makes sense, thanks for explaining the motivation.
