### ISSUE TITLE
java.lang.ClassFormatError in scala/actors/scheduler/ResizableThreadPoolScheduler after building scalac with -Xexperimental

### ISSUE THREAD

**Issue by scabug** [scala/bug#5150]
Steps to reproduce:

git checkout upstream/master
ant -Dscalac.args.quickonly=-Xexperimental dist

Fails when starting partest:
```scala
[...]
dist.done:

test.suite:
  [partest] Compiling files that are expected to build

BUILD FAILED
/home/jordi/workspace/scala/build.xml:48: The following error occurred while executing this line:
/home/jordi/workspace/scala/build.xml:1563: java.lang.ClassFormatError: Illegal class modifiers in class scala/actors/scheduler/ResizableThreadPoolScheduler: 0x419
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
[...]
```

Full build log is attached.

**Comment by magnolia-k** [comment]
The -Xexperimental option has been deprecated since Scala 2.13.0, so the issue itself can be closed.

Also, Scala's actor class has been removed from Scala 2.12.

**Comment by som-snytt** [comment]
I don't think this ticket can be closed on that basis. "Removing -Xexperimental" also means experimental options became standard behavior, not that the behavior was removed. Too bad the example code was not self-contained here.

Compare https://github.com/scala/bug/issues/7970 for same error, different modifiers. That code does actually run on 2.12. Does that mean it was fixed?

Alternatively, "this ticket is so old that if it's still an issue, someone will report it again eventually, and probably not on Scala 3 unless it's an old backend issue because Scala 3 has old backend."

**Comment by joroKr21** [comment]
> Too bad the example code was not self-contained here.

Unless you want to dig up the old source of that file 😄 
But I think even without doing that there is not really a reason to keep it open.
