### ISSUE TITLE
Add ProcessLogger use case example to scaladoc

### ISSUE THREAD

**Issue by scabug** [scala/bug#5243]
It is too hard to understand how to use ProcessLogger without a clear example use case.

**Comment by ilango123** [comment]
@scabug can you tell me why this bug is open. I beg your pardon, I am trying to be a contributor and chose this to be a place to start. 
For example, in https://www.scala-lang.org/api/current/scala/Option.html, there are code examples that demonstrate a use-case for Option.
Are we looking for something similar for ProcessLogger? I noticed there is an example, in the source code for ProcessLogger from 2.11.8.  For instance, if that example were to be shown on the ProcessLogger documentation page, would that be enough to close this bug? 
Please advise.

**Comment by SethTisue** [comment]
> could you throw a little more light on why this bug is open?

(possibly no reason — one form of participation that's really helpful in this repo is simply to identify tickets that shouldn't remain open)

> For example, in https://www.scala-lang.org/api/current/scala/Option.html, there are code examples that demonstrate a use-case for Option.
> Are we looking for something similar for ProcessLogger? I noticed there is an example, in the source code for ProcessLogger from 2.11.8.
> For instance, if that example were to be shown on the ProcessLogger documentation page, would that be enough to close this bug?
> Please advise.

That example is in a Scaladoc comment, so it appears in the API doc as well. If you're not seeing it, it could be because you're looking at the doc for the `ProcessLogger` companion object instead of for the trait. The big "T" and "O" flip back and forth. http://www.scala-lang.org/api/2.12.2/scala/sys/process/ProcessLogger.html

It appears to me that this ticket predates scala/scala@838c97bcb55908aff3638caae0aa87d237100b4b, the commit that added the example in question, and this should have been closed when that was merged. Closing.

**Comment by ilango123** [comment]
You are right. I was looking at the doc for the Companion object instead of for the trait.  Glad it is closed now.
