### ISSUE TITLE
OffsetPosition in scala.util.parsing.input does not support mac line endings (\r)

### ISSUE THREAD

**Issue by scabug** [scala/bug#5669]
OffsetPosition currently only looks for \n when calculating line breaks, causing files with mac line endings to appear as 1 enormously long line.  This is similar to the problem described in #2543, but in OffsetPosition instead of Source.

**Comment by SethTisue** [comment]
@SethTisue said:
The parser combinators library is now community-maintained. Issues with it are now tracked at https://github.com/scala/scala-parser-combinators/issues/61 instead of here in the Scala JIRA.

Interested community members: if you consider this issue significant, feel free to open a new issue for it on GitHub, with links in both directions.
