### ISSUE TITLE
Compose Orderings

### ISSUE THREAD

**Issue by scabug** [scala/bug#5961]
There is no way to compose an Ordering, given 2 simpler orderings.

For example:

```scala
case class Pair(x: Int, y: Int)
```

it would be useful to be able to do:

```scala
implicit val pairOrdering = Ordering.by[Pair, Int](_.x).compose[Pair, Int](Ordering.by[Pair, Int](_.y))
```

where the second ordering is triggered only if the first one returns `0`.

**Comment by NthPortal** [comment]
I have already written appropriate methods to do this [here](https://github.com/NthPortal/extra-predef/blob/v1.1.0/src/main/scala/com/nthportal/package.scala#L81-L215), and I am interested in submitting the code to the Scala library.

I chose the method name based on the methods `Ordering.by` and Java's `Comparator.thenComparing`, but I am open other names.

If you wish me to submit it, to which branch should I PR?

**Comment by Ichoran** [comment]
Ow.  That is an ugly method name.  How about simply `orElse` like most of the chaining operators?  Or something else direct and clear (e.g. `tiebreaker` or `orIfSame`).

**Comment by ritschwumm** [comment]
+1 for orElse https://github.com/ritschwumm/scutil/blob/6548cb467b3b3b04621364cf77af8a5af44e0197/sub/base/src/main/scala/scutil/math/pimp/OrderingImplicits.scala#L40

**Comment by axel22** [comment]
+1 too for `orElse`

**Comment by NthPortal** [comment]
I agree that `orElse` sounds good for `def orElse(other: Ordering[T]): Ordering[T]`. e.g.

```scala
case class PlayingCard(rank: Rank, suit: Suit)

val rankOrdering: Ordering[PlayingCard] = Ordering.by(_.rank)
val fullOrdering: Ordering[PlayingCard] = rankOrdering.orElse(Ordering.by(_.suit))
// Reads "rank ordering or else ordering by card.suit"
```

I feel that it sounds awkward for `def orElse[S](f: T => S)(implicit ord: Ordering[S]): Ordering[T]`. e.g.

```scala
case class PlayingCard(rank: Rank, suit: Suit)

val rankOrdering: Ordering[PlayingCard] = Ordering.by(_.rank)
val fullOrdering: Ordering[PlayingCard] = rankOrdering.orElse(_.suit)
// Reads "rank ordering or else card.suit" ??
```

Should the latter be called something else? Should it not get its own method? (The latter method allocates only one `Ordering` rather than two, and is also more concise for repeated chaining).

**Comment by Ichoran** [comment]
`Ordering.by(_.rank).orBy(_.suit)`

**Comment by ritschwumm** [comment]
orElseBy?

**Comment by Ichoran** [comment]
You could also have a form of `by` that takes multiple arguments.  I think `orElseBy` is also fine, but it's an extra word that really doesn't serve a purpose.

**Comment by NthPortal** [comment]
@Ichoran How would you define a `by` with multiple arguments? Varargs would be difficult, since each function requires an implicit ordering for its return type.

The two options I can think of are:

- create a whole bunch of overloads (mirroring the several implicit orderings for tuples)
- create a method with a lot of parameters which have a default value of some `Ordering` that always returns `0` (which would need to be cast to appropriate type)

Neither of these options seem great to me. Did you have something different in mind?

(Also, while such a definition of `by` would certainly be useful, unless it supports varargs, it would still not replace `or(Else)By`, which can support an arbitrary number of comparisons.)

**Comment by ritschwumm** [comment]
just one thought: would it have been better to defined orElse as
```def orElse[U<:T](that:Ordering[U]):Ordering[U] = ???```
instead of
```def orElse(that:Ordering[T]):Ordering[T] = ???```
?

**Comment by NthPortal** [comment]
If that is the case, `orElseBy` should probably be
`def orElseBy[U<:T,S:Ordering](f:U=>S):Ordering[U]`
instead of
`def orElseBy[S:Ordering](f:T=>S):Ordering[T]`
as well

**Comment by NthPortal** [comment]
At the same time though, the signature could also be
`def orElse[U>:T](that:Ordering[U]):Ordering[T]`

**Comment by NthPortal** [comment]
After some investigation, other signatures are less pleasant to use.

With either `U <: T` or `U >: T`, the following code snippet fails to compile due to both diverging implicits, and an inability to infer the type of `_` in `_.b`.

```
case class Pair(a: Int, b: Int)
val o1 = Ordering.by[Pair, Int](_.a).orElseBy(_.b)
val o2 = Ordering.by[Pair, Int](_.a).orElse(Ordering.by(_.b))
```

It only compiles if you explicitly specify the types as:

- `orElseBy[Pair, Int]`
- either `orElse[Pair]` or `Ordering.by[Pair, Int]`

 which makes the code substantially more verbose.
