### ISSUE TITLE
Typechecking of a macro expansion infers wrong type for List.map

### ISSUE THREAD

**Issue by scabug** [scala/bug#6155]
As per http://stackoverflow.com/questions/11681631/macro-return-type-and-higher-order-functions:

Macro definition:
```scala
def test(s:String) = macro testImpl

def testImpl(c:Context)(s:c.Expr[String]):c.Expr[Any] = {
  import c.universe._
  val list = reify(List(1)).tree

  val function = reify((x:Int) => x).tree

  val res = 
    Apply(
      Select(
        list,
        newTermName("map")),
      List(function)
    )

  c.Expr(res)
}
```

Macro call:
```scala
val list:List[Int] = test("")
```

Error message:
```scala
[error]  found   : Any
[error]  required: List[Int]
[error]     val list:List[Int] = test("")
[error]                              ^
```

**Comment by SethTisue** [comment]
it's not clear to me if there's anything actionable here

someone can reopen if they can clearly summarize the state of the ticket (or perhaps it would be better to open one or more new tickets)

**Comment by Blaisorblade** [comment]
Following up on [this comment of mine](https://github.com/scala/bug/issues/6155#issuecomment-292409371), the documentation issue has arguably been fixed.

With blackbox macros, the original code is clearly ill-typed, because a function returning `Any` can't be used in a context expecting `List[Int]`.

Instead, for whitebox macros, IIUC it's nowadays clear enough that "all bets are off", isn't it?

So IIUC this isn't even a bug.
