### ISSUE TITLE
Error message not helpful when val definition contains extra '()'

### ISSUE THREAD

**Issue by scabug** [scala/bug#6564]
If a val definition contains an extra set of parenthesis, like if not correctly transforming a def into a val, the error reported by the compiler is not really helpful.

```scala
$ scalac test.scala 
test.scala:5: error: not found: value a
  val a(): String = ""
      ^
one error found
```

It would be better if the error was something like: `expected ':' or '=', found '('`

**Comment by som-snytt** [comment]
Punting this in favor of actual correctness bugs in this area. Possible umbrella issue: https://github.com/scala/bug/issues/11800

The use case is switching `def` to `val`.

This case is probably a scalafix lint. It would be nice to have a hook for supplementary explanations by a reporter. Maybe the reporter doesn't turn on extra diagnostics: instead, record history so that on error, reporter can turn on instrumentation and re-run part of the compilation run. There's not much to say here: a patvaldef that introduces no vals.

Scala 3 does not have more to add here, therefore, `f--d in dotty` label applies.
