### ISSUE TITLE
unsoundness in many guises

### ISSUE THREAD

**Issue by scabug** [scala/bug#7278]
[Updated to consolidate demonstrations.]
```scala
class A { class E }
class B extends A { class E }
trait C { type E = Int }
trait D { type E = String }

object Test {
  // should not compile (?)
  // martin says "I'd argue about that"
  type EE[+X <: { type E }] = X#E

  def fail1() {
    val b = new B
    var x1: EE[A] = null
    var x2: EE[B] = new b.E
    x1 = x2
  }

  def fail2() {
    val b = new B
    var x1: p.E forSome { val p: A } = new b.E // should not compile
    var x2: p.E forSome { val p: B } = new b.E
    x1 = x2 // should not compile
  }

  def fail3() {
    var x1: EE[C] = 5
    var x2: EE[C with D] = ""
    x1 = x2
  }

  def wrap(label: String)(op: => Unit): Unit =
    try { op } catch { case x: ClassCastException => println("%30s %s".format(label, x)) }

  def main(args: Array[String]): Unit = {
    wrap("Variance and inner classes")(fail1())
    wrap("Conformance of existentials")(fail2())
    wrap("Linearization and type aliases")(fail3())
  }
}
//     Variance and inner classes java.lang.ClassCastException: B$E cannot be cast to A$E
//    Conformance of existentials java.lang.ClassCastException: B$E cannot be cast to A$E
// Linearization and type aliases java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
```

**Comment by SethTisue** [comment]
Scala 3 refuses to compile `type EE[+X <: { type E }] = X#E` with "X is not a legal path since it is not a concrete type"

It also rejects `class A { class E }; class B extends A { class E }` with "class E cannot have the same name as class E in class A -- class definitions cannot be overridden"

As for the status of these various examples in Scala 2, I think one reason this ticket has stayed open so long is it combines a lot of different stuff. I don't understand what the motivation was to consolidate all this in a single ticket — and then it got bigger as people have piled on with comments. In recent years we have been more consistent about discouraging these sorts of umbrella tickets.

If anyone cares about any individual test case here, I invite you to open a fresh ticket on it, so we can discuss them independently, label them independently, etc.

**Comment by som-snytt** [comment]
Instead of a fresh ticket, I reopened 7535, which now shows green above.

**Comment by som-snytt** [comment]
The example from the mailing seems OK to me, but the thread shows that the expectation at the time was virtual classes.

It warns on 2.13 and errors under `-Xsource:3`:
```
shadowing a nested class of a parent is deprecated but class Bar shadows class Bar defined in class Foo; rename the class to something else
```

The paulp coda still crashes.
```
  import scala.language.existentials
  def pp = {
    var b: foo.Bar forSome { val foo: Foo } = new foo.Bar
    b = new subFoo.Bar
    b
  }
```
It can be "made to work" by the (probably expected) idiom
```
class Bar extends super.Bar
```
