### ISSUE TITLE
Partest file should express tool flags and outputs

### ISSUE THREAD

**Issue by scabug** [scala/bug#7310]
The "test file" should encode the test itself and any tool flags and outputs used by the test runner (heretofore, .flags and .check).

Test output may be specific to a test run by depending on tool flags or the platform on which the test is run.

**Comment by som-snytt** [comment]
Test files support `// scalac: -Xsource:3` style pragmas and other features since https://github.com/scala/scala/commit/99b4d95fe6c908ce3170ff4d090420f8e47efa1d and recently updated to support cli `// using option` syntax.

The check file directives are a nuisance when updating the file, so they have fallen out of favor. One use case was for differential output when `-optimise` was on.

REPL `SessionTest` is handy for putting test and result in the same file.

`filter` files are still in use.
