### ISSUE TITLE
Stop importing java.lang.* by default

### ISSUE THREAD

**Issue by scabug** [scala/bug#7462]
There has been a lot of effort to reduce the size of `Predef` and the amount of classes in `scala.*`, but we have not evaluted the third default import, `java.lang.*`.

There are multiple issues why having this import by default is not worthwhile:

- Many of the classes in `java.lang.*` are useless in Scala (`java.lang.Void`, `java.lang.Deprecated`, `java.lang.Override`, ...) or are just not implemented (`java.lang.Compiler`)
- Many are just not important enough to be imported by default (`java.lang.Process`, `java.lang.ProcessBuilder`, `java.lang.StackTraceElement`, `java.lang.StrictMath`, ...)
- Many of them are shadowed by types in `scala.*` anyway, but still manage to create havoc in the REPL (`java.lang.Byte`, `java.lang.Long`, ...)
- It eats up valuable naming options (like `Number`, `Package`, `Compiler`, ...)
- It can confuse users (`java.lang.Iterable` vs. `scala.collection.Iterable`, `StringBuilder` is `scala.collection.mutable.StringBuilder` but `StringBuffer` is `java.lang.StringBuffer`)
- Most of the useful ones are aliased into the `scala.*` namespace anyway (`String`, `Class`, `Exception`, ...)
- Oracle keeps adding new classes, making the whole import a version-dependent moving target (`java.lang.ClassValue`, `java.lang.AutoCloseable`, both new in Java 7)

The proposed plan is as follows:

- 2.11: Start emitting warnings if people use types from `java.lang.*` without qualifying or importing them.
- 2.12: Stop importing `java.lang.*`.

To ease the transition, it might be worthwhile to

- add a few aliases so that things keep working without any change necessary (e. g. alias `java.lang.Thread`)
- add some common method implementations so that there is less need to use `java.lang.*` in the first place (e. g. add `java.lang.Integer.bitCount` to `scala.runtime.RichInt`)

One minor issue is that we can alias the type, but not the value, because Java doesn't have companion objects.

Paul's proposal concerning this:
```
We could always stop punishing ourselves, and synthesize it.

// Rather than taunt us with "object java.lang.String is not a value", this could
// give us what we want. It knows exactly what this would mean, as it shows us
// when it allows "import java.lang.String._".
val String = java.lang.String
```

Specification: In §9.1 Compilation Units, remove “the package java.lang, ” from “Implicitly imported into every compilation unit are, in that order : the package java.lang, the package scala, and the object scala.Predef.”

Discussion: https://groups.google.com/d/topic/scala-internals/ECY6vBzlx3A/discussion

**Comment by som-snytt** [comment]
`-Yimports:scala` offers sufficient flexibility.

The platform is indeed a moving target, but a target that Scala exploits as it may.

I wonder if @SethTisue who asked for it in caps six years ago, will close this ticket or make it a blocker.

My general sense is that folks either want only a custom predef or maximal convenience of included AAA batteries. For example, I think the repl should follow jshell and import more usual stuff by default.

**Comment by Jasper-M** [comment]
I think we should do this in Scala 3. Not even kidding.

**Comment by soc** [comment]
@som-snytt Just for the record: 

This issue is about _improving the defaults_ not adding some tuning knobs that 99.9% of users will never use.

Putting this aside, `-Yimports` is uniquely unsuitable to offer any improvement on this issue, due to specified imports getting implicitly turned into wildcard imports, which means:

- You can import whole packages
- You can import all static members from individual classes
- You **cannot** import types individually

So the one and only thing required from `-Yimports` to address this issue seems to have landed outside the acclaimed "sufficient flexibility" this feature was gifted with.

You can chalk it up as one of those times where the urge to add a feature was greater than the desire to check whether it was fit for purpose. ¯\\\_(ツ)\_/¯

(And now I'm trying to figure out how to bulk-unsubscribe, because it's silly that I'm still receiving notifications for this.)

**Comment by som-snytt** [comment]
`-Yimports` specifies so-called "root imports" exactly, so I don't understand the previous comment. So it's easy for a user not to see `Thread` and `Object`, etc.

Anyway, I agree with the comment prior to that, that it ought to be possible to make a policy decision at this point whether it's a desirable for `scala/scala` and also for users. There is more experience now with what is a platform dependency.

**Comment by soc** [comment]
> `-Yimports` specifies so-called "root imports" exactly

It does not. It turns every import into a wild-card import:

`-Yimports:java.lang.String` does not import `String`, it imports `valueOf`, `copyValueOf`, `join`, `CASE_INSENSITIVE_ORDER`; `-Yimports:java.nio.file` does not import `file`, it imports `Files`, `FileStore`, `FileSystem` etc.

It is simply impossible to import e. g. `java.lang.String` individually, without importing everything in `java.lang`.

**Comment by som-snytt** [comment]
@soc you don't understand what "root imports" means in this context. Also, `-Yimports` was specificially designed for "root imports", not as "code preamble". Stating this for interested observers. The relevant ticket/PR discusses this, because preamble was also prototyped.

**Comment by eed3si9n** [comment]
If you look at the original description and see JDK 7's [package summary](https://docs.oracle.com/javase/7/docs/api/java/lang/package-summary.html), most reasons like:

> - It eats up valuable naming options (like `Number`, `Package`, `Compiler`, ...)

sounds "meh" to me. (btw I strongly discourage anyone from using `Package` as a class name since it causes endless amount of pain on macOS and Windows when `Package.class` clashes with `package.class` etc.) Half of the names are exceptions and are likely useful / harmless.

In 2019 present context, however,

> Oracle keeps adding new classes, making the whole import a version-dependent moving target (`java.lang.ClassValue`, `java.lang.AutoCloseable`, both new in Java 7)

has a whole new implications. Java as platform is moving at faster pace, potentially adding names in an unpredictable way. From random sampling:

- [FunctionalInterface](https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html) in JDK 8
- [Module](https://docs.oracle.com/javase/9/docs/api/java/lang/Module.html), [ModuleLayer](https://docs.oracle.com/javase/9/docs/api/java/lang/ModuleLayer.html), [StackWalker](https://docs.oracle.com/javase/9/docs/api/java/lang/StackWalker.html) in JKD 9

**Comment by som-snytt** [comment]
I'll contribute that it's weird to me

- not knowing where StringBuilder comes from
- if I had to import Thread
- also if I had to import StackWalker

Does that call for a compatibility layer of useful stuff added in JDK N? Maybe if we had conditional compilation, it could be a handy module that covers every version since JDK 8 as a required baseline. Or maybe enabled by `--target`.

**Comment by eed3si9n** [comment]
Each major release of Scala should freeze the knowledge about JDK N where N is the minimum required like 8, so compiling on JDK N + 1 would not introduce incidental semantic changes either at compile-time or runtime.

> if I had to import Thread

Yea. I agree that the proposed battle plan (https://gist.github.com/soc/5994338) seems a bit aggressive.  Maybe someone can come up with a defensive battle plan where we default to keep, and remove things that are truly problematic.

**Comment by soc** [comment]
> you don't understand what "root imports" means in this context. Also, -Yimports was specificially designed for "root imports", not as "code preamble".

I think you gave a good description in https://github.com/scala/scala/pull/6764.

Fact is that the applicability of `Yimports` to resolve this issue is completely irrelevant to a "root" vs. "pre-amble" design.

I disagreed with your notion of "specifies so-called "root imports" _exactly_", as specifying `java.lang` and getting `java.lang._` imported is as far from "exactly" as practically possible for this kind of functionality.

This design of adding adding wildcards to imports is what makes the feature completely useless in the context of this ticket.

Alright, I'll leave you now to the hand-wringing over a battle plan that is as defensive as doing nothing for 6 years (diminishing returns, yadda-yadda). :-)

**Comment by Jasper-M** [comment]
> Yea. I agree that the proposed battle plan (https://gist.github.com/soc/5994338) seems a bit aggressive. Maybe someone can come up with a defensive battle plan where we default to keep, and remove things that are truly problematic.

I would just start by simply removing the `java.lang._` import. Then see what breaks in the std library, compiler and community build. Based on that make a _small_ selection of types that haven't been aliased in `scala` or `scala.Predef` yet and that genuinely look like oversights that are generally useful and don't have alternatives in the scala std library. Add those as aliases to `scala` or `scala.Predef`. And while we're at it, deprecate and copy all aliases from `scala.Predef` to `scala` or the other way around.

I've never really understood why we already have all those aliases if we import `java.lang._` anyway.

**Comment by soc** [comment]
> I would just start by simply removing the java.lang._ import. [...] Add those as aliases to scala or scala.Predef.

That's not going to work, due to the reason quoted above. E. g. `import java.lang.String` is kinda like `type String = java.lang.String` plus `val String = java.lang.String`, except that you cannot write down the latter in Java.

Going without the `val` would mean that people could write `val x: String = ...`, but not `String.valueOf(...)`.

So you need a way to specify the things desired to be in scope either ...
- via imports – but `Yimports` does not work, as noted above – or ...
- address the issue of "object java.lang.String is not a value" one way or another

**Comment by Jasper-M** [comment]
Wait, does `String.valueOf(...)` actually mean `java.lang.String.valueOf(...)` while `val a: String` means `val a: scala.Predef.String`?

> you cannot write down the latter in Java.

You cannot even write it in Scala. I thought static java members just work cause the compiler special cases those accesses, not the imports.

**Comment by soc** [comment]
> Wait, does String.valueOf(...) actually mean java.lang.String.valueOf(...) while val a: String means val a: scala.Predef.String?

Yes. (At least the last time I checked this.) This is because the type alias in Predef wins over the import of `java.lang._`, but no such alias exists for values.

> You cannot even write it in Scala.

Sorry, a typo. That's what I meant. I corrected it above.

**Comment by SethTisue** [comment]
I believe this is now out of scope for Scala 2, but perhaps it could progress on Scala 3.
