### ISSUE TITLE
Option zip should return Option

### ISSUE THREAD

**Issue by scabug** [scala/bug#8394]
zip in the Option docs says:
zip[B](that: GenIterable[B]): Option[(A, B)] 

but it acutally returns an Iterable[A, B]. I don't think it's a documentation bug, as returning an Option would make sense.

**Comment by xavier-fernandez** [comment]
Start working on this right now :)

**Comment by ashawley** [comment]
Fixing this would take marshaling the old patch scala/scala#4433 that adds `Option.zip` and updating it to work on 2.13.

Is this a good first issue?

**Comment by SethTisue** [comment]
> Is this a good first issue?

indeed!

**Comment by SethTisue** [comment]
Dale isn't working on scala/scala#6491 anymore, he says. Would someone else like to take it?

I've removed "good first issue" since there is now enough accumulated history and discussion on this to be potentially intimidating to a newcomer. Regardless, it's not a big change and shouldn't be hard for someone to pick up, assuming there aren't new objections to what seems to me (knock on wood) like emerging consensus on the PR about what the right design is.

**Comment by SethTisue** [comment]
(And I've redone the labels to show that this is now about changing `Option` for 2.13, not about fixing Scaladoc. Someone might like to open a new ticket on the Scaladoc angle on this.)

**Comment by NthPortal** [comment]
scala/scala#6491 seems to be moving again
