### ISSUE TITLE
copyToArray should return the number of elements copied

### ISSUE THREAD

**Issue by scabug** [scala/bug#8469]
I believe copyToArray should return the number of elements copied. In particular this would be important for Iterator, but might be handy in general. Given that copyToArray returns Unit at the moment, this would be a backward compatible change.

Consider the following use case. I receive an Iterator that I expect to be of a certain size. I want to put it into an Array. One option is to use Iterator.toArray and then assert that the size is as expected. But toArray is slow, because it does not know the expected size and has to use a dynamic array (or linked list?). copyToArray would be perfect, except we cannot tell how much was copied in the end. If Iterator.hasNext is true, we know the Iterator was too long. But if it is false, it was either the expected size or too short, and we cannot tell these cases apart.

Link to actual code with the above use-case:
https://github.com/apache/spark/blob/f4d9019aa8c93e6f7539192ba5780a2f6c8ce19e/graphx/src/main/scala/org/apache/spark/graphx/impl/EdgePartition.scala#L92

**Comment by SethTisue** [comment]
the duplicate report #11002 has some further explanation/justification

**Comment by joshlemer** [comment]
@SethTisue Is there any indication that this can be in before the release of 2.13? Since the time to make these changes is now. In the previous api, these methods returned Unit, so there is no danger of changing their behavior. If 2.13 is published with these methods returning `Array[T]` it would be a breaking change to return elems copied.

**Comment by SethTisue** [comment]
there is still time before 2.13.0-M5, which is targeted for Aug 10.

> In the previous api, these methods returned Unit, so there is no danger of changing their behavior

true (though it's still not a 100% source-compatible change, since the inferred type of an expression could change as a result. regardless, as you point out, this particular source-compatibility horse already left the barn in 2.13.0-M4)

@julienrf is this a change you'd accept...?

**Comment by julienrf** [comment]
Yes, we should try to fix that!

**Comment by SethTisue** [comment]
@joshlemer do you plan to submit a pull request on it...?

**Comment by joshlemer** [comment]
@SethTisue Yes I'll try and do this tonight :-)
