### ISSUE TITLE
Vector should have SerialVersionUID, and other problems with SI-8549 discovered by the Xcheckinit build.

### ISSUE THREAD

**Issue by scabug** [scala/bug#8576]
As noticed in the instability of the new test for #8549 under -Xcheckinit:

https://scala-webapps.epfl.ch/jenkins/view/2.12.x/job/scala-nightly-checkinit-2.12.x/

Marking as a blocker for 2.11.1 as the release is intended to fix serialization issues.

**Comment by szeiger** [comment]
Removing the "collections" label because this is not really about `Vector` or collections. In light of https://www.bleepingcomputer.com/news/security/oracle-plans-to-drop-java-serialization-support-the-source-of-most-security-bugs/ and with Java serialization being mostly abandoned in favor of newer protocols anyway I'm not sure we should invest time into this corner case (serialization compatibility between checkinit and non-checkinit builds) at all.

**Comment by SethTisue** [comment]
> I'm not sure we should invest time into this corner case (serialization compatibility between checkinit and non-checkinit builds) at all.

agree, in fact, I think we should close this ticket — but I think @dwijnand may want to double check with Lukas first
