### ISSUE TITLE
curried constructors could be implicitly eta-expanded

### ISSUE THREAD

**Issue by scabug** [scala/bug#8729]
The language spec (sec. 6.26.2) states that eta-expansion only applies to curried methods that aren't constructors; this restriction seems arbitrary. If I can write:

```scala
scala> case class Foo(a: Int)(b: Int)
defined class Foo

scala> val f: Int => Foo = Foo(3)
f: Int => Foo = <function1>
```

then I don't see why:

```scala
scala> val f: Int => Foo = new Foo(3)
<console>:9: error: missing arguments for constructor Foo in class Foo
```

should be forbidden. If `Foo` isn't a case class (or doesn't otherwise have a curried `apply` method) it's necessary to manually eta-expand:

```scala
scala> val f: Int => Foo = new Foo(3)(_)
f: Int => Foo = <function1>
```

This inconsistency seems unwarranted.

**Comment by SethTisue** [comment]
In Scala 3, the `new Foo(3)` version still doesn't compile, but in Scala 3 one doesn't normally need to use `new` anymore, and it does work if you write it in `new`-less style:

```
scala> case class Foo(a: Int)(b: Int)
// defined case class Foo
                                                                                                    
scala> val f: Int => Foo = new Foo(3)
-- [E178] Type Error: ----------------------------------------------------------
1 |val f: Int => Foo = new Foo(3)
  |                    ^^^^^^^^^^
  |                    missing argument list for constructor Foo in class Foo
  |
  |                      def <init>(a: Int)(b: Int): Foo
  |
  | longer explanation available when compiling with `-explain`
1 error found
                                                                                                    
scala> val f: Int => Foo = Foo(3)
val f: Int => Foo = Lambda$1760/0x000000f0015882c8@7c6ab057
```

so in a way it's "fixed" in Scala 3, but in a way it isn't. (I am not adding the "fixed in Scala 3" label.)

Anyway, I think changing this is now out of scope for Scala 2. The change still seems plausible for Scala 3, but someone would have to champion the change with a SIP (because a spec change is needed) and accompanying implementation.

> this restriction seems arbitrary

it seems arbitrary to me too, but also, perhaps there's some logic behind it that I'm not perceiving
