### ISSUE TITLE
Misleading use case for Map#map

### ISSUE THREAD

**Issue by scabug** [scala/bug#8876]
From http://www.scala-lang.org/api/current/index.html#scala.collection.Map :

Look at `filter`'s compact type signature:
```
filter(p: ((A, B)) ⇒ Boolean): Map[A, B]
```

This type signature makes sense. I can pass in a function that takes a tuple of (key, value) and returns a boolean.

Now look at `map`'s compact type signature:
```
map[B](f: (A) ⇒ B): Shrinkable[B]
```

I interpret this as "map takes in a function which takes a key and returns an arbitrary type", but it actually means "map takes in a function which takes a tuple of (key, value) and returns an arbitrary type".

Here `A` actually refers to `(A, B)` (from Map extending `Iterable[(A, B)]`?), which is the confusing part.

Perhaps this type signature would be less confusing:
```
map[C](f: ((A, B)) ⇒ C): Shrinkable[C]
```

?

**Comment by ashawley** [comment]
@nafg wrote:

> why not just rename Map's type parameters to K and V or something like that?

Looks like that's exactly what they did in the collections prototype, see:

https://github.com/scala/collection-strawman/blob/5f601cb/collections/src/main/scala/strawman/collection/Map.scala#L225

That change has existed since https://github.com/scala/collection-strawman/commit/7fd6d93

Perhaps, close this issue?  Two years ago, maybe the collections rewrite wasn't serious, but it sounds like it might ship with 2.13.

**Comment by SethTisue** [comment]
outright closing it might be reasonable, but I've put it on the M4 milestone (that's when collection-strawman will be merged) so we can double-check before closing. I'll also add the "has PR" label

**Comment by paulp** [comment]
Is this ticket about this one particular example, or is it about the fact that "use cases" do not work? If someone reports that addition doesn't work because they noticed a code sample where 4 + 5 produces 913, changing the code not to use 4 and 5 is not quite the same thing as fixing it. Is changing the name of this one library class's type parameters going to fix the same issue arising in everyone else's libraries? Or in the other places it occurs in THIS library?

Here's a signature from the 2.12.4 scaladoc for HashMap.
```scala
def ++:[B](that: TraversableOnce[B]): HashMap[B]
```

Maybe there's some other ticket covering "use cases don't work", in which case sure, this is merely one instantiation of a much larger issue. If there is not, it's difficult to see how it's justified. Not that I think leaving it open will cause it to be fixed. But I think people deserve to know what are the operative principles.

**Comment by nafg** [comment]
@paulp personally I would go by the issue summary which implicit it's about the specific instance. Unfortunately it seems like there might not be a ticket for the larger issue.

**Comment by nafg** [comment]
The collections rewrite probably helps a lot simply because it doesn't use CanBuildFrom.

**Comment by SethTisue** [comment]
> Is this ticket about this one particular example, or is it about the fact that "use cases" do not work?

the ticket on use cases in general being broken is #6071

**Comment by paulp** [comment]
One might argue “use cases should be generated automatically” has a different aesthetic than “use cases do not work”.

**Comment by SethTisue** [comment]
Yeah. I renamed #6071 and added a comment.

**Comment by SethTisue** [comment]
Gah, let's just close this one.
