### ISSUE TITLE
please allow value definitions before the first generator in a for comprehension

### ISSUE THREAD

**Issue by scabug** [scala/bug#907]
I would like to be able to write this:

  for{x = foo(bar); y <- x} ...

the language spec (6.19) says "An enumerator sequence always starts with 
a generator", but why? From time to time I would find it convenient to put
a value definition first.  I realize that in the above code I only use x once,
but I've hit this in real code where I want to use x more than once.

(Perhaps "if" should be allowed too?)

**Comment by fommil** [comment]
I'd really like to see this ticket reopened.

**Comment by jvican** [comment]
I'm not sure this workaround:
```scala
val x = foo(bar)
for {y <- x}
```
  
is worth it. I think we have already enough desugarings in parser. Putting more would force all the Scala tooling to catch up and I don't think it's a neat solution overall, but rather a hack.

**Comment by fommil** [comment]
for FP code this is definitely worth it. This comes up all the time when `for` is your main language structure for sequential code.

**Comment by fommil** [comment]
btw, apparently we should be discussing at https://contributors.scala-lang.org/t/ressurrect-assignment-as-first-line-of-for/808

**Comment by SethTisue** [comment]
it appears this was closed because the core team at the time didn't intend to tackle it, not because it would necessarily be rejected if it came in as a community contribution (including the necessary spec work and so forth)

**Comment by SethTisue** [comment]
an example usage with `Future` via @viktorklang: https://twitter.com/viktorklang/status/861982357800308737

**Comment by SethTisue** [comment]
further food for thought in this area at https://contributors.scala-lang.org/t/pre-sip-let-expressions-in-scala/1391/1

**Comment by SethTisue** [comment]
came up again at https://contributors.scala-lang.org/t/allow-simple-vals-to-appear-first-in-for-expression/5428

**Comment by nafg** [comment]
I would like to go even further and allow for comprehensions with only value definitions and no generators. It would be like defining a bunch of `val`s without having to write `val` each time.

One of the really nice things about Scala is that changing code in a limited way often involves few edits. For instance to change a binding from immediately-evaluate-once to deferred-evaluate-every-time you just change `val` to `def` while in say Java you'd have to change a whole bunch of syntax (add parentheses, curly braces, and `return`). To make a function's scope persist (a.k.a. change a method to a class) is a bit more work but not nearly as much as in say Java, because it's still basically just keyword-name-arguments-body. And so on.

Additionally, most constructs don't have a very strict, conservative set of ways to apply it. Constructs are usually limited only for very good reasons. For instance you can nest methods inside classes inside pattern matches etc. Vals can have block statements on their right-hand side. And there isn't different syntax for class members vs. local bindings.

Together this means that you can take a more "agile" approach to writing code, not worrying up front what form things will take because you can easily evolve code over time with little effort.

By the same token, to me it makes sense that since for comprehension already supports value definitions, there's no good reason to prohibit them as the first item. And once you accept that, there's no good reason to require it to be followed by a generator.

**Comment by fommil** [comment]
Naftoli raises the zombies in the thread ![](https://media.giphy.com/media/IdwEN5eoXFodi/giphy.gif)

**Comment by som-snytt** [comment]
came up again at https://contributors.scala-lang.org/t/pre-sip-comprehensive-function-applications/5902/12

where initial args are precomputed.

**Comment by SethTisue** [comment]
closing since this would need to happen in Scala 3 first before we could do it here

**Comment by som-snytt** [comment]
Closing because the ticket has 22 thumbs-up, which is the limit for Scala 2.

Since it is an enhancement, not a bug, feature proposals with implementations and backports are always welcome.

**Comment by SethTisue** [comment]
https://github.com/scala/improvement-proposals/pull/79 proposes to fix this in Scala 3
