### ISSUE TITLE
Implement breakable generators for sequence comprehensions

### ISSUE THREAD

**Issue by scabug** [scala/bug#9120]
Proposing a light-weight implementation of 'break' and 'continue' that operate inside of sequence comprehensions, as specialized breakable generators.

The concept is written up here:
http://erikerlandson.github.io/blog/2015/01/24/monadic-break-and-continue-for-scala-sequence-comprehensions/

A simple example of what they look like in use:

```scala
object Main {
  import scala.util.control.BreakableGenerators._

  def main(args: Array[String]) {

    val r = for (
      // generate a breakable sequence from some sequential input
      loop <- breakable(1 to 1000);
      // iterate over the breakable sequence
      j <- loop;
      // print out at each iteration
      _ = { println(s"iteration j= $j") };
      // continue to next iteration when 'j' is even
      if { j % 2 == 0 } continue;
      // break out of the loop when 'j' exceeds 5
      if { j > 5 } break(loop) 
    ) yield {
      j
    }
    println(s"result= ${r.toList}")
  }
}
```

**Comment by SethTisue** [comment]
I think this is now out of scope for Scala 2, but Scala 3's `boundary` and `break` might be what you were looking for @erikerlandson?

**Comment by Ichoran** [comment]
@SethTisue - I don't think boundary/break entirely works because you can't get partial computations that way (not with ordinary syntax).  The features he wanted could be built with boundary/break, but they alone aren't enough.

@erikerlandson - My kse3 library implements functionality like this for arrays using boundary/break.  It doesn't solve the break-out-of-multiple-levels problem (by design), but operations that normally accumulate things can return partial results with skipping and early termination.  If you wanted to do it for the Scala collections, it might be instructive to see how I did it for arrays.
