### ISSUE TITLE
destructuring binds, implicit resolution, and declaration order

### ISSUE THREAD

**Issue by scabug** [scala/bug#9130]
This caused me quite the literal headache today:

```scala
class S[_]
class T[_]

case class B(x: Int)
object B {
  def makeST = (new S[B], new T[B])
  implicit val (s,t): (S[B],T[B]) = makeST
}

object A { implicitly[T[B]] }
```
The code above compiles, but if you swap the order of A and B,  it no longer will:
```scala
class S[_]
class T[_]

object A { implicitly[T[B]] }

case class B(x: Int)
object B {
  def makeST = (new S[B], new T[B])
  implicit val (s,t): (S[B],T[B]) = makeST
}
```
```
<console>:11: error: could not find implicit value for parameter e: T[B]
         implicitly[T[B]]
                   ^
```
Very sad indeed.  

The tuple has something to with it; this is ok:
```scala
class S[_]
class T[_]

object A { implicitly[T[B]] }

case class B(x: Int)
object B {
  def makeST = (new S[B], new T[B])
  implicit val s: S[B] = makeST._1
  implicit val t: T[B] = makeST._2
}
```

**Comment by SethTisue** [comment]
Scala 2 now warns by default ("Implicit definition should have explicit type"), and Scala 3 actually errors ("result type of implicit definition needs to be given explicitly")

and the new `given` syntax doesn't offer any equivalent to `implicit val (a:Int, b:String) = ...`, so that angle has been designed away
