### ISSUE TITLE
Can't deserialize scala.List[M] if scala-library is not in the same classloader as M

### ISSUE THREAD

**Issue by scabug** [scala/bug#9237]
List has some serialization problems.

Take a look at the minimized version here.

https://github.com/hamnis/minimized-list-serialization

This seems to be triggered by classloaders, not that I understand why that is the case.
Comment in the fork in Test in build.sbt, then it works.

**Comment by dknoester** [comment]
Hi all,

This seems related to a bug I've recently reported to Apache Spark: https://issues.apache.org/jira/browse/SPARK-20525

Was hoping someone here might be able to help - Thanks in advance!

**Comment by SethTisue** [comment]
putting this on the 2.13.0-RC1 milestone because in the 2.13 collections, most/all collections are affected, instead of only `List`

however, I also think we should just close this as "not a bug". as @scottcarey wrote, "this is not a bug at all, its just how Java Serialization works"

but we do need to make sure we've documented the issue in e.g. the 2.13 collections migration guide

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/7624

**Comment by SethTisue** [comment]
that PR is marked with the release-notes label, which should be a sufficient that we don't forget to include it in migration doc
