### ISSUE TITLE
Weak Least Upper Bound is not Correctly Calculated in Some Conditional Expressions

### ISSUE THREAD

**Issue by scabug** [scala/bug#9338]
According to [SLS 6.15](http://www.scala-lang.org/files/archive/spec/2.11/06-expressions.html#conditional-expressions):

```
The type of the conditional expression is the weak least upper bound of the types of e2 and e3.
```

However, it seems that the result of following code (conditional expression is included) is not correct:

```
scala> val x: Any = if(true) 1 else 1.0
x: Any = 1

scala> val x: Double = if(true) 1 else 1.0
x: Double = 1.0
```

because weak least upper bounds of Int (type of 1) and Double (type of 1.0) is Double, 1 should be converted 1.0 regardless of the expected type.

**Comment by SethTisue** [comment]
I would agree it's a bug, and it's still present in 2.13.10.

I'm going to mark at as "fixed in Scala 3" not because the bug was addressed directly, even though the behavior is the same:

```scala
Welcome to Scala 3.3.1-RC1-bin-20230221-847eccc-NIGHTLY-git-847eccc (17.0.6, Java OpenJDK 64-Bit Server VM).

scala> val x: Any = if(true) 1 else 1.0
val x: Any = 1
```

because in Scala 3 it's behaving as spec'ed, as per https://docs.scala-lang.org/scala3/reference/dropped-features/weak-conformance.html :

> Scala 3 drops the general notion of weak conformance, and instead keeps one rule: Int literals are adapted to other numeric types if necessary.

and when the expected type is `Any`, no adaptation is needed.

**Comment by SethTisue** [comment]
Regardless, I'm going to close this ticket as "not planned", since I think that the benefit of fixing it would be exceeded, at this late stage in Scala 2's evolution, by the cost of introducing a Scala 2 vs 3 behavior difference that doesn't currently exist.

**Comment by som-snytt** [comment]
It's not a bug because the spec says each expr must conform to the expected type of the conditional.

That is why the following works. Otherwise the type of the conditional is `AnyRef` instead of `D`.

The ticket example is more special because `42` is not an `Int` if the expected type is `Short`. Cf https://github.com/scala/bug/issues/12722

```
scala> class C; class D
class C
class D

scala> implicit def cv0(c: C): D = new D
def cv0(c: C): D

scala> def b = true
def b: Boolean

scala> val x: D = if (b) new C else new D // print
                                                             private[this] val `x `: D = if (b)
  cv0(new C())
else
  new D()
```
A similar example:
```
scala> val d: Double = if (b) (42: Short) else (17: Byte) // print

private[this] val `d `: scala.Double = if (b)
  ((42): scala.Short).toDouble
else
  ((17): scala.Byte).toDouble
```
If the RHS were typed as `Short`, the conditional result would be converted in turn `toDouble`.

I think the same principle applies in Scala 3, which still has numeric widening. I don't know how they describe the type of a conditional without recourse to weak LUB; "harmonization" applies only to literals.

**Comment by SethTisue** [comment]
> It's not a bug because the spec says each expr must conform to the expected type of the conditional

It does say that, but `1` and `1.0` both conform to `Any`, so we're good.

But then the spec _also_ says:

> The type of the conditional expression is the weak least upper bound of the types of e2 and e3

I don't see how you've made an argument that this wording somehow doesn't apply here?

**Comment by SethTisue** [comment]
If we're reading the spec differently, maybe the bug is that the spec ought to be clearer.

**Comment by som-snytt** [comment]
The code says the spec should say "The inferred type of the conditional...".

So a branch body might be typed with the explicit expected type, or subsequently adapted to the inferred type.
