### ISSUE TITLE
Parenless overloaded methods are used in ambiguous cases

### ISSUE THREAD

**Issue by scabug** [scala/bug#9395]
This code:

```scala
class MyClass {
    def something(in: String): String = {
        in + "_z"
    }

    def something: (String) => String = {
        case _ => "Fixed"
    }
}

val my = new MyClass()

println(List("x", "y").map(my.something))
```

Prints List(Fixed, Fixed).

The type checker is calling the no-argument variant of my.something(), and then silently taking the return type and passing it to map(). This ignores the other matching one-argument version of my.something.

The below line (arguably correctly) produces a compile error about an "ambiguous reference to overloaded definition":

```scala
val fun: String => String = my.something(_)
```

Adding parentheses to the no-argument definition of the method removes the issue. Changing the return type of the no-argument method to be anything other than String => String removes the issue.

I think this is incorrect behavior; where there is a conflict between the result of an implicit conversion (the my.something() return value) and an unconverted correct type, either the unconverted type should win or a compile error should be thrown telling the user about ambiguity. In other words, the above code should either output List(x_z, y_z) or fail to compile. Currently the implicitly converted version is silently taking precedence.

**Comment by som-snytt** [comment]
Dotty says `1`.
```
[[syntax trees at end of                     typer]] // t9395.scala
package <empty> {
  final lazy module val Test: Test = new Test()
  final module class Test() extends Object(), App { this: Test.type =>
    def f(s: String): String = "1"
    val f: String => String =
      {
        def $anonfun(s: String): String = "2"
        closure($anonfun)
      }
    val t: String => String =
      {
        def $anonfun(s: String): String = Test.f(s)
        closure($anonfun)
      }
    println(Test.t.apply(""))
  }
}
```
Is this like the Monty Hall problem where you always pick the other door?

**Comment by som-snytt** [comment]
https://github.com/lampepfl/dotty/issues/18294

**Comment by som-snytt** [comment]
Sorry I did not note which version of Dotty was current two years ago.

Currently, 3.5.2 says `2`.

Odersky says "as specified" https://github.com/scala/scala3/pull/19654#issuecomment-1939111474

There is recent Dotty history of trying to make overload resolution with eta-expansion do something "intuitive". For some people, that may mean "`f` should resolve the same as `f(_)`". For others, "Do extra work to discover some interpretation of the code I wrote that compiles, and take that as correct."

The explanations here are about mechanisms and not specification:
https://github.com/scala/scala3/issues/21727#issuecomment-2439972457
https://github.com/scala/scala3/pull/21847#pullrequestreview-2397509176

The spec says:

> Implicit conversions can be applied to expressions whose type does not match their expected type, to qualifiers in selections, and to unapplied methods.

The `f` reference (nullary and matches its expected type) does not meet any of these criteria. That justifies doing the obvious thing: take the `f` that works before opening a can of worms to adapt alternatives.

Closing this ticket since further clarifications or progressions will take place at scala3.
