### ISSUE TITLE
Future.sequence of Option

### ISSUE THREAD

**Issue by scabug** [scala/bug#9694]
Hi everybody,

Having the following code

```scala
import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global

val f1 = List(Future(1))
Future.sequence(f1)

val f2 = Option(Future(1))
Future.sequence(f2)
```

The first **Future.sequence** works whereas the second one doesn't.

According to the **Future.sequence** signature, it requires **M[ X ]** to be a subtype of **TraversableOnce[ X ]**.

Would it make sense to require an implicit conversion {code:scala}M[X] => TraversableOnce[X]{code} in order to make possible applying *Future.sequence* to an *Option*? 

What do you think? :-)

**Comment by eed3si9n** [comment]
@viktorklang et al, Assuming Option will not extend TraversableOnce within a year or two, could you consider this a good first issue?

**Comment by SethTisue** [comment]
I don't think any proposal involving further entangling of Option with the collections library will fly — I find even the existing degree of entanglement questionable.

**Comment by SethTisue** [comment]
related: #8394

**Comment by viktorklang** [comment]
@SethTisue Am I right in interpreting your position as sequence(Option) not making sense?

**Comment by ritschwumm** [comment]
@viktorklang he probably means the implicit conversion from option to iterable which is causing a lot of problems already; having option _extend_ traversable would be even worse.

**Comment by viktorklang** [comment]
@ritschwumm Apologies, I was unclear. Since `sequence` is for collections (since there is no stdlib Monad typeclass), if we do not consider Option to be a collection (which is definitely a valid opinion), then I posit that we should leave sequence as is.

**Comment by ritschwumm** [comment]
well, sequence- and traverse-like operations make as much sense for Option as they make for collections, and i'd expect to have them in the standard library. the same goes for Either and maybe other types. lacking a typeclass, those probably would have to be additional methods.

**Comment by SethTisue** [comment]
@julienrf has been thinking about this here: https://github.com/scala/collection-strawman/issues/247

**Comment by viktorklang** [comment]
@ritschwumm For the (rare?) occurrence where sequencing of an Option is needed, I don't think it's too much effort to either write inline, or define an utility which does one of the following:

~~~scala
Future.sequence(o.toList).map(_.headOption)

o.fold(Future.successful(Option.empty[T]))(_.map(Some(_)))
~~~

**Comment by martijnhoekstra** [comment]
writing a utility to do that doesn't seem far fetched.

Naming that utility anything other than `sequence` does seem rather far fetched IMO.

If that utility is generally useful, and naturally called `sequence`, that to me sounds like a reason for having it rather than for not having it.

**Comment by dwijnand** [comment]
Given the uncertainty it sounds like this might not be such a good first issue to tackle.

**Comment by viktorklang** [comment]
@martijnhoekstra I guess what I'm trying to say is: the first time you need it, write that code in place, the second or third time, write a utility, when a lot of people have written that exact utility, it may be a good candidate to standardize?

**Comment by jeffrey-aguilera** [comment]
In 2.13, `Option` now extends `IterableOnce` and `Future.sequence` is declared as `sequence[A, CC[X] <: IterableOnce[X], To]`, but this _still_ does not work: Implicit not found for `BuildFrom[Option[Future[A]], A, To_]`.

**Comment by julienrf** [comment]
You need to add a `BuildFrom` instance for `Option`:

~~~ scala
implicit def buildFromOption[A]: BuildFrom[Option[_], A, Option[A]] = ...
~~~

**Comment by SethTisue** [comment]
in a sense, this really isn't about `Future` or `Future.sequence`, it's about this implicit not existing (for `Int` or any other element type):

```scala
scala 2.13.3> implicitly[collection.BuildFrom[Option[Int],Int,Option[_]]]
                        ^
              error: Cannot construct a collection of type Option[_] with elements of type Int based on a collection of type Option[Int].
```

**Comment by SethTisue** [comment]
@julienrf jinx

**Comment by SethTisue** [comment]
have we previously considered adding this to stdlib?

```scala
import collection.BuildFrom, collection.mutable.Builder

implicit def optionBuildFrom[T]: BuildFrom[Option[_], T, Option[T]] =
  new BuildFrom[Option[_], T, Option[T]] {
    override def fromSpecific(from: Option[_])(it: collection.IterableOnce[T]): Option[T] =
      it.iterator.nextOption()
    override def newBuilder(from: Option[_]) = new Builder[T, Option[T]] {
      private var _result: Option[T] = None
      def clear(): Unit = { _result = None }
      def result(): Option[T] = _result
      def addOne(elem: T): this.type = {
        require(_result == None)
        _result = Some(elem)
        this
      }
  }
}
```

demo:

```
import scala.concurrent.{ Future, Await }
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration.Duration

val f1: Option[Future[Int]] = Some(Future(1))
Await.result(Future.sequence(f1), Duration.Inf)  // Some(1)
val f2: Option[Future[Int]] = None
Await.result(Future.sequence(f2), Duration.Inf)  // None
val v3: Option[Future[Int]] = Some(Future.failed(new RuntimeException("foo")))
Await.result(Future.sequence(f3), Duration.Inf)  // None
```

**Comment by julienrf** [comment]
This would solve this problem but it feels to me like we would be hijacking BuildFrom.

If we support Option, I would expect that we also support Either. But this is not possible because this type has nothing to do with IterableOnce, and it would make little sense to implement BuildFrom instances for Either.

What we really want here is to have instances of Traverse[Option] and Traverse[Either].

That being said, I guess there might be less use cases in the wild for Either[X, Future[Y]], than use cases for Option[Future[X]]. I'm not sure. But if this is indeed the case, then maybe it's OK to go with implementing BuildFrom for Option. 



-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SethTisue** [comment]
> What we really want here is to have instances of Traverse[Option] and Traverse[Either].

(https://typelevel.org/cats/typeclasses/traverse.html, for anyone wondering)

I see we already hashed this over pretty thoroughly at https://github.com/scala/collection-strawman/issues/247 and then continuing at https://github.com/scala/bug/issues/10934

since #10934 is closed, leaving one this open doesn't seem to make sense

a contribution of improved doc for `Future.sequence` would be welcome

**Comment by julienrf** [comment]
Even though I personally think it would be better to broaden the applicability of `sequence` to other types, I understand the arguments against it. Now, supporting `Option` requires very little effort in the standard library, so maybe it’s worth adding this `BuildFrom` instance for `Option`?
However, this can’t be achieved before Scala 3.1 (or 2.14).

**Comment by ritschwumm** [comment]
the BuildFrom instance sounds like a bad idea to me:

* Option and collections in scala are quite different things: more or less everything in the collections universe assumes a collection has no upper limit on items, certainly not one as low as 1
* i consider BuildFrom to be an implementation detail of the collections, something that is quite definitely _not_ a collection like Option (because of its upper limit on items being 1) should not rely on. 
* someone trying to understand e.g. Future.sequence on an Option will have a hard time figuring out why this works.

if i could, i'd probably just add sequenceEither and sequenceOption to Future and be done with it - and keep the collections library out of the picture. or have a traversable typeclass, of course.
