### ISSUE TITLE
Mixed compilation: cannot refer to Scala object in Java source

### ISSUE THREAD

**Issue by scabug** [scala/bug#9714]
Test.scala
```scala
package p
object O {
  Test.foo()
}
```

Test.java
```scala
package p;
public class Test {
  public static p.O$ foo() { return null; }
}
```

```
$ rm -rf p && scalac11 Test.scala Test.java
Test.java:3: error: not found: type p
  public static p.O$ foo() { return null; }
                ^
one error found
```

**Comment by SethTisue** [comment]
remains reproducible in both Scala 2.13.12 and 3.3.1. The 3.3.1 error message is "type O is not a member of p - did you mean p.O.type?"

**Comment by He-Pin** [comment]
Yes,I think the code should be O.type

**Comment by som-snytt** [comment]
To review, `javac` is happy because `public static final p.Module$ MODULE$;` but `scalac` doesn't understand what is intended by `p.Module$` in Java source.

The PR says OK, when we translate Java statics, also translate the lookup of `Module$` names as type names (to a lookup of the corresponding term, returning its `moduleClass`).

**Comment by SethTisue** [comment]
I'm okay with going ahead with a fix in Scala 2 regardless. I consider it a fix, not a design change.

**Comment by som-snytt** [comment]
I am a disinterested contributor.

**Comment by SethTisue** [comment]
![Orson_Welles_Paul_Masson_Park](https://github.com/scala/bug/assets/161079/4ce28adc-d0bb-4f0f-9183-97bed0b36ecd)

**Comment by SethTisue** [comment]
![Orson_Welles_Paul_Masson_Park](https://github.com/scala/bug/assets/161079/78115979-5035-4fa1-a444-d70503c637c7)
