### ISSUE TITLE
Join operations on maps

### ISSUE THREAD

**Issue by scabug** [scala/bug#9896]
It would be great if map collections offered basic join operations such us:

- inner join
- left join
- right join

For simplicity, this operations would only join maps (thus key uniqueness is guaranteed at each collection) so the resulting maps' values would consist on pairs of values, value-optional value and optional value - value respectively. Keeping things simple but providing rich building blocks for complex algorithms.

**Comment by SethTisue** [comment]
there was further discussion at https://github.com/scala/collection-strawman/issues/71 and an implementation at https://github.com/scala/collection-strawman/pull/259 which ultimately didn't end up in stdlib, but at https://github.com/scala/scala-collection-contrib (commit: https://github.com/scala/scala-collection-contrib/commit/23db6e7cf5b55e55a360b9c6aa60c63b9d420b31)

I'm closing this ticket since these days we don't use scala/bug for feature requests. note that the bar is very high these days for adding new collections methods, as we already have a ton of them (and stdlib is frozen anyway, though not forever)
