### ISSUE TITLE
drop, take and slice methods on VectorIterator should not consume linear time

### ISSUE THREAD

**Issue by scabug** [scala/bug#9954]
As an `IndexedSeq`, `VectorIterator` does not implement its own `drop`, `take` and `slice` at the moment.
The default implementation in `Iterator` takes linear time.

This issue also affects views of `Vector` s.

**Comment by atiqsayyed** [comment]
Can I pick this one? I need some guidance on how should i approach it.
I've just started to contribute

**Comment by lrytz** [comment]
This change is most likely not binary compatible (I haven't checked), so it has to target 2.13. In this case, it does not make sense to fix it in the current source code under scala/scala, as the collections library is being reworked at https://github.com/scala/collection-strawman. You could check in the new implementation if the issue is already fixed (or maybe @szeiger knows).

**Comment by SethTisue** [comment]
the 2.13 collections are now far enough along that now would be a good time for someone to check if this is resolved there yet or not.

**Comment by NthPortal** [comment]
It does not seem to be resolved yet - `VectorIterator` inherits all of the specified methods from `Iterator`. The implementation of `take` in `Iterator` seems to be constant time (I'm not sure why it wouldn't be previously), but the others are not.

It might be worth looking to solve this in general for `Iterator`s over `IndexedSeq`s, rather than just for `VectorIterator`.

**Comment by Ichoran** [comment]
Sequential indexing can often be optimized surprisingly well, but the custom iterator shaves off another 15% of the runtime.  Also, it can't _always_ be optimized that well (if the loop is more complex), and then there's a major penalty (~10x, if you have to dig all the way down the 32-wide tree each time).

**Comment by szeiger** [comment]
`VectorIterator.drop` exists in 2.13 but still no `slice` or `take`

**Comment by szeiger** [comment]
`drop` exists but turns out to be broken as I discovered while trying to implement `take` and `slice`:

```
scala> Vector.from(0 until 20).iterator.drop(19).knownSize
res7: Int = 1

scala> Vector.from(0 until 20).iterator.drop(20).knownSize
res8: Int = 20
```
