### ISSUE TITLE
PartialFunction doesn't compose well

### ISSUE THREAD

**Issue by scabug** [scala/bug#9968]
I'd like to be able to say

```scala
{ case Good(whatever) => whatever }.andThen { case Even(num) => println("it's even!") }
```

But if I use this, although it makes a PartialFunction, it doesn't do what I want it to.  In particular, it will tell me that it's defined at Good(3).  This is because it inherits andThen from Function, and so it takes a Function as its argument.

I think overloading andThen to take a PartialFunction would be pretty disruptive, so I propose two better ways forward:

A.  provide a `compose` method on the PartialFunction object (somewhat confusing because there is also a compose method on the PartialFunction instance, but its behavior is not what we want for composing two PFs)
B.  change andThen to inspect the other function, and if it's a PartialFunction, upgrade its behavior.  (this is a thrilling runtime change, and makes its behavior inconsistent).

What do you think?

**Comment by SethTisue** [comment]
evidence people want this:

* https://stackoverflow.com/questions/21041626/chaining-partialfunctions-with-andthen-in-scala
* https://stackoverflow.com/questions/23024626/compose-partial-functions

I think a PR adding this to stdlib, in some form, would be accepted.

**Comment by SethTisue** [comment]
is there really no ticket on this older than 2016? seems strange

**Comment by insdami** [comment]
I can take this one.
I think an `andThenPartial` captures the intention quite well. Does it make sense to also have `composePartial`? So you have the equivalent of `compose` and `andThen` for `PartialFunction`

**Comment by jvican** [comment]
Are we sure here that a library change is the way to go? To me it seems the compiler should be smarter and the spec should specify the expected behaviour for partial functions, as proposed in:

> B. change andThen to inspect the other function, and if it's a PartialFunction, upgrade its behavior. (this is a thrilling runtime change, and makes its behavior inconsistent).
  
This probably requires some (simple) change to the compiler, but I think it's the best way to move forward.

**Comment by SethTisue** [comment]
"change andThen to inspect the other function": couldn't that be a library change, why would be a compiler change needed?

**Comment by NthPortal** [comment]
Because `isDefinedAt` needs to compute the result of applying the first partial function in order to test if the value is defined for the second partial function, is it worthwhile to have a special implementation of `PartialFunction` which (conservatively) caches the result of the applying the first partial function?

e.g.

```scala
class PartialAndThen[A, B, C](left: PartialFunction[A, B], right: PartialFunction[B, C])
    extends PartialFunction[A, C] {
  private[this] var cache: (A, B) = (null.asInstanceOf[A], null.asInstanceOf[B])
  def isDefinedAt(a: A): Boolean = {
    if (left.isDefinedAt(a)) {
      val tmp = left(a)
      if (right.isDefinedAt(tmp)) {
        cache = a -> tmp
        true
      } else false
    } else false
  }
  def apply(a: A): C = {
    val (a2, b2) = cache // I'm assuming this will only read the reference to `cache` once
    if (a2 eq a && a2 ne null) right(b2)
    else right(left(a))
  }
}
```

**Comment by Jasper-M** [comment]
> "change andThen to inspect the other function": couldn't that be a library change, why would be a compiler change needed?

I think a library change is partly possible. Something like

```
def andThen[C](k: B => C) =  k match {
  case pf: PartialFunction[B, C] => andThenPartial(pf)
  case f: Function1[B, C] => andThenTotal(k)
}
```

But then the example code from the issue still wouldn't work because the expected type of the argument to `andThen` is `Function1`, not `PartialFunction`. `{ case Even(num) => println("it's even!") }` will simply _not_ be compiled to a `PartialFunction`.
The compiler change required to change that might be simple, but it would probably require a SIP.

**Comment by SethTisue** [comment]
see also https://github.com/scala/scala/pull/7552
